template: testify
packages:
  github.com/stashapp/stash/pkg/models:
    config:
      include-interface-regex: ".*ReaderWriter"
      dir: ./pkg/models/mocks
      pkgname: mocks
      filename: "{{.InterfaceName}}.go"
