// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// AudioMarkerReaderWriter is an autogenerated mock type for the AudioMarkerReaderWriter type
type AudioMarkerReaderWriter struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx
func (_m *AudioMarkerReaderWriter) All(ctx context.Context) ([]*models.AudioMarker, error) {
	ret := _m.Called(ctx)

	var r0 []*models.AudioMarker
	if rf, ok := ret.Get(0).(func(context.Context) []*models.AudioMarker); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AudioMarker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx
func (_m *AudioMarkerReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByTagID provides a mock function with given fields: ctx, tagID
func (_m *AudioMarkerReaderWriter) CountByTagID(ctx context.Context, tagID int) (int, error) {
	ret := _m.Called(ctx, tagID)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, tagID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, tagID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, newAudioMarker
func (_m *AudioMarkerReaderWriter) Create(ctx context.Context, newAudioMarker *models.AudioMarker) error {
	ret := _m.Called(ctx, newAudioMarker)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AudioMarker) error); ok {
		r0 = rf(ctx, newAudioMarker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Destroy provides a mock function with given fields: ctx, id
func (_m *AudioMarkerReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *AudioMarkerReaderWriter) Find(ctx context.Context, id int) (*models.AudioMarker, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.AudioMarker
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.AudioMarker); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AudioMarker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByAudioID provides a mock function with given fields: ctx, audioID
func (_m *AudioMarkerReaderWriter) FindByAudioID(ctx context.Context, audioID int) ([]*models.AudioMarker, error) {
	ret := _m.Called(ctx, audioID)

	var r0 []*models.AudioMarker
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.AudioMarker); ok {
		r0 = rf(ctx, audioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AudioMarker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, audioID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMany provides a mock function with given fields: ctx, ids
func (_m *AudioMarkerReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.AudioMarker, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*models.AudioMarker
	if rf, ok := ret.Get(0).(func(context.Context, []int) []*models.AudioMarker); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AudioMarker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMarkerStrings provides a mock function with given fields: ctx, q, sort
func (_m *AudioMarkerReaderWriter) GetMarkerStrings(ctx context.Context, q *string, sort *string) ([]*models.MarkerStringsResultType, error) {
	ret := _m.Called(ctx, q, sort)

	var r0 []*models.MarkerStringsResultType
	if rf, ok := ret.Get(0).(func(context.Context, *string, *string) []*models.MarkerStringsResultType); ok {
		r0 = rf(ctx, q, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MarkerStringsResultType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *string, *string) error); ok {
		r1 = rf(ctx, q, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTagIDs provides a mock function with given fields: ctx, relatedID
func (_m *AudioMarkerReaderWriter) GetTagIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _m.Called(ctx, relatedID)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = rf(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: ctx, audioMarkerFilter, findFilter
func (_m *AudioMarkerReaderWriter) Query(ctx context.Context, audioMarkerFilter *models.AudioMarkerFilterType, findFilter *models.FindFilterType) ([]*models.AudioMarker, int, error) {
	ret := _m.Called(ctx, audioMarkerFilter, findFilter)

	var r0 []*models.AudioMarker
	if rf, ok := ret.Get(0).(func(context.Context, *models.AudioMarkerFilterType, *models.FindFilterType) []*models.AudioMarker); ok {
		r0 = rf(ctx, audioMarkerFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AudioMarker)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, *models.AudioMarkerFilterType, *models.FindFilterType) int); ok {
		r1 = rf(ctx, audioMarkerFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *models.AudioMarkerFilterType, *models.FindFilterType) error); ok {
		r2 = rf(ctx, audioMarkerFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// QueryCount provides a mock function with given fields: ctx, audioMarkerFilter, findFilter
func (_m *AudioMarkerReaderWriter) QueryCount(ctx context.Context, audioMarkerFilter *models.AudioMarkerFilterType, findFilter *models.FindFilterType) (int, error) {
	ret := _m.Called(ctx, audioMarkerFilter, findFilter)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *models.AudioMarkerFilterType, *models.FindFilterType) int); ok {
		r0 = rf(ctx, audioMarkerFilter, findFilter)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.AudioMarkerFilterType, *models.FindFilterType) error); ok {
		r1 = rf(ctx, audioMarkerFilter, findFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, updatedAudioMarker
func (_m *AudioMarkerReaderWriter) Update(ctx context.Context, updatedAudioMarker *models.AudioMarker) error {
	ret := _m.Called(ctx, updatedAudioMarker)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AudioMarker) error); ok {
		r0 = rf(ctx, updatedAudioMarker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePartial provides a mock function with given fields: ctx, id, updatedAudioMarker
func (_m *AudioMarkerReaderWriter) UpdatePartial(ctx context.Context, id int, updatedAudioMarker models.AudioMarkerPartial) (*models.AudioMarker, error) {
	ret := _m.Called(ctx, id, updatedAudioMarker)

	var r0 *models.AudioMarker
	if rf, ok := ret.Get(0).(func(context.Context, int, models.AudioMarkerPartial) *models.AudioMarker); ok {
		r0 = rf(ctx, id, updatedAudioMarker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AudioMarker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, models.AudioMarkerPartial) error); ok {
		r1 = rf(ctx, id, updatedAudioMarker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTags provides a mock function with given fields: ctx, markerID, tagIDs
func (_m *AudioMarkerReaderWriter) UpdateTags(ctx context.Context, markerID int, tagIDs []int) error {
	ret := _m.Called(ctx, markerID, tagIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = rf(ctx, markerID, tagIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Wall provides a mock function with given fields: ctx, q
func (_m *AudioMarkerReaderWriter) Wall(ctx context.Context, q *string) ([]*models.AudioMarker, error) {
	ret := _m.Called(ctx, q)

	var r0 []*models.AudioMarker
	if rf, ok := ret.Get(0).(func(context.Context, *string) []*models.AudioMarker); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AudioMarker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
