// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io/fs"

	"github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileReaderWriter creates a new instance of MockFileReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileReaderWriter {
	mock := &MockFileReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileReaderWriter is an autogenerated mock type for the FileReaderWriter type
type MockFileReaderWriter struct {
	mock.Mock
}

type MockFileReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileReaderWriter) EXPECT() *MockFileReaderWriter_Expecter {
	return &MockFileReaderWriter_Expecter{mock: &_m.Mock}
}

// CountAllInPaths provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) CountAllInPaths(ctx context.Context, p []string) (int, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CountAllInPaths")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (int, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) int); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_CountAllInPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAllInPaths'
type MockFileReaderWriter_CountAllInPaths_Call struct {
	*mock.Call
}

// CountAllInPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - p []string
func (_e *MockFileReaderWriter_Expecter) CountAllInPaths(ctx interface{}, p interface{}) *MockFileReaderWriter_CountAllInPaths_Call {
	return &MockFileReaderWriter_CountAllInPaths_Call{Call: _e.mock.On("CountAllInPaths", ctx, p)}
}

func (_c *MockFileReaderWriter_CountAllInPaths_Call) Run(run func(ctx context.Context, p []string)) *MockFileReaderWriter_CountAllInPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_CountAllInPaths_Call) Return(n int, err error) *MockFileReaderWriter_CountAllInPaths_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFileReaderWriter_CountAllInPaths_Call) RunAndReturn(run func(ctx context.Context, p []string) (int, error)) *MockFileReaderWriter_CountAllInPaths_Call {
	_c.Call.Return(run)
	return _c
}

// CountByFolderID provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) CountByFolderID(ctx context.Context, folderID models.FolderID) (int, error) {
	ret := _mock.Called(ctx, folderID)

	if len(ret) == 0 {
		panic("no return value specified for CountByFolderID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FolderID) (int, error)); ok {
		return returnFunc(ctx, folderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FolderID) int); ok {
		r0 = returnFunc(ctx, folderID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FolderID) error); ok {
		r1 = returnFunc(ctx, folderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_CountByFolderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByFolderID'
type MockFileReaderWriter_CountByFolderID_Call struct {
	*mock.Call
}

// CountByFolderID is a helper method to define mock.On call
//   - ctx context.Context
//   - folderID models.FolderID
func (_e *MockFileReaderWriter_Expecter) CountByFolderID(ctx interface{}, folderID interface{}) *MockFileReaderWriter_CountByFolderID_Call {
	return &MockFileReaderWriter_CountByFolderID_Call{Call: _e.mock.On("CountByFolderID", ctx, folderID)}
}

func (_c *MockFileReaderWriter_CountByFolderID_Call) Run(run func(ctx context.Context, folderID models.FolderID)) *MockFileReaderWriter_CountByFolderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FolderID
		if args[1] != nil {
			arg1 = args[1].(models.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_CountByFolderID_Call) Return(n int, err error) *MockFileReaderWriter_CountByFolderID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFileReaderWriter_CountByFolderID_Call) RunAndReturn(run func(ctx context.Context, folderID models.FolderID) (int, error)) *MockFileReaderWriter_CountByFolderID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) Create(ctx context.Context, f models.File) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.File) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileReaderWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileReaderWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - f models.File
func (_e *MockFileReaderWriter_Expecter) Create(ctx interface{}, f interface{}) *MockFileReaderWriter_Create_Call {
	return &MockFileReaderWriter_Create_Call{Call: _e.mock.On("Create", ctx, f)}
}

func (_c *MockFileReaderWriter_Create_Call) Run(run func(ctx context.Context, f models.File)) *MockFileReaderWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.File
		if args[1] != nil {
			arg1 = args[1].(models.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_Create_Call) Return(err error) *MockFileReaderWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileReaderWriter_Create_Call) RunAndReturn(run func(ctx context.Context, f models.File) error) *MockFileReaderWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) Destroy(ctx context.Context, id models.FileID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileReaderWriter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockFileReaderWriter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - id models.FileID
func (_e *MockFileReaderWriter_Expecter) Destroy(ctx interface{}, id interface{}) *MockFileReaderWriter_Destroy_Call {
	return &MockFileReaderWriter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, id)}
}

func (_c *MockFileReaderWriter_Destroy_Call) Run(run func(ctx context.Context, id models.FileID)) *MockFileReaderWriter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_Destroy_Call) Return(err error) *MockFileReaderWriter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileReaderWriter_Destroy_Call) RunAndReturn(run func(ctx context.Context, id models.FileID) error) *MockFileReaderWriter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// DestroyFingerprints provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) DestroyFingerprints(ctx context.Context, fileID models.FileID, types []string) error {
	ret := _mock.Called(ctx, fileID, types)

	if len(ret) == 0 {
		panic("no return value specified for DestroyFingerprints")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID, []string) error); ok {
		r0 = returnFunc(ctx, fileID, types)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileReaderWriter_DestroyFingerprints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroyFingerprints'
type MockFileReaderWriter_DestroyFingerprints_Call struct {
	*mock.Call
}

// DestroyFingerprints is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
//   - types []string
func (_e *MockFileReaderWriter_Expecter) DestroyFingerprints(ctx interface{}, fileID interface{}, types interface{}) *MockFileReaderWriter_DestroyFingerprints_Call {
	return &MockFileReaderWriter_DestroyFingerprints_Call{Call: _e.mock.On("DestroyFingerprints", ctx, fileID, types)}
}

func (_c *MockFileReaderWriter_DestroyFingerprints_Call) Run(run func(ctx context.Context, fileID models.FileID, types []string)) *MockFileReaderWriter_DestroyFingerprints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_DestroyFingerprints_Call) Return(err error) *MockFileReaderWriter_DestroyFingerprints_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileReaderWriter_DestroyFingerprints_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID, types []string) error) *MockFileReaderWriter_DestroyFingerprints_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) Find(ctx context.Context, id ...models.FileID) ([]models.File, error) {
	var tmpRet mock.Arguments
	if len(id) > 0 {
		tmpRet = _mock.Called(ctx, id)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...models.FileID) ([]models.File, error)); ok {
		return returnFunc(ctx, id...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...models.FileID) []models.File); ok {
		r0 = returnFunc(ctx, id...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...models.FileID) error); ok {
		r1 = returnFunc(ctx, id...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockFileReaderWriter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id ...models.FileID
func (_e *MockFileReaderWriter_Expecter) Find(ctx interface{}, id ...interface{}) *MockFileReaderWriter_Find_Call {
	return &MockFileReaderWriter_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx}, id...)...)}
}

func (_c *MockFileReaderWriter_Find_Call) Run(run func(ctx context.Context, id ...models.FileID)) *MockFileReaderWriter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.FileID
		var variadicArgs []models.FileID
		if len(args) > 1 {
			variadicArgs = args[1].([]models.FileID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_Find_Call) Return(files []models.File, err error) *MockFileReaderWriter_Find_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileReaderWriter_Find_Call) RunAndReturn(run func(ctx context.Context, id ...models.FileID) ([]models.File, error)) *MockFileReaderWriter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByPath provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) FindAllByPath(ctx context.Context, path string) ([]models.File, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByPath")
	}

	var r0 []models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.File, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.File); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_FindAllByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByPath'
type MockFileReaderWriter_FindAllByPath_Call struct {
	*mock.Call
}

// FindAllByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockFileReaderWriter_Expecter) FindAllByPath(ctx interface{}, path interface{}) *MockFileReaderWriter_FindAllByPath_Call {
	return &MockFileReaderWriter_FindAllByPath_Call{Call: _e.mock.On("FindAllByPath", ctx, path)}
}

func (_c *MockFileReaderWriter_FindAllByPath_Call) Run(run func(ctx context.Context, path string)) *MockFileReaderWriter_FindAllByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_FindAllByPath_Call) Return(files []models.File, err error) *MockFileReaderWriter_FindAllByPath_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileReaderWriter_FindAllByPath_Call) RunAndReturn(run func(ctx context.Context, path string) ([]models.File, error)) *MockFileReaderWriter_FindAllByPath_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllInPaths provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) FindAllInPaths(ctx context.Context, p []string, limit int, offset int) ([]models.File, error) {
	ret := _mock.Called(ctx, p, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllInPaths")
	}

	var r0 []models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int, int) ([]models.File, error)); ok {
		return returnFunc(ctx, p, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, int, int) []models.File); ok {
		r0 = returnFunc(ctx, p, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, int, int) error); ok {
		r1 = returnFunc(ctx, p, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_FindAllInPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllInPaths'
type MockFileReaderWriter_FindAllInPaths_Call struct {
	*mock.Call
}

// FindAllInPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - p []string
//   - limit int
//   - offset int
func (_e *MockFileReaderWriter_Expecter) FindAllInPaths(ctx interface{}, p interface{}, limit interface{}, offset interface{}) *MockFileReaderWriter_FindAllInPaths_Call {
	return &MockFileReaderWriter_FindAllInPaths_Call{Call: _e.mock.On("FindAllInPaths", ctx, p, limit, offset)}
}

func (_c *MockFileReaderWriter_FindAllInPaths_Call) Run(run func(ctx context.Context, p []string, limit int, offset int)) *MockFileReaderWriter_FindAllInPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_FindAllInPaths_Call) Return(files []models.File, err error) *MockFileReaderWriter_FindAllInPaths_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileReaderWriter_FindAllInPaths_Call) RunAndReturn(run func(ctx context.Context, p []string, limit int, offset int) ([]models.File, error)) *MockFileReaderWriter_FindAllInPaths_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFileInfo provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) FindByFileInfo(ctx context.Context, info fs.FileInfo, size int64) ([]models.File, error) {
	ret := _mock.Called(ctx, info, size)

	if len(ret) == 0 {
		panic("no return value specified for FindByFileInfo")
	}

	var r0 []models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, fs.FileInfo, int64) ([]models.File, error)); ok {
		return returnFunc(ctx, info, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, fs.FileInfo, int64) []models.File); ok {
		r0 = returnFunc(ctx, info, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, fs.FileInfo, int64) error); ok {
		r1 = returnFunc(ctx, info, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_FindByFileInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFileInfo'
type MockFileReaderWriter_FindByFileInfo_Call struct {
	*mock.Call
}

// FindByFileInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - info fs.FileInfo
//   - size int64
func (_e *MockFileReaderWriter_Expecter) FindByFileInfo(ctx interface{}, info interface{}, size interface{}) *MockFileReaderWriter_FindByFileInfo_Call {
	return &MockFileReaderWriter_FindByFileInfo_Call{Call: _e.mock.On("FindByFileInfo", ctx, info, size)}
}

func (_c *MockFileReaderWriter_FindByFileInfo_Call) Run(run func(ctx context.Context, info fs.FileInfo, size int64)) *MockFileReaderWriter_FindByFileInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_FindByFileInfo_Call) Return(files []models.File, err error) *MockFileReaderWriter_FindByFileInfo_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileReaderWriter_FindByFileInfo_Call) RunAndReturn(run func(ctx context.Context, info fs.FileInfo, size int64) ([]models.File, error)) *MockFileReaderWriter_FindByFileInfo_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFingerprint provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) FindByFingerprint(ctx context.Context, fp models.Fingerprint) ([]models.File, error) {
	ret := _mock.Called(ctx, fp)

	if len(ret) == 0 {
		panic("no return value specified for FindByFingerprint")
	}

	var r0 []models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Fingerprint) ([]models.File, error)); ok {
		return returnFunc(ctx, fp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Fingerprint) []models.File); ok {
		r0 = returnFunc(ctx, fp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Fingerprint) error); ok {
		r1 = returnFunc(ctx, fp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_FindByFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFingerprint'
type MockFileReaderWriter_FindByFingerprint_Call struct {
	*mock.Call
}

// FindByFingerprint is a helper method to define mock.On call
//   - ctx context.Context
//   - fp models.Fingerprint
func (_e *MockFileReaderWriter_Expecter) FindByFingerprint(ctx interface{}, fp interface{}) *MockFileReaderWriter_FindByFingerprint_Call {
	return &MockFileReaderWriter_FindByFingerprint_Call{Call: _e.mock.On("FindByFingerprint", ctx, fp)}
}

func (_c *MockFileReaderWriter_FindByFingerprint_Call) Run(run func(ctx context.Context, fp models.Fingerprint)) *MockFileReaderWriter_FindByFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Fingerprint
		if args[1] != nil {
			arg1 = args[1].(models.Fingerprint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_FindByFingerprint_Call) Return(files []models.File, err error) *MockFileReaderWriter_FindByFingerprint_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileReaderWriter_FindByFingerprint_Call) RunAndReturn(run func(ctx context.Context, fp models.Fingerprint) ([]models.File, error)) *MockFileReaderWriter_FindByFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPath provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) FindByPath(ctx context.Context, path string) (models.File, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for FindByPath")
	}

	var r0 models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.File, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.File); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_FindByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPath'
type MockFileReaderWriter_FindByPath_Call struct {
	*mock.Call
}

// FindByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockFileReaderWriter_Expecter) FindByPath(ctx interface{}, path interface{}) *MockFileReaderWriter_FindByPath_Call {
	return &MockFileReaderWriter_FindByPath_Call{Call: _e.mock.On("FindByPath", ctx, path)}
}

func (_c *MockFileReaderWriter_FindByPath_Call) Run(run func(ctx context.Context, path string)) *MockFileReaderWriter_FindByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_FindByPath_Call) Return(file models.File, err error) *MockFileReaderWriter_FindByPath_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileReaderWriter_FindByPath_Call) RunAndReturn(run func(ctx context.Context, path string) (models.File, error)) *MockFileReaderWriter_FindByPath_Call {
	_c.Call.Return(run)
	return _c
}

// FindByZipFileID provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) FindByZipFileID(ctx context.Context, zipFileID models.FileID) ([]models.File, error) {
	ret := _mock.Called(ctx, zipFileID)

	if len(ret) == 0 {
		panic("no return value specified for FindByZipFileID")
	}

	var r0 []models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) ([]models.File, error)); ok {
		return returnFunc(ctx, zipFileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) []models.File); ok {
		r0 = returnFunc(ctx, zipFileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileID) error); ok {
		r1 = returnFunc(ctx, zipFileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_FindByZipFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByZipFileID'
type MockFileReaderWriter_FindByZipFileID_Call struct {
	*mock.Call
}

// FindByZipFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - zipFileID models.FileID
func (_e *MockFileReaderWriter_Expecter) FindByZipFileID(ctx interface{}, zipFileID interface{}) *MockFileReaderWriter_FindByZipFileID_Call {
	return &MockFileReaderWriter_FindByZipFileID_Call{Call: _e.mock.On("FindByZipFileID", ctx, zipFileID)}
}

func (_c *MockFileReaderWriter_FindByZipFileID_Call) Run(run func(ctx context.Context, zipFileID models.FileID)) *MockFileReaderWriter_FindByZipFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_FindByZipFileID_Call) Return(files []models.File, err error) *MockFileReaderWriter_FindByZipFileID_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileReaderWriter_FindByZipFileID_Call) RunAndReturn(run func(ctx context.Context, zipFileID models.FileID) ([]models.File, error)) *MockFileReaderWriter_FindByZipFileID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCaptions provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) GetCaptions(ctx context.Context, fileID models.FileID) ([]*models.VideoCaption, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetCaptions")
	}

	var r0 []*models.VideoCaption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) ([]*models.VideoCaption, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) []*models.VideoCaption); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.VideoCaption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_GetCaptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCaptions'
type MockFileReaderWriter_GetCaptions_Call struct {
	*mock.Call
}

// GetCaptions is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
func (_e *MockFileReaderWriter_Expecter) GetCaptions(ctx interface{}, fileID interface{}) *MockFileReaderWriter_GetCaptions_Call {
	return &MockFileReaderWriter_GetCaptions_Call{Call: _e.mock.On("GetCaptions", ctx, fileID)}
}

func (_c *MockFileReaderWriter_GetCaptions_Call) Run(run func(ctx context.Context, fileID models.FileID)) *MockFileReaderWriter_GetCaptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_GetCaptions_Call) Return(videoCaptions []*models.VideoCaption, err error) *MockFileReaderWriter_GetCaptions_Call {
	_c.Call.Return(videoCaptions, err)
	return _c
}

func (_c *MockFileReaderWriter_GetCaptions_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID) ([]*models.VideoCaption, error)) *MockFileReaderWriter_GetCaptions_Call {
	_c.Call.Return(run)
	return _c
}

// IsPrimary provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) IsPrimary(ctx context.Context, fileID models.FileID) (bool, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for IsPrimary")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) (bool, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) bool); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_IsPrimary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPrimary'
type MockFileReaderWriter_IsPrimary_Call struct {
	*mock.Call
}

// IsPrimary is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
func (_e *MockFileReaderWriter_Expecter) IsPrimary(ctx interface{}, fileID interface{}) *MockFileReaderWriter_IsPrimary_Call {
	return &MockFileReaderWriter_IsPrimary_Call{Call: _e.mock.On("IsPrimary", ctx, fileID)}
}

func (_c *MockFileReaderWriter_IsPrimary_Call) Run(run func(ctx context.Context, fileID models.FileID)) *MockFileReaderWriter_IsPrimary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_IsPrimary_Call) Return(b bool, err error) *MockFileReaderWriter_IsPrimary_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFileReaderWriter_IsPrimary_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID) (bool, error)) *MockFileReaderWriter_IsPrimary_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyFingerprints provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) ModifyFingerprints(ctx context.Context, fileID models.FileID, fingerprints []models.Fingerprint) error {
	ret := _mock.Called(ctx, fileID, fingerprints)

	if len(ret) == 0 {
		panic("no return value specified for ModifyFingerprints")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID, []models.Fingerprint) error); ok {
		r0 = returnFunc(ctx, fileID, fingerprints)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileReaderWriter_ModifyFingerprints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyFingerprints'
type MockFileReaderWriter_ModifyFingerprints_Call struct {
	*mock.Call
}

// ModifyFingerprints is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
//   - fingerprints []models.Fingerprint
func (_e *MockFileReaderWriter_Expecter) ModifyFingerprints(ctx interface{}, fileID interface{}, fingerprints interface{}) *MockFileReaderWriter_ModifyFingerprints_Call {
	return &MockFileReaderWriter_ModifyFingerprints_Call{Call: _e.mock.On("ModifyFingerprints", ctx, fileID, fingerprints)}
}

func (_c *MockFileReaderWriter_ModifyFingerprints_Call) Run(run func(ctx context.Context, fileID models.FileID, fingerprints []models.Fingerprint)) *MockFileReaderWriter_ModifyFingerprints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		var arg2 []models.Fingerprint
		if args[2] != nil {
			arg2 = args[2].([]models.Fingerprint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_ModifyFingerprints_Call) Return(err error) *MockFileReaderWriter_ModifyFingerprints_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileReaderWriter_ModifyFingerprints_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID, fingerprints []models.Fingerprint) error) *MockFileReaderWriter_ModifyFingerprints_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) Query(ctx context.Context, options models.FileQueryOptions) (*models.FileQueryResult, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *models.FileQueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileQueryOptions) (*models.FileQueryResult, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileQueryOptions) *models.FileQueryResult); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileQueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileQueryOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileReaderWriter_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockFileReaderWriter_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - options models.FileQueryOptions
func (_e *MockFileReaderWriter_Expecter) Query(ctx interface{}, options interface{}) *MockFileReaderWriter_Query_Call {
	return &MockFileReaderWriter_Query_Call{Call: _e.mock.On("Query", ctx, options)}
}

func (_c *MockFileReaderWriter_Query_Call) Run(run func(ctx context.Context, options models.FileQueryOptions)) *MockFileReaderWriter_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileQueryOptions
		if args[1] != nil {
			arg1 = args[1].(models.FileQueryOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_Query_Call) Return(fileQueryResult *models.FileQueryResult, err error) *MockFileReaderWriter_Query_Call {
	_c.Call.Return(fileQueryResult, err)
	return _c
}

func (_c *MockFileReaderWriter_Query_Call) RunAndReturn(run func(ctx context.Context, options models.FileQueryOptions) (*models.FileQueryResult, error)) *MockFileReaderWriter_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) Update(ctx context.Context, f models.File) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.File) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileReaderWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFileReaderWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - f models.File
func (_e *MockFileReaderWriter_Expecter) Update(ctx interface{}, f interface{}) *MockFileReaderWriter_Update_Call {
	return &MockFileReaderWriter_Update_Call{Call: _e.mock.On("Update", ctx, f)}
}

func (_c *MockFileReaderWriter_Update_Call) Run(run func(ctx context.Context, f models.File)) *MockFileReaderWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.File
		if args[1] != nil {
			arg1 = args[1].(models.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_Update_Call) Return(err error) *MockFileReaderWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileReaderWriter_Update_Call) RunAndReturn(run func(ctx context.Context, f models.File) error) *MockFileReaderWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCaptions provides a mock function for the type MockFileReaderWriter
func (_mock *MockFileReaderWriter) UpdateCaptions(ctx context.Context, fileID models.FileID, captions []*models.VideoCaption) error {
	ret := _mock.Called(ctx, fileID, captions)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCaptions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID, []*models.VideoCaption) error); ok {
		r0 = returnFunc(ctx, fileID, captions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileReaderWriter_UpdateCaptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCaptions'
type MockFileReaderWriter_UpdateCaptions_Call struct {
	*mock.Call
}

// UpdateCaptions is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
//   - captions []*models.VideoCaption
func (_e *MockFileReaderWriter_Expecter) UpdateCaptions(ctx interface{}, fileID interface{}, captions interface{}) *MockFileReaderWriter_UpdateCaptions_Call {
	return &MockFileReaderWriter_UpdateCaptions_Call{Call: _e.mock.On("UpdateCaptions", ctx, fileID, captions)}
}

func (_c *MockFileReaderWriter_UpdateCaptions_Call) Run(run func(ctx context.Context, fileID models.FileID, captions []*models.VideoCaption)) *MockFileReaderWriter_UpdateCaptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		var arg2 []*models.VideoCaption
		if args[2] != nil {
			arg2 = args[2].([]*models.VideoCaption)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileReaderWriter_UpdateCaptions_Call) Return(err error) *MockFileReaderWriter_UpdateCaptions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileReaderWriter_UpdateCaptions_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID, captions []*models.VideoCaption) error) *MockFileReaderWriter_UpdateCaptions_Call {
	_c.Call.Return(run)
	return _c
}
