// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGalleryReaderWriter creates a new instance of MockGalleryReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGalleryReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGalleryReaderWriter {
	mock := &MockGalleryReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGalleryReaderWriter is an autogenerated mock type for the GalleryReaderWriter type
type MockGalleryReaderWriter struct {
	mock.Mock
}

type MockGalleryReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGalleryReaderWriter) EXPECT() *MockGalleryReaderWriter_Expecter {
	return &MockGalleryReaderWriter_Expecter{mock: &_m.Mock}
}

// AddFileID provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) AddFileID(ctx context.Context, id int, fileID models.FileID) error {
	ret := _mock.Called(ctx, id, fileID)

	if len(ret) == 0 {
		panic("no return value specified for AddFileID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.FileID) error); ok {
		r0 = returnFunc(ctx, id, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_AddFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFileID'
type MockGalleryReaderWriter_AddFileID_Call struct {
	*mock.Call
}

// AddFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - fileID models.FileID
func (_e *MockGalleryReaderWriter_Expecter) AddFileID(ctx interface{}, id interface{}, fileID interface{}) *MockGalleryReaderWriter_AddFileID_Call {
	return &MockGalleryReaderWriter_AddFileID_Call{Call: _e.mock.On("AddFileID", ctx, id, fileID)}
}

func (_c *MockGalleryReaderWriter_AddFileID_Call) Run(run func(ctx context.Context, id int, fileID models.FileID)) *MockGalleryReaderWriter_AddFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.FileID
		if args[2] != nil {
			arg2 = args[2].(models.FileID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_AddFileID_Call) Return(err error) *MockGalleryReaderWriter_AddFileID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_AddFileID_Call) RunAndReturn(run func(ctx context.Context, id int, fileID models.FileID) error) *MockGalleryReaderWriter_AddFileID_Call {
	_c.Call.Return(run)
	return _c
}

// AddImages provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) AddImages(ctx context.Context, galleryID int, imageIDs ...int) error {
	var tmpRet mock.Arguments
	if len(imageIDs) > 0 {
		tmpRet = _mock.Called(ctx, galleryID, imageIDs)
	} else {
		tmpRet = _mock.Called(ctx, galleryID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddImages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...int) error); ok {
		r0 = returnFunc(ctx, galleryID, imageIDs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_AddImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddImages'
type MockGalleryReaderWriter_AddImages_Call struct {
	*mock.Call
}

// AddImages is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
//   - imageIDs ...int
func (_e *MockGalleryReaderWriter_Expecter) AddImages(ctx interface{}, galleryID interface{}, imageIDs ...interface{}) *MockGalleryReaderWriter_AddImages_Call {
	return &MockGalleryReaderWriter_AddImages_Call{Call: _e.mock.On("AddImages",
		append([]interface{}{ctx, galleryID}, imageIDs...)...)}
}

func (_c *MockGalleryReaderWriter_AddImages_Call) Run(run func(ctx context.Context, galleryID int, imageIDs ...int)) *MockGalleryReaderWriter_AddImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		var variadicArgs []int
		if len(args) > 2 {
			variadicArgs = args[2].([]int)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_AddImages_Call) Return(err error) *MockGalleryReaderWriter_AddImages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_AddImages_Call) RunAndReturn(run func(ctx context.Context, galleryID int, imageIDs ...int) error) *MockGalleryReaderWriter_AddImages_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) All(ctx context.Context) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.Gallery); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockGalleryReaderWriter_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGalleryReaderWriter_Expecter) All(ctx interface{}) *MockGalleryReaderWriter_All_Call {
	return &MockGalleryReaderWriter_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockGalleryReaderWriter_All_Call) Run(run func(ctx context.Context)) *MockGalleryReaderWriter_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_All_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_All_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_All_Call) RunAndReturn(run func(ctx context.Context) ([]*models.Gallery, error)) *MockGalleryReaderWriter_All_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockGalleryReaderWriter_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGalleryReaderWriter_Expecter) Count(ctx interface{}) *MockGalleryReaderWriter_Count_Call {
	return &MockGalleryReaderWriter_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockGalleryReaderWriter_Count_Call) Run(run func(ctx context.Context)) *MockGalleryReaderWriter_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_Count_Call) Return(n int, err error) *MockGalleryReaderWriter_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGalleryReaderWriter_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockGalleryReaderWriter_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByFileID provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) CountByFileID(ctx context.Context, fileID models.FileID) (int, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for CountByFileID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) (int, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) int); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_CountByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByFileID'
type MockGalleryReaderWriter_CountByFileID_Call struct {
	*mock.Call
}

// CountByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
func (_e *MockGalleryReaderWriter_Expecter) CountByFileID(ctx interface{}, fileID interface{}) *MockGalleryReaderWriter_CountByFileID_Call {
	return &MockGalleryReaderWriter_CountByFileID_Call{Call: _e.mock.On("CountByFileID", ctx, fileID)}
}

func (_c *MockGalleryReaderWriter_CountByFileID_Call) Run(run func(ctx context.Context, fileID models.FileID)) *MockGalleryReaderWriter_CountByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_CountByFileID_Call) Return(n int, err error) *MockGalleryReaderWriter_CountByFileID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGalleryReaderWriter_CountByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID) (int, error)) *MockGalleryReaderWriter_CountByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) Create(ctx context.Context, newGallery *models.Gallery, fileIDs []models.FileID) error {
	ret := _mock.Called(ctx, newGallery, fileIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Gallery, []models.FileID) error); ok {
		r0 = returnFunc(ctx, newGallery, fileIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGalleryReaderWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newGallery *models.Gallery
//   - fileIDs []models.FileID
func (_e *MockGalleryReaderWriter_Expecter) Create(ctx interface{}, newGallery interface{}, fileIDs interface{}) *MockGalleryReaderWriter_Create_Call {
	return &MockGalleryReaderWriter_Create_Call{Call: _e.mock.On("Create", ctx, newGallery, fileIDs)}
}

func (_c *MockGalleryReaderWriter_Create_Call) Run(run func(ctx context.Context, newGallery *models.Gallery, fileIDs []models.FileID)) *MockGalleryReaderWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Gallery
		if args[1] != nil {
			arg1 = args[1].(*models.Gallery)
		}
		var arg2 []models.FileID
		if args[2] != nil {
			arg2 = args[2].([]models.FileID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_Create_Call) Return(err error) *MockGalleryReaderWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_Create_Call) RunAndReturn(run func(ctx context.Context, newGallery *models.Gallery, fileIDs []models.FileID) error) *MockGalleryReaderWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockGalleryReaderWriter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGalleryReaderWriter_Expecter) Destroy(ctx interface{}, id interface{}) *MockGalleryReaderWriter_Destroy_Call {
	return &MockGalleryReaderWriter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, id)}
}

func (_c *MockGalleryReaderWriter_Destroy_Call) Run(run func(ctx context.Context, id int)) *MockGalleryReaderWriter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_Destroy_Call) Return(err error) *MockGalleryReaderWriter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_Destroy_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockGalleryReaderWriter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) Find(ctx context.Context, id int) (*models.Gallery, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Gallery, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Gallery); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockGalleryReaderWriter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGalleryReaderWriter_Expecter) Find(ctx interface{}, id interface{}) *MockGalleryReaderWriter_Find_Call {
	return &MockGalleryReaderWriter_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockGalleryReaderWriter_Find_Call) Run(run func(ctx context.Context, id int)) *MockGalleryReaderWriter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_Find_Call) Return(gallery *models.Gallery, err error) *MockGalleryReaderWriter_Find_Call {
	_c.Call.Return(gallery, err)
	return _c
}

func (_c *MockGalleryReaderWriter_Find_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Gallery, error)) *MockGalleryReaderWriter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByChecksum provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindByChecksum(ctx context.Context, checksum string) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, checksum)

	if len(ret) == 0 {
		panic("no return value specified for FindByChecksum")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, checksum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.Gallery); ok {
		r0 = returnFunc(ctx, checksum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, checksum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindByChecksum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByChecksum'
type MockGalleryReaderWriter_FindByChecksum_Call struct {
	*mock.Call
}

// FindByChecksum is a helper method to define mock.On call
//   - ctx context.Context
//   - checksum string
func (_e *MockGalleryReaderWriter_Expecter) FindByChecksum(ctx interface{}, checksum interface{}) *MockGalleryReaderWriter_FindByChecksum_Call {
	return &MockGalleryReaderWriter_FindByChecksum_Call{Call: _e.mock.On("FindByChecksum", ctx, checksum)}
}

func (_c *MockGalleryReaderWriter_FindByChecksum_Call) Run(run func(ctx context.Context, checksum string)) *MockGalleryReaderWriter_FindByChecksum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindByChecksum_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindByChecksum_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindByChecksum_Call) RunAndReturn(run func(ctx context.Context, checksum string) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindByChecksum_Call {
	_c.Call.Return(run)
	return _c
}

// FindByChecksums provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindByChecksums(ctx context.Context, checksums []string) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, checksums)

	if len(ret) == 0 {
		panic("no return value specified for FindByChecksums")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, checksums)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*models.Gallery); ok {
		r0 = returnFunc(ctx, checksums)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, checksums)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindByChecksums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByChecksums'
type MockGalleryReaderWriter_FindByChecksums_Call struct {
	*mock.Call
}

// FindByChecksums is a helper method to define mock.On call
//   - ctx context.Context
//   - checksums []string
func (_e *MockGalleryReaderWriter_Expecter) FindByChecksums(ctx interface{}, checksums interface{}) *MockGalleryReaderWriter_FindByChecksums_Call {
	return &MockGalleryReaderWriter_FindByChecksums_Call{Call: _e.mock.On("FindByChecksums", ctx, checksums)}
}

func (_c *MockGalleryReaderWriter_FindByChecksums_Call) Run(run func(ctx context.Context, checksums []string)) *MockGalleryReaderWriter_FindByChecksums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindByChecksums_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindByChecksums_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindByChecksums_Call) RunAndReturn(run func(ctx context.Context, checksums []string) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindByChecksums_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFileID provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindByFileID(ctx context.Context, fileID models.FileID) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for FindByFileID")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) []*models.Gallery); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFileID'
type MockGalleryReaderWriter_FindByFileID_Call struct {
	*mock.Call
}

// FindByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
func (_e *MockGalleryReaderWriter_Expecter) FindByFileID(ctx interface{}, fileID interface{}) *MockGalleryReaderWriter_FindByFileID_Call {
	return &MockGalleryReaderWriter_FindByFileID_Call{Call: _e.mock.On("FindByFileID", ctx, fileID)}
}

func (_c *MockGalleryReaderWriter_FindByFileID_Call) Run(run func(ctx context.Context, fileID models.FileID)) *MockGalleryReaderWriter_FindByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindByFileID_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindByFileID_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFingerprints provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindByFingerprints(ctx context.Context, fp []models.Fingerprint) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, fp)

	if len(ret) == 0 {
		panic("no return value specified for FindByFingerprints")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Fingerprint) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, fp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Fingerprint) []*models.Gallery); ok {
		r0 = returnFunc(ctx, fp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []models.Fingerprint) error); ok {
		r1 = returnFunc(ctx, fp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindByFingerprints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFingerprints'
type MockGalleryReaderWriter_FindByFingerprints_Call struct {
	*mock.Call
}

// FindByFingerprints is a helper method to define mock.On call
//   - ctx context.Context
//   - fp []models.Fingerprint
func (_e *MockGalleryReaderWriter_Expecter) FindByFingerprints(ctx interface{}, fp interface{}) *MockGalleryReaderWriter_FindByFingerprints_Call {
	return &MockGalleryReaderWriter_FindByFingerprints_Call{Call: _e.mock.On("FindByFingerprints", ctx, fp)}
}

func (_c *MockGalleryReaderWriter_FindByFingerprints_Call) Run(run func(ctx context.Context, fp []models.Fingerprint)) *MockGalleryReaderWriter_FindByFingerprints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Fingerprint
		if args[1] != nil {
			arg1 = args[1].([]models.Fingerprint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindByFingerprints_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindByFingerprints_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindByFingerprints_Call) RunAndReturn(run func(ctx context.Context, fp []models.Fingerprint) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindByFingerprints_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFolderID provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindByFolderID(ctx context.Context, folderID models.FolderID) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, folderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByFolderID")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FolderID) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, folderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FolderID) []*models.Gallery); ok {
		r0 = returnFunc(ctx, folderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FolderID) error); ok {
		r1 = returnFunc(ctx, folderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindByFolderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFolderID'
type MockGalleryReaderWriter_FindByFolderID_Call struct {
	*mock.Call
}

// FindByFolderID is a helper method to define mock.On call
//   - ctx context.Context
//   - folderID models.FolderID
func (_e *MockGalleryReaderWriter_Expecter) FindByFolderID(ctx interface{}, folderID interface{}) *MockGalleryReaderWriter_FindByFolderID_Call {
	return &MockGalleryReaderWriter_FindByFolderID_Call{Call: _e.mock.On("FindByFolderID", ctx, folderID)}
}

func (_c *MockGalleryReaderWriter_FindByFolderID_Call) Run(run func(ctx context.Context, folderID models.FolderID)) *MockGalleryReaderWriter_FindByFolderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FolderID
		if args[1] != nil {
			arg1 = args[1].(models.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindByFolderID_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindByFolderID_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindByFolderID_Call) RunAndReturn(run func(ctx context.Context, folderID models.FolderID) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindByFolderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByImageID provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindByImageID(ctx context.Context, imageID int) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for FindByImageID")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Gallery); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindByImageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByImageID'
type MockGalleryReaderWriter_FindByImageID_Call struct {
	*mock.Call
}

// FindByImageID is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID int
func (_e *MockGalleryReaderWriter_Expecter) FindByImageID(ctx interface{}, imageID interface{}) *MockGalleryReaderWriter_FindByImageID_Call {
	return &MockGalleryReaderWriter_FindByImageID_Call{Call: _e.mock.On("FindByImageID", ctx, imageID)}
}

func (_c *MockGalleryReaderWriter_FindByImageID_Call) Run(run func(ctx context.Context, imageID int)) *MockGalleryReaderWriter_FindByImageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindByImageID_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindByImageID_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindByImageID_Call) RunAndReturn(run func(ctx context.Context, imageID int) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindByImageID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPath provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindByPath(ctx context.Context, path string) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for FindByPath")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.Gallery); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPath'
type MockGalleryReaderWriter_FindByPath_Call struct {
	*mock.Call
}

// FindByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGalleryReaderWriter_Expecter) FindByPath(ctx interface{}, path interface{}) *MockGalleryReaderWriter_FindByPath_Call {
	return &MockGalleryReaderWriter_FindByPath_Call{Call: _e.mock.On("FindByPath", ctx, path)}
}

func (_c *MockGalleryReaderWriter_FindByPath_Call) Run(run func(ctx context.Context, path string)) *MockGalleryReaderWriter_FindByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindByPath_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindByPath_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindByPath_Call) RunAndReturn(run func(ctx context.Context, path string) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindByPath_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySceneID provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindBySceneID(ctx context.Context, sceneID int) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, sceneID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySceneID")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, sceneID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Gallery); ok {
		r0 = returnFunc(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindBySceneID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySceneID'
type MockGalleryReaderWriter_FindBySceneID_Call struct {
	*mock.Call
}

// FindBySceneID is a helper method to define mock.On call
//   - ctx context.Context
//   - sceneID int
func (_e *MockGalleryReaderWriter_Expecter) FindBySceneID(ctx interface{}, sceneID interface{}) *MockGalleryReaderWriter_FindBySceneID_Call {
	return &MockGalleryReaderWriter_FindBySceneID_Call{Call: _e.mock.On("FindBySceneID", ctx, sceneID)}
}

func (_c *MockGalleryReaderWriter_FindBySceneID_Call) Run(run func(ctx context.Context, sceneID int)) *MockGalleryReaderWriter_FindBySceneID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindBySceneID_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindBySceneID_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindBySceneID_Call) RunAndReturn(run func(ctx context.Context, sceneID int) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindBySceneID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMany provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindMany")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []*models.Gallery); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMany'
type MockGalleryReaderWriter_FindMany_Call struct {
	*mock.Call
}

// FindMany is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockGalleryReaderWriter_Expecter) FindMany(ctx interface{}, ids interface{}) *MockGalleryReaderWriter_FindMany_Call {
	return &MockGalleryReaderWriter_FindMany_Call{Call: _e.mock.On("FindMany", ctx, ids)}
}

func (_c *MockGalleryReaderWriter_FindMany_Call) Run(run func(ctx context.Context, ids []int)) *MockGalleryReaderWriter_FindMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindMany_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindMany_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindMany_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserGalleryByTitle provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) FindUserGalleryByTitle(ctx context.Context, title string) ([]*models.Gallery, error) {
	ret := _mock.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for FindUserGalleryByTitle")
	}

	var r0 []*models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.Gallery, error)); ok {
		return returnFunc(ctx, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.Gallery); ok {
		r0 = returnFunc(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_FindUserGalleryByTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserGalleryByTitle'
type MockGalleryReaderWriter_FindUserGalleryByTitle_Call struct {
	*mock.Call
}

// FindUserGalleryByTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
func (_e *MockGalleryReaderWriter_Expecter) FindUserGalleryByTitle(ctx interface{}, title interface{}) *MockGalleryReaderWriter_FindUserGalleryByTitle_Call {
	return &MockGalleryReaderWriter_FindUserGalleryByTitle_Call{Call: _e.mock.On("FindUserGalleryByTitle", ctx, title)}
}

func (_c *MockGalleryReaderWriter_FindUserGalleryByTitle_Call) Run(run func(ctx context.Context, title string)) *MockGalleryReaderWriter_FindUserGalleryByTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_FindUserGalleryByTitle_Call) Return(gallerys []*models.Gallery, err error) *MockGalleryReaderWriter_FindUserGalleryByTitle_Call {
	_c.Call.Return(gallerys, err)
	return _c
}

func (_c *MockGalleryReaderWriter_FindUserGalleryByTitle_Call) RunAndReturn(run func(ctx context.Context, title string) ([]*models.Gallery, error)) *MockGalleryReaderWriter_FindUserGalleryByTitle_Call {
	_c.Call.Return(run)
	return _c
}

// GetFiles provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) GetFiles(ctx context.Context, relatedID int) ([]models.File, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetFiles")
	}

	var r0 []models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.File, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.File); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_GetFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFiles'
type MockGalleryReaderWriter_GetFiles_Call struct {
	*mock.Call
}

// GetFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockGalleryReaderWriter_Expecter) GetFiles(ctx interface{}, relatedID interface{}) *MockGalleryReaderWriter_GetFiles_Call {
	return &MockGalleryReaderWriter_GetFiles_Call{Call: _e.mock.On("GetFiles", ctx, relatedID)}
}

func (_c *MockGalleryReaderWriter_GetFiles_Call) Run(run func(ctx context.Context, relatedID int)) *MockGalleryReaderWriter_GetFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_GetFiles_Call) Return(files []models.File, err error) *MockGalleryReaderWriter_GetFiles_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockGalleryReaderWriter_GetFiles_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]models.File, error)) *MockGalleryReaderWriter_GetFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageIDs provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) GetImageIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetImageIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_GetImageIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageIDs'
type MockGalleryReaderWriter_GetImageIDs_Call struct {
	*mock.Call
}

// GetImageIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockGalleryReaderWriter_Expecter) GetImageIDs(ctx interface{}, relatedID interface{}) *MockGalleryReaderWriter_GetImageIDs_Call {
	return &MockGalleryReaderWriter_GetImageIDs_Call{Call: _e.mock.On("GetImageIDs", ctx, relatedID)}
}

func (_c *MockGalleryReaderWriter_GetImageIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockGalleryReaderWriter_GetImageIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_GetImageIDs_Call) Return(ints []int, err error) *MockGalleryReaderWriter_GetImageIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockGalleryReaderWriter_GetImageIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockGalleryReaderWriter_GetImageIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetManyFileIDs provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) GetManyFileIDs(ctx context.Context, ids []int) ([][]models.FileID, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetManyFileIDs")
	}

	var r0 [][]models.FileID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([][]models.FileID, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) [][]models.FileID); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]models.FileID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_GetManyFileIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManyFileIDs'
type MockGalleryReaderWriter_GetManyFileIDs_Call struct {
	*mock.Call
}

// GetManyFileIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockGalleryReaderWriter_Expecter) GetManyFileIDs(ctx interface{}, ids interface{}) *MockGalleryReaderWriter_GetManyFileIDs_Call {
	return &MockGalleryReaderWriter_GetManyFileIDs_Call{Call: _e.mock.On("GetManyFileIDs", ctx, ids)}
}

func (_c *MockGalleryReaderWriter_GetManyFileIDs_Call) Run(run func(ctx context.Context, ids []int)) *MockGalleryReaderWriter_GetManyFileIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_GetManyFileIDs_Call) Return(fileIDss [][]models.FileID, err error) *MockGalleryReaderWriter_GetManyFileIDs_Call {
	_c.Call.Return(fileIDss, err)
	return _c
}

func (_c *MockGalleryReaderWriter_GetManyFileIDs_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([][]models.FileID, error)) *MockGalleryReaderWriter_GetManyFileIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetPerformerIDs provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) GetPerformerIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetPerformerIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_GetPerformerIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPerformerIDs'
type MockGalleryReaderWriter_GetPerformerIDs_Call struct {
	*mock.Call
}

// GetPerformerIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockGalleryReaderWriter_Expecter) GetPerformerIDs(ctx interface{}, relatedID interface{}) *MockGalleryReaderWriter_GetPerformerIDs_Call {
	return &MockGalleryReaderWriter_GetPerformerIDs_Call{Call: _e.mock.On("GetPerformerIDs", ctx, relatedID)}
}

func (_c *MockGalleryReaderWriter_GetPerformerIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockGalleryReaderWriter_GetPerformerIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_GetPerformerIDs_Call) Return(ints []int, err error) *MockGalleryReaderWriter_GetPerformerIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockGalleryReaderWriter_GetPerformerIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockGalleryReaderWriter_GetPerformerIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSceneIDs provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) GetSceneIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetSceneIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_GetSceneIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSceneIDs'
type MockGalleryReaderWriter_GetSceneIDs_Call struct {
	*mock.Call
}

// GetSceneIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockGalleryReaderWriter_Expecter) GetSceneIDs(ctx interface{}, relatedID interface{}) *MockGalleryReaderWriter_GetSceneIDs_Call {
	return &MockGalleryReaderWriter_GetSceneIDs_Call{Call: _e.mock.On("GetSceneIDs", ctx, relatedID)}
}

func (_c *MockGalleryReaderWriter_GetSceneIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockGalleryReaderWriter_GetSceneIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_GetSceneIDs_Call) Return(ints []int, err error) *MockGalleryReaderWriter_GetSceneIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockGalleryReaderWriter_GetSceneIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockGalleryReaderWriter_GetSceneIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagIDs provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) GetTagIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_GetTagIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagIDs'
type MockGalleryReaderWriter_GetTagIDs_Call struct {
	*mock.Call
}

// GetTagIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockGalleryReaderWriter_Expecter) GetTagIDs(ctx interface{}, relatedID interface{}) *MockGalleryReaderWriter_GetTagIDs_Call {
	return &MockGalleryReaderWriter_GetTagIDs_Call{Call: _e.mock.On("GetTagIDs", ctx, relatedID)}
}

func (_c *MockGalleryReaderWriter_GetTagIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockGalleryReaderWriter_GetTagIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_GetTagIDs_Call) Return(ints []int, err error) *MockGalleryReaderWriter_GetTagIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockGalleryReaderWriter_GetTagIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockGalleryReaderWriter_GetTagIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLs provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) GetURLs(ctx context.Context, relatedID int) ([]string, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetURLs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_GetURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLs'
type MockGalleryReaderWriter_GetURLs_Call struct {
	*mock.Call
}

// GetURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockGalleryReaderWriter_Expecter) GetURLs(ctx interface{}, relatedID interface{}) *MockGalleryReaderWriter_GetURLs_Call {
	return &MockGalleryReaderWriter_GetURLs_Call{Call: _e.mock.On("GetURLs", ctx, relatedID)}
}

func (_c *MockGalleryReaderWriter_GetURLs_Call) Run(run func(ctx context.Context, relatedID int)) *MockGalleryReaderWriter_GetURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_GetURLs_Call) Return(strings []string, err error) *MockGalleryReaderWriter_GetURLs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGalleryReaderWriter_GetURLs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]string, error)) *MockGalleryReaderWriter_GetURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) Query(ctx context.Context, galleryFilter *models.GalleryFilterType, findFilter *models.FindFilterType) ([]*models.Gallery, int, error) {
	ret := _mock.Called(ctx, galleryFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []*models.Gallery
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GalleryFilterType, *models.FindFilterType) ([]*models.Gallery, int, error)); ok {
		return returnFunc(ctx, galleryFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GalleryFilterType, *models.FindFilterType) []*models.Gallery); ok {
		r0 = returnFunc(ctx, galleryFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.GalleryFilterType, *models.FindFilterType) int); ok {
		r1 = returnFunc(ctx, galleryFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *models.GalleryFilterType, *models.FindFilterType) error); ok {
		r2 = returnFunc(ctx, galleryFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGalleryReaderWriter_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockGalleryReaderWriter_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryFilter *models.GalleryFilterType
//   - findFilter *models.FindFilterType
func (_e *MockGalleryReaderWriter_Expecter) Query(ctx interface{}, galleryFilter interface{}, findFilter interface{}) *MockGalleryReaderWriter_Query_Call {
	return &MockGalleryReaderWriter_Query_Call{Call: _e.mock.On("Query", ctx, galleryFilter, findFilter)}
}

func (_c *MockGalleryReaderWriter_Query_Call) Run(run func(ctx context.Context, galleryFilter *models.GalleryFilterType, findFilter *models.FindFilterType)) *MockGalleryReaderWriter_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.GalleryFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.GalleryFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_Query_Call) Return(gallerys []*models.Gallery, n int, err error) *MockGalleryReaderWriter_Query_Call {
	_c.Call.Return(gallerys, n, err)
	return _c
}

func (_c *MockGalleryReaderWriter_Query_Call) RunAndReturn(run func(ctx context.Context, galleryFilter *models.GalleryFilterType, findFilter *models.FindFilterType) ([]*models.Gallery, int, error)) *MockGalleryReaderWriter_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryCount provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) QueryCount(ctx context.Context, galleryFilter *models.GalleryFilterType, findFilter *models.FindFilterType) (int, error) {
	ret := _mock.Called(ctx, galleryFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for QueryCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GalleryFilterType, *models.FindFilterType) (int, error)); ok {
		return returnFunc(ctx, galleryFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GalleryFilterType, *models.FindFilterType) int); ok {
		r0 = returnFunc(ctx, galleryFilter, findFilter)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.GalleryFilterType, *models.FindFilterType) error); ok {
		r1 = returnFunc(ctx, galleryFilter, findFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_QueryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryCount'
type MockGalleryReaderWriter_QueryCount_Call struct {
	*mock.Call
}

// QueryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryFilter *models.GalleryFilterType
//   - findFilter *models.FindFilterType
func (_e *MockGalleryReaderWriter_Expecter) QueryCount(ctx interface{}, galleryFilter interface{}, findFilter interface{}) *MockGalleryReaderWriter_QueryCount_Call {
	return &MockGalleryReaderWriter_QueryCount_Call{Call: _e.mock.On("QueryCount", ctx, galleryFilter, findFilter)}
}

func (_c *MockGalleryReaderWriter_QueryCount_Call) Run(run func(ctx context.Context, galleryFilter *models.GalleryFilterType, findFilter *models.FindFilterType)) *MockGalleryReaderWriter_QueryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.GalleryFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.GalleryFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_QueryCount_Call) Return(n int, err error) *MockGalleryReaderWriter_QueryCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGalleryReaderWriter_QueryCount_Call) RunAndReturn(run func(ctx context.Context, galleryFilter *models.GalleryFilterType, findFilter *models.FindFilterType) (int, error)) *MockGalleryReaderWriter_QueryCount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImages provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) RemoveImages(ctx context.Context, galleryID int, imageIDs ...int) error {
	var tmpRet mock.Arguments
	if len(imageIDs) > 0 {
		tmpRet = _mock.Called(ctx, galleryID, imageIDs)
	} else {
		tmpRet = _mock.Called(ctx, galleryID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveImages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...int) error); ok {
		r0 = returnFunc(ctx, galleryID, imageIDs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_RemoveImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImages'
type MockGalleryReaderWriter_RemoveImages_Call struct {
	*mock.Call
}

// RemoveImages is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
//   - imageIDs ...int
func (_e *MockGalleryReaderWriter_Expecter) RemoveImages(ctx interface{}, galleryID interface{}, imageIDs ...interface{}) *MockGalleryReaderWriter_RemoveImages_Call {
	return &MockGalleryReaderWriter_RemoveImages_Call{Call: _e.mock.On("RemoveImages",
		append([]interface{}{ctx, galleryID}, imageIDs...)...)}
}

func (_c *MockGalleryReaderWriter_RemoveImages_Call) Run(run func(ctx context.Context, galleryID int, imageIDs ...int)) *MockGalleryReaderWriter_RemoveImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		var variadicArgs []int
		if len(args) > 2 {
			variadicArgs = args[2].([]int)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_RemoveImages_Call) Return(err error) *MockGalleryReaderWriter_RemoveImages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_RemoveImages_Call) RunAndReturn(run func(ctx context.Context, galleryID int, imageIDs ...int) error) *MockGalleryReaderWriter_RemoveImages_Call {
	_c.Call.Return(run)
	return _c
}

// ResetCover provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) ResetCover(ctx context.Context, galleryID int) error {
	ret := _mock.Called(ctx, galleryID)

	if len(ret) == 0 {
		panic("no return value specified for ResetCover")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, galleryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_ResetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetCover'
type MockGalleryReaderWriter_ResetCover_Call struct {
	*mock.Call
}

// ResetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
func (_e *MockGalleryReaderWriter_Expecter) ResetCover(ctx interface{}, galleryID interface{}) *MockGalleryReaderWriter_ResetCover_Call {
	return &MockGalleryReaderWriter_ResetCover_Call{Call: _e.mock.On("ResetCover", ctx, galleryID)}
}

func (_c *MockGalleryReaderWriter_ResetCover_Call) Run(run func(ctx context.Context, galleryID int)) *MockGalleryReaderWriter_ResetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_ResetCover_Call) Return(err error) *MockGalleryReaderWriter_ResetCover_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_ResetCover_Call) RunAndReturn(run func(ctx context.Context, galleryID int) error) *MockGalleryReaderWriter_ResetCover_Call {
	_c.Call.Return(run)
	return _c
}

// SetCover provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) SetCover(ctx context.Context, galleryID int, coverImageID int) error {
	ret := _mock.Called(ctx, galleryID, coverImageID)

	if len(ret) == 0 {
		panic("no return value specified for SetCover")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, galleryID, coverImageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_SetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCover'
type MockGalleryReaderWriter_SetCover_Call struct {
	*mock.Call
}

// SetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
//   - coverImageID int
func (_e *MockGalleryReaderWriter_Expecter) SetCover(ctx interface{}, galleryID interface{}, coverImageID interface{}) *MockGalleryReaderWriter_SetCover_Call {
	return &MockGalleryReaderWriter_SetCover_Call{Call: _e.mock.On("SetCover", ctx, galleryID, coverImageID)}
}

func (_c *MockGalleryReaderWriter_SetCover_Call) Run(run func(ctx context.Context, galleryID int, coverImageID int)) *MockGalleryReaderWriter_SetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_SetCover_Call) Return(err error) *MockGalleryReaderWriter_SetCover_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_SetCover_Call) RunAndReturn(run func(ctx context.Context, galleryID int, coverImageID int) error) *MockGalleryReaderWriter_SetCover_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) Update(ctx context.Context, updatedGallery *models.Gallery) error {
	ret := _mock.Called(ctx, updatedGallery)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Gallery) error); ok {
		r0 = returnFunc(ctx, updatedGallery)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGalleryReaderWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - updatedGallery *models.Gallery
func (_e *MockGalleryReaderWriter_Expecter) Update(ctx interface{}, updatedGallery interface{}) *MockGalleryReaderWriter_Update_Call {
	return &MockGalleryReaderWriter_Update_Call{Call: _e.mock.On("Update", ctx, updatedGallery)}
}

func (_c *MockGalleryReaderWriter_Update_Call) Run(run func(ctx context.Context, updatedGallery *models.Gallery)) *MockGalleryReaderWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Gallery
		if args[1] != nil {
			arg1 = args[1].(*models.Gallery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_Update_Call) Return(err error) *MockGalleryReaderWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_Update_Call) RunAndReturn(run func(ctx context.Context, updatedGallery *models.Gallery) error) *MockGalleryReaderWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImages provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) UpdateImages(ctx context.Context, galleryID int, imageIDs []int) error {
	ret := _mock.Called(ctx, galleryID, imageIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = returnFunc(ctx, galleryID, imageIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGalleryReaderWriter_UpdateImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImages'
type MockGalleryReaderWriter_UpdateImages_Call struct {
	*mock.Call
}

// UpdateImages is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
//   - imageIDs []int
func (_e *MockGalleryReaderWriter_Expecter) UpdateImages(ctx interface{}, galleryID interface{}, imageIDs interface{}) *MockGalleryReaderWriter_UpdateImages_Call {
	return &MockGalleryReaderWriter_UpdateImages_Call{Call: _e.mock.On("UpdateImages", ctx, galleryID, imageIDs)}
}

func (_c *MockGalleryReaderWriter_UpdateImages_Call) Run(run func(ctx context.Context, galleryID int, imageIDs []int)) *MockGalleryReaderWriter_UpdateImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_UpdateImages_Call) Return(err error) *MockGalleryReaderWriter_UpdateImages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGalleryReaderWriter_UpdateImages_Call) RunAndReturn(run func(ctx context.Context, galleryID int, imageIDs []int) error) *MockGalleryReaderWriter_UpdateImages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePartial provides a mock function for the type MockGalleryReaderWriter
func (_mock *MockGalleryReaderWriter) UpdatePartial(ctx context.Context, id int, updatedGallery models.GalleryPartial) (*models.Gallery, error) {
	ret := _mock.Called(ctx, id, updatedGallery)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePartial")
	}

	var r0 *models.Gallery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.GalleryPartial) (*models.Gallery, error)); ok {
		return returnFunc(ctx, id, updatedGallery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.GalleryPartial) *models.Gallery); ok {
		r0 = returnFunc(ctx, id, updatedGallery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Gallery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.GalleryPartial) error); ok {
		r1 = returnFunc(ctx, id, updatedGallery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGalleryReaderWriter_UpdatePartial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePartial'
type MockGalleryReaderWriter_UpdatePartial_Call struct {
	*mock.Call
}

// UpdatePartial is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - updatedGallery models.GalleryPartial
func (_e *MockGalleryReaderWriter_Expecter) UpdatePartial(ctx interface{}, id interface{}, updatedGallery interface{}) *MockGalleryReaderWriter_UpdatePartial_Call {
	return &MockGalleryReaderWriter_UpdatePartial_Call{Call: _e.mock.On("UpdatePartial", ctx, id, updatedGallery)}
}

func (_c *MockGalleryReaderWriter_UpdatePartial_Call) Run(run func(ctx context.Context, id int, updatedGallery models.GalleryPartial)) *MockGalleryReaderWriter_UpdatePartial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.GalleryPartial
		if args[2] != nil {
			arg2 = args[2].(models.GalleryPartial)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGalleryReaderWriter_UpdatePartial_Call) Return(gallery *models.Gallery, err error) *MockGalleryReaderWriter_UpdatePartial_Call {
	_c.Call.Return(gallery, err)
	return _c
}

func (_c *MockGalleryReaderWriter_UpdatePartial_Call) RunAndReturn(run func(ctx context.Context, id int, updatedGallery models.GalleryPartial) (*models.Gallery, error)) *MockGalleryReaderWriter_UpdatePartial_Call {
	_c.Call.Return(run)
	return _c
}
