// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGroupReaderWriter creates a new instance of MockGroupReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupReaderWriter {
	mock := &MockGroupReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGroupReaderWriter is an autogenerated mock type for the GroupReaderWriter type
type MockGroupReaderWriter struct {
	mock.Mock
}

type MockGroupReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupReaderWriter) EXPECT() *MockGroupReaderWriter_Expecter {
	return &MockGroupReaderWriter_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) All(ctx context.Context) ([]*models.Group, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.Group, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.Group); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockGroupReaderWriter_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGroupReaderWriter_Expecter) All(ctx interface{}) *MockGroupReaderWriter_All_Call {
	return &MockGroupReaderWriter_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockGroupReaderWriter_All_Call) Run(run func(ctx context.Context)) *MockGroupReaderWriter_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_All_Call) Return(groups []*models.Group, err error) *MockGroupReaderWriter_All_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupReaderWriter_All_Call) RunAndReturn(run func(ctx context.Context) ([]*models.Group, error)) *MockGroupReaderWriter_All_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockGroupReaderWriter_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGroupReaderWriter_Expecter) Count(ctx interface{}) *MockGroupReaderWriter_Count_Call {
	return &MockGroupReaderWriter_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockGroupReaderWriter_Count_Call) Run(run func(ctx context.Context)) *MockGroupReaderWriter_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_Count_Call) Return(n int, err error) *MockGroupReaderWriter_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGroupReaderWriter_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockGroupReaderWriter_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByPerformerID provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) CountByPerformerID(ctx context.Context, performerID int) (int, error) {
	ret := _mock.Called(ctx, performerID)

	if len(ret) == 0 {
		panic("no return value specified for CountByPerformerID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, performerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, performerID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, performerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_CountByPerformerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByPerformerID'
type MockGroupReaderWriter_CountByPerformerID_Call struct {
	*mock.Call
}

// CountByPerformerID is a helper method to define mock.On call
//   - ctx context.Context
//   - performerID int
func (_e *MockGroupReaderWriter_Expecter) CountByPerformerID(ctx interface{}, performerID interface{}) *MockGroupReaderWriter_CountByPerformerID_Call {
	return &MockGroupReaderWriter_CountByPerformerID_Call{Call: _e.mock.On("CountByPerformerID", ctx, performerID)}
}

func (_c *MockGroupReaderWriter_CountByPerformerID_Call) Run(run func(ctx context.Context, performerID int)) *MockGroupReaderWriter_CountByPerformerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_CountByPerformerID_Call) Return(n int, err error) *MockGroupReaderWriter_CountByPerformerID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGroupReaderWriter_CountByPerformerID_Call) RunAndReturn(run func(ctx context.Context, performerID int) (int, error)) *MockGroupReaderWriter_CountByPerformerID_Call {
	_c.Call.Return(run)
	return _c
}

// CountByStudioID provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) CountByStudioID(ctx context.Context, studioID int) (int, error) {
	ret := _mock.Called(ctx, studioID)

	if len(ret) == 0 {
		panic("no return value specified for CountByStudioID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, studioID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, studioID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, studioID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_CountByStudioID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStudioID'
type MockGroupReaderWriter_CountByStudioID_Call struct {
	*mock.Call
}

// CountByStudioID is a helper method to define mock.On call
//   - ctx context.Context
//   - studioID int
func (_e *MockGroupReaderWriter_Expecter) CountByStudioID(ctx interface{}, studioID interface{}) *MockGroupReaderWriter_CountByStudioID_Call {
	return &MockGroupReaderWriter_CountByStudioID_Call{Call: _e.mock.On("CountByStudioID", ctx, studioID)}
}

func (_c *MockGroupReaderWriter_CountByStudioID_Call) Run(run func(ctx context.Context, studioID int)) *MockGroupReaderWriter_CountByStudioID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_CountByStudioID_Call) Return(n int, err error) *MockGroupReaderWriter_CountByStudioID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGroupReaderWriter_CountByStudioID_Call) RunAndReturn(run func(ctx context.Context, studioID int) (int, error)) *MockGroupReaderWriter_CountByStudioID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) Create(ctx context.Context, newGroup *models.Group) error {
	ret := _mock.Called(ctx, newGroup)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Group) error); ok {
		r0 = returnFunc(ctx, newGroup)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupReaderWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupReaderWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newGroup *models.Group
func (_e *MockGroupReaderWriter_Expecter) Create(ctx interface{}, newGroup interface{}) *MockGroupReaderWriter_Create_Call {
	return &MockGroupReaderWriter_Create_Call{Call: _e.mock.On("Create", ctx, newGroup)}
}

func (_c *MockGroupReaderWriter_Create_Call) Run(run func(ctx context.Context, newGroup *models.Group)) *MockGroupReaderWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Group
		if args[1] != nil {
			arg1 = args[1].(*models.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_Create_Call) Return(err error) *MockGroupReaderWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupReaderWriter_Create_Call) RunAndReturn(run func(ctx context.Context, newGroup *models.Group) error) *MockGroupReaderWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupReaderWriter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockGroupReaderWriter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGroupReaderWriter_Expecter) Destroy(ctx interface{}, id interface{}) *MockGroupReaderWriter_Destroy_Call {
	return &MockGroupReaderWriter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, id)}
}

func (_c *MockGroupReaderWriter_Destroy_Call) Run(run func(ctx context.Context, id int)) *MockGroupReaderWriter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_Destroy_Call) Return(err error) *MockGroupReaderWriter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupReaderWriter_Destroy_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockGroupReaderWriter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) Find(ctx context.Context, id int) (*models.Group, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Group, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Group); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockGroupReaderWriter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGroupReaderWriter_Expecter) Find(ctx interface{}, id interface{}) *MockGroupReaderWriter_Find_Call {
	return &MockGroupReaderWriter_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockGroupReaderWriter_Find_Call) Run(run func(ctx context.Context, id int)) *MockGroupReaderWriter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_Find_Call) Return(group *models.Group, err error) *MockGroupReaderWriter_Find_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupReaderWriter_Find_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Group, error)) *MockGroupReaderWriter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) FindByName(ctx context.Context, name string, nocase bool) (*models.Group, error) {
	ret := _mock.Called(ctx, name, nocase)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*models.Group, error)); ok {
		return returnFunc(ctx, name, nocase)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *models.Group); ok {
		r0 = returnFunc(ctx, name, nocase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, name, nocase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockGroupReaderWriter_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - nocase bool
func (_e *MockGroupReaderWriter_Expecter) FindByName(ctx interface{}, name interface{}, nocase interface{}) *MockGroupReaderWriter_FindByName_Call {
	return &MockGroupReaderWriter_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name, nocase)}
}

func (_c *MockGroupReaderWriter_FindByName_Call) Run(run func(ctx context.Context, name string, nocase bool)) *MockGroupReaderWriter_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_FindByName_Call) Return(group *models.Group, err error) *MockGroupReaderWriter_FindByName_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupReaderWriter_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string, nocase bool) (*models.Group, error)) *MockGroupReaderWriter_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNames provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) FindByNames(ctx context.Context, names []string, nocase bool) ([]*models.Group, error) {
	ret := _mock.Called(ctx, names, nocase)

	if len(ret) == 0 {
		panic("no return value specified for FindByNames")
	}

	var r0 []*models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool) ([]*models.Group, error)); ok {
		return returnFunc(ctx, names, nocase)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool) []*models.Group); ok {
		r0 = returnFunc(ctx, names, nocase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, bool) error); ok {
		r1 = returnFunc(ctx, names, nocase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_FindByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNames'
type MockGroupReaderWriter_FindByNames_Call struct {
	*mock.Call
}

// FindByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
//   - nocase bool
func (_e *MockGroupReaderWriter_Expecter) FindByNames(ctx interface{}, names interface{}, nocase interface{}) *MockGroupReaderWriter_FindByNames_Call {
	return &MockGroupReaderWriter_FindByNames_Call{Call: _e.mock.On("FindByNames", ctx, names, nocase)}
}

func (_c *MockGroupReaderWriter_FindByNames_Call) Run(run func(ctx context.Context, names []string, nocase bool)) *MockGroupReaderWriter_FindByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_FindByNames_Call) Return(groups []*models.Group, err error) *MockGroupReaderWriter_FindByNames_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupReaderWriter_FindByNames_Call) RunAndReturn(run func(ctx context.Context, names []string, nocase bool) ([]*models.Group, error)) *MockGroupReaderWriter_FindByNames_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPerformerID provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) FindByPerformerID(ctx context.Context, performerID int) ([]*models.Group, error) {
	ret := _mock.Called(ctx, performerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPerformerID")
	}

	var r0 []*models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Group, error)); ok {
		return returnFunc(ctx, performerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Group); ok {
		r0 = returnFunc(ctx, performerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, performerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_FindByPerformerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPerformerID'
type MockGroupReaderWriter_FindByPerformerID_Call struct {
	*mock.Call
}

// FindByPerformerID is a helper method to define mock.On call
//   - ctx context.Context
//   - performerID int
func (_e *MockGroupReaderWriter_Expecter) FindByPerformerID(ctx interface{}, performerID interface{}) *MockGroupReaderWriter_FindByPerformerID_Call {
	return &MockGroupReaderWriter_FindByPerformerID_Call{Call: _e.mock.On("FindByPerformerID", ctx, performerID)}
}

func (_c *MockGroupReaderWriter_FindByPerformerID_Call) Run(run func(ctx context.Context, performerID int)) *MockGroupReaderWriter_FindByPerformerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_FindByPerformerID_Call) Return(groups []*models.Group, err error) *MockGroupReaderWriter_FindByPerformerID_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupReaderWriter_FindByPerformerID_Call) RunAndReturn(run func(ctx context.Context, performerID int) ([]*models.Group, error)) *MockGroupReaderWriter_FindByPerformerID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStudioID provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) FindByStudioID(ctx context.Context, studioID int) ([]*models.Group, error) {
	ret := _mock.Called(ctx, studioID)

	if len(ret) == 0 {
		panic("no return value specified for FindByStudioID")
	}

	var r0 []*models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Group, error)); ok {
		return returnFunc(ctx, studioID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Group); ok {
		r0 = returnFunc(ctx, studioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, studioID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_FindByStudioID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStudioID'
type MockGroupReaderWriter_FindByStudioID_Call struct {
	*mock.Call
}

// FindByStudioID is a helper method to define mock.On call
//   - ctx context.Context
//   - studioID int
func (_e *MockGroupReaderWriter_Expecter) FindByStudioID(ctx interface{}, studioID interface{}) *MockGroupReaderWriter_FindByStudioID_Call {
	return &MockGroupReaderWriter_FindByStudioID_Call{Call: _e.mock.On("FindByStudioID", ctx, studioID)}
}

func (_c *MockGroupReaderWriter_FindByStudioID_Call) Run(run func(ctx context.Context, studioID int)) *MockGroupReaderWriter_FindByStudioID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_FindByStudioID_Call) Return(groups []*models.Group, err error) *MockGroupReaderWriter_FindByStudioID_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupReaderWriter_FindByStudioID_Call) RunAndReturn(run func(ctx context.Context, studioID int) ([]*models.Group, error)) *MockGroupReaderWriter_FindByStudioID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMany provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Group, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindMany")
	}

	var r0 []*models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]*models.Group, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []*models.Group); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_FindMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMany'
type MockGroupReaderWriter_FindMany_Call struct {
	*mock.Call
}

// FindMany is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockGroupReaderWriter_Expecter) FindMany(ctx interface{}, ids interface{}) *MockGroupReaderWriter_FindMany_Call {
	return &MockGroupReaderWriter_FindMany_Call{Call: _e.mock.On("FindMany", ctx, ids)}
}

func (_c *MockGroupReaderWriter_FindMany_Call) Run(run func(ctx context.Context, ids []int)) *MockGroupReaderWriter_FindMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_FindMany_Call) Return(groups []*models.Group, err error) *MockGroupReaderWriter_FindMany_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockGroupReaderWriter_FindMany_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]*models.Group, error)) *MockGroupReaderWriter_FindMany_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackImage provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) GetBackImage(ctx context.Context, groupID int) ([]byte, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackImage")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]byte, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []byte); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_GetBackImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackImage'
type MockGroupReaderWriter_GetBackImage_Call struct {
	*mock.Call
}

// GetBackImage is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int
func (_e *MockGroupReaderWriter_Expecter) GetBackImage(ctx interface{}, groupID interface{}) *MockGroupReaderWriter_GetBackImage_Call {
	return &MockGroupReaderWriter_GetBackImage_Call{Call: _e.mock.On("GetBackImage", ctx, groupID)}
}

func (_c *MockGroupReaderWriter_GetBackImage_Call) Run(run func(ctx context.Context, groupID int)) *MockGroupReaderWriter_GetBackImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_GetBackImage_Call) Return(bytes []byte, err error) *MockGroupReaderWriter_GetBackImage_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockGroupReaderWriter_GetBackImage_Call) RunAndReturn(run func(ctx context.Context, groupID int) ([]byte, error)) *MockGroupReaderWriter_GetBackImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainingGroupDescriptions provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) GetContainingGroupDescriptions(ctx context.Context, id int) ([]models.GroupIDDescription, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetContainingGroupDescriptions")
	}

	var r0 []models.GroupIDDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.GroupIDDescription, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.GroupIDDescription); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GroupIDDescription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_GetContainingGroupDescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainingGroupDescriptions'
type MockGroupReaderWriter_GetContainingGroupDescriptions_Call struct {
	*mock.Call
}

// GetContainingGroupDescriptions is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGroupReaderWriter_Expecter) GetContainingGroupDescriptions(ctx interface{}, id interface{}) *MockGroupReaderWriter_GetContainingGroupDescriptions_Call {
	return &MockGroupReaderWriter_GetContainingGroupDescriptions_Call{Call: _e.mock.On("GetContainingGroupDescriptions", ctx, id)}
}

func (_c *MockGroupReaderWriter_GetContainingGroupDescriptions_Call) Run(run func(ctx context.Context, id int)) *MockGroupReaderWriter_GetContainingGroupDescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_GetContainingGroupDescriptions_Call) Return(groupIDDescriptions []models.GroupIDDescription, err error) *MockGroupReaderWriter_GetContainingGroupDescriptions_Call {
	_c.Call.Return(groupIDDescriptions, err)
	return _c
}

func (_c *MockGroupReaderWriter_GetContainingGroupDescriptions_Call) RunAndReturn(run func(ctx context.Context, id int) ([]models.GroupIDDescription, error)) *MockGroupReaderWriter_GetContainingGroupDescriptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetFrontImage provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) GetFrontImage(ctx context.Context, groupID int) ([]byte, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetFrontImage")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]byte, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []byte); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_GetFrontImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFrontImage'
type MockGroupReaderWriter_GetFrontImage_Call struct {
	*mock.Call
}

// GetFrontImage is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int
func (_e *MockGroupReaderWriter_Expecter) GetFrontImage(ctx interface{}, groupID interface{}) *MockGroupReaderWriter_GetFrontImage_Call {
	return &MockGroupReaderWriter_GetFrontImage_Call{Call: _e.mock.On("GetFrontImage", ctx, groupID)}
}

func (_c *MockGroupReaderWriter_GetFrontImage_Call) Run(run func(ctx context.Context, groupID int)) *MockGroupReaderWriter_GetFrontImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_GetFrontImage_Call) Return(bytes []byte, err error) *MockGroupReaderWriter_GetFrontImage_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockGroupReaderWriter_GetFrontImage_Call) RunAndReturn(run func(ctx context.Context, groupID int) ([]byte, error)) *MockGroupReaderWriter_GetFrontImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubGroupDescriptions provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) GetSubGroupDescriptions(ctx context.Context, id int) ([]models.GroupIDDescription, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSubGroupDescriptions")
	}

	var r0 []models.GroupIDDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.GroupIDDescription, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.GroupIDDescription); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.GroupIDDescription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_GetSubGroupDescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubGroupDescriptions'
type MockGroupReaderWriter_GetSubGroupDescriptions_Call struct {
	*mock.Call
}

// GetSubGroupDescriptions is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGroupReaderWriter_Expecter) GetSubGroupDescriptions(ctx interface{}, id interface{}) *MockGroupReaderWriter_GetSubGroupDescriptions_Call {
	return &MockGroupReaderWriter_GetSubGroupDescriptions_Call{Call: _e.mock.On("GetSubGroupDescriptions", ctx, id)}
}

func (_c *MockGroupReaderWriter_GetSubGroupDescriptions_Call) Run(run func(ctx context.Context, id int)) *MockGroupReaderWriter_GetSubGroupDescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_GetSubGroupDescriptions_Call) Return(groupIDDescriptions []models.GroupIDDescription, err error) *MockGroupReaderWriter_GetSubGroupDescriptions_Call {
	_c.Call.Return(groupIDDescriptions, err)
	return _c
}

func (_c *MockGroupReaderWriter_GetSubGroupDescriptions_Call) RunAndReturn(run func(ctx context.Context, id int) ([]models.GroupIDDescription, error)) *MockGroupReaderWriter_GetSubGroupDescriptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagIDs provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) GetTagIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_GetTagIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagIDs'
type MockGroupReaderWriter_GetTagIDs_Call struct {
	*mock.Call
}

// GetTagIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockGroupReaderWriter_Expecter) GetTagIDs(ctx interface{}, relatedID interface{}) *MockGroupReaderWriter_GetTagIDs_Call {
	return &MockGroupReaderWriter_GetTagIDs_Call{Call: _e.mock.On("GetTagIDs", ctx, relatedID)}
}

func (_c *MockGroupReaderWriter_GetTagIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockGroupReaderWriter_GetTagIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_GetTagIDs_Call) Return(ints []int, err error) *MockGroupReaderWriter_GetTagIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockGroupReaderWriter_GetTagIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockGroupReaderWriter_GetTagIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLs provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) GetURLs(ctx context.Context, relatedID int) ([]string, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetURLs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_GetURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLs'
type MockGroupReaderWriter_GetURLs_Call struct {
	*mock.Call
}

// GetURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockGroupReaderWriter_Expecter) GetURLs(ctx interface{}, relatedID interface{}) *MockGroupReaderWriter_GetURLs_Call {
	return &MockGroupReaderWriter_GetURLs_Call{Call: _e.mock.On("GetURLs", ctx, relatedID)}
}

func (_c *MockGroupReaderWriter_GetURLs_Call) Run(run func(ctx context.Context, relatedID int)) *MockGroupReaderWriter_GetURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_GetURLs_Call) Return(strings []string, err error) *MockGroupReaderWriter_GetURLs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGroupReaderWriter_GetURLs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]string, error)) *MockGroupReaderWriter_GetURLs_Call {
	_c.Call.Return(run)
	return _c
}

// HasBackImage provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) HasBackImage(ctx context.Context, groupID int) (bool, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for HasBackImage")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_HasBackImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBackImage'
type MockGroupReaderWriter_HasBackImage_Call struct {
	*mock.Call
}

// HasBackImage is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int
func (_e *MockGroupReaderWriter_Expecter) HasBackImage(ctx interface{}, groupID interface{}) *MockGroupReaderWriter_HasBackImage_Call {
	return &MockGroupReaderWriter_HasBackImage_Call{Call: _e.mock.On("HasBackImage", ctx, groupID)}
}

func (_c *MockGroupReaderWriter_HasBackImage_Call) Run(run func(ctx context.Context, groupID int)) *MockGroupReaderWriter_HasBackImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_HasBackImage_Call) Return(b bool, err error) *MockGroupReaderWriter_HasBackImage_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGroupReaderWriter_HasBackImage_Call) RunAndReturn(run func(ctx context.Context, groupID int) (bool, error)) *MockGroupReaderWriter_HasBackImage_Call {
	_c.Call.Return(run)
	return _c
}

// HasFrontImage provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) HasFrontImage(ctx context.Context, groupID int) (bool, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for HasFrontImage")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_HasFrontImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFrontImage'
type MockGroupReaderWriter_HasFrontImage_Call struct {
	*mock.Call
}

// HasFrontImage is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int
func (_e *MockGroupReaderWriter_Expecter) HasFrontImage(ctx interface{}, groupID interface{}) *MockGroupReaderWriter_HasFrontImage_Call {
	return &MockGroupReaderWriter_HasFrontImage_Call{Call: _e.mock.On("HasFrontImage", ctx, groupID)}
}

func (_c *MockGroupReaderWriter_HasFrontImage_Call) Run(run func(ctx context.Context, groupID int)) *MockGroupReaderWriter_HasFrontImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_HasFrontImage_Call) Return(b bool, err error) *MockGroupReaderWriter_HasFrontImage_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGroupReaderWriter_HasFrontImage_Call) RunAndReturn(run func(ctx context.Context, groupID int) (bool, error)) *MockGroupReaderWriter_HasFrontImage_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) Query(ctx context.Context, groupFilter *models.GroupFilterType, findFilter *models.FindFilterType) ([]*models.Group, int, error) {
	ret := _mock.Called(ctx, groupFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []*models.Group
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GroupFilterType, *models.FindFilterType) ([]*models.Group, int, error)); ok {
		return returnFunc(ctx, groupFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GroupFilterType, *models.FindFilterType) []*models.Group); ok {
		r0 = returnFunc(ctx, groupFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.GroupFilterType, *models.FindFilterType) int); ok {
		r1 = returnFunc(ctx, groupFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *models.GroupFilterType, *models.FindFilterType) error); ok {
		r2 = returnFunc(ctx, groupFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGroupReaderWriter_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockGroupReaderWriter_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - groupFilter *models.GroupFilterType
//   - findFilter *models.FindFilterType
func (_e *MockGroupReaderWriter_Expecter) Query(ctx interface{}, groupFilter interface{}, findFilter interface{}) *MockGroupReaderWriter_Query_Call {
	return &MockGroupReaderWriter_Query_Call{Call: _e.mock.On("Query", ctx, groupFilter, findFilter)}
}

func (_c *MockGroupReaderWriter_Query_Call) Run(run func(ctx context.Context, groupFilter *models.GroupFilterType, findFilter *models.FindFilterType)) *MockGroupReaderWriter_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.GroupFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.GroupFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_Query_Call) Return(groups []*models.Group, n int, err error) *MockGroupReaderWriter_Query_Call {
	_c.Call.Return(groups, n, err)
	return _c
}

func (_c *MockGroupReaderWriter_Query_Call) RunAndReturn(run func(ctx context.Context, groupFilter *models.GroupFilterType, findFilter *models.FindFilterType) ([]*models.Group, int, error)) *MockGroupReaderWriter_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryCount provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) QueryCount(ctx context.Context, groupFilter *models.GroupFilterType, findFilter *models.FindFilterType) (int, error) {
	ret := _mock.Called(ctx, groupFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for QueryCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GroupFilterType, *models.FindFilterType) (int, error)); ok {
		return returnFunc(ctx, groupFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.GroupFilterType, *models.FindFilterType) int); ok {
		r0 = returnFunc(ctx, groupFilter, findFilter)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.GroupFilterType, *models.FindFilterType) error); ok {
		r1 = returnFunc(ctx, groupFilter, findFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_QueryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryCount'
type MockGroupReaderWriter_QueryCount_Call struct {
	*mock.Call
}

// QueryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - groupFilter *models.GroupFilterType
//   - findFilter *models.FindFilterType
func (_e *MockGroupReaderWriter_Expecter) QueryCount(ctx interface{}, groupFilter interface{}, findFilter interface{}) *MockGroupReaderWriter_QueryCount_Call {
	return &MockGroupReaderWriter_QueryCount_Call{Call: _e.mock.On("QueryCount", ctx, groupFilter, findFilter)}
}

func (_c *MockGroupReaderWriter_QueryCount_Call) Run(run func(ctx context.Context, groupFilter *models.GroupFilterType, findFilter *models.FindFilterType)) *MockGroupReaderWriter_QueryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.GroupFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.GroupFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_QueryCount_Call) Return(n int, err error) *MockGroupReaderWriter_QueryCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGroupReaderWriter_QueryCount_Call) RunAndReturn(run func(ctx context.Context, groupFilter *models.GroupFilterType, findFilter *models.FindFilterType) (int, error)) *MockGroupReaderWriter_QueryCount_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) Update(ctx context.Context, updatedGroup *models.Group) error {
	ret := _mock.Called(ctx, updatedGroup)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Group) error); ok {
		r0 = returnFunc(ctx, updatedGroup)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupReaderWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGroupReaderWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - updatedGroup *models.Group
func (_e *MockGroupReaderWriter_Expecter) Update(ctx interface{}, updatedGroup interface{}) *MockGroupReaderWriter_Update_Call {
	return &MockGroupReaderWriter_Update_Call{Call: _e.mock.On("Update", ctx, updatedGroup)}
}

func (_c *MockGroupReaderWriter_Update_Call) Run(run func(ctx context.Context, updatedGroup *models.Group)) *MockGroupReaderWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Group
		if args[1] != nil {
			arg1 = args[1].(*models.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_Update_Call) Return(err error) *MockGroupReaderWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupReaderWriter_Update_Call) RunAndReturn(run func(ctx context.Context, updatedGroup *models.Group) error) *MockGroupReaderWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBackImage provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) UpdateBackImage(ctx context.Context, groupID int, backImage []byte) error {
	ret := _mock.Called(ctx, groupID, backImage)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBackImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []byte) error); ok {
		r0 = returnFunc(ctx, groupID, backImage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupReaderWriter_UpdateBackImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBackImage'
type MockGroupReaderWriter_UpdateBackImage_Call struct {
	*mock.Call
}

// UpdateBackImage is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int
//   - backImage []byte
func (_e *MockGroupReaderWriter_Expecter) UpdateBackImage(ctx interface{}, groupID interface{}, backImage interface{}) *MockGroupReaderWriter_UpdateBackImage_Call {
	return &MockGroupReaderWriter_UpdateBackImage_Call{Call: _e.mock.On("UpdateBackImage", ctx, groupID, backImage)}
}

func (_c *MockGroupReaderWriter_UpdateBackImage_Call) Run(run func(ctx context.Context, groupID int, backImage []byte)) *MockGroupReaderWriter_UpdateBackImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_UpdateBackImage_Call) Return(err error) *MockGroupReaderWriter_UpdateBackImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupReaderWriter_UpdateBackImage_Call) RunAndReturn(run func(ctx context.Context, groupID int, backImage []byte) error) *MockGroupReaderWriter_UpdateBackImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFrontImage provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) UpdateFrontImage(ctx context.Context, groupID int, frontImage []byte) error {
	ret := _mock.Called(ctx, groupID, frontImage)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFrontImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []byte) error); ok {
		r0 = returnFunc(ctx, groupID, frontImage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGroupReaderWriter_UpdateFrontImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFrontImage'
type MockGroupReaderWriter_UpdateFrontImage_Call struct {
	*mock.Call
}

// UpdateFrontImage is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int
//   - frontImage []byte
func (_e *MockGroupReaderWriter_Expecter) UpdateFrontImage(ctx interface{}, groupID interface{}, frontImage interface{}) *MockGroupReaderWriter_UpdateFrontImage_Call {
	return &MockGroupReaderWriter_UpdateFrontImage_Call{Call: _e.mock.On("UpdateFrontImage", ctx, groupID, frontImage)}
}

func (_c *MockGroupReaderWriter_UpdateFrontImage_Call) Run(run func(ctx context.Context, groupID int, frontImage []byte)) *MockGroupReaderWriter_UpdateFrontImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_UpdateFrontImage_Call) Return(err error) *MockGroupReaderWriter_UpdateFrontImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupReaderWriter_UpdateFrontImage_Call) RunAndReturn(run func(ctx context.Context, groupID int, frontImage []byte) error) *MockGroupReaderWriter_UpdateFrontImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePartial provides a mock function for the type MockGroupReaderWriter
func (_mock *MockGroupReaderWriter) UpdatePartial(ctx context.Context, id int, updatedGroup models.GroupPartial) (*models.Group, error) {
	ret := _mock.Called(ctx, id, updatedGroup)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePartial")
	}

	var r0 *models.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.GroupPartial) (*models.Group, error)); ok {
		return returnFunc(ctx, id, updatedGroup)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.GroupPartial) *models.Group); ok {
		r0 = returnFunc(ctx, id, updatedGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.GroupPartial) error); ok {
		r1 = returnFunc(ctx, id, updatedGroup)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGroupReaderWriter_UpdatePartial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePartial'
type MockGroupReaderWriter_UpdatePartial_Call struct {
	*mock.Call
}

// UpdatePartial is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - updatedGroup models.GroupPartial
func (_e *MockGroupReaderWriter_Expecter) UpdatePartial(ctx interface{}, id interface{}, updatedGroup interface{}) *MockGroupReaderWriter_UpdatePartial_Call {
	return &MockGroupReaderWriter_UpdatePartial_Call{Call: _e.mock.On("UpdatePartial", ctx, id, updatedGroup)}
}

func (_c *MockGroupReaderWriter_UpdatePartial_Call) Run(run func(ctx context.Context, id int, updatedGroup models.GroupPartial)) *MockGroupReaderWriter_UpdatePartial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.GroupPartial
		if args[2] != nil {
			arg2 = args[2].(models.GroupPartial)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGroupReaderWriter_UpdatePartial_Call) Return(group *models.Group, err error) *MockGroupReaderWriter_UpdatePartial_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockGroupReaderWriter_UpdatePartial_Call) RunAndReturn(run func(ctx context.Context, id int, updatedGroup models.GroupPartial) (*models.Group, error)) *MockGroupReaderWriter_UpdatePartial_Call {
	_c.Call.Return(run)
	return _c
}
