// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageReaderWriter creates a new instance of MockImageReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageReaderWriter {
	mock := &MockImageReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageReaderWriter is an autogenerated mock type for the ImageReaderWriter type
type MockImageReaderWriter struct {
	mock.Mock
}

type MockImageReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageReaderWriter) EXPECT() *MockImageReaderWriter_Expecter {
	return &MockImageReaderWriter_Expecter{mock: &_m.Mock}
}

// AddFileID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) AddFileID(ctx context.Context, id int, fileID models.FileID) error {
	ret := _mock.Called(ctx, id, fileID)

	if len(ret) == 0 {
		panic("no return value specified for AddFileID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.FileID) error); ok {
		r0 = returnFunc(ctx, id, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageReaderWriter_AddFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFileID'
type MockImageReaderWriter_AddFileID_Call struct {
	*mock.Call
}

// AddFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - fileID models.FileID
func (_e *MockImageReaderWriter_Expecter) AddFileID(ctx interface{}, id interface{}, fileID interface{}) *MockImageReaderWriter_AddFileID_Call {
	return &MockImageReaderWriter_AddFileID_Call{Call: _e.mock.On("AddFileID", ctx, id, fileID)}
}

func (_c *MockImageReaderWriter_AddFileID_Call) Run(run func(ctx context.Context, id int, fileID models.FileID)) *MockImageReaderWriter_AddFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.FileID
		if args[2] != nil {
			arg2 = args[2].(models.FileID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_AddFileID_Call) Return(err error) *MockImageReaderWriter_AddFileID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageReaderWriter_AddFileID_Call) RunAndReturn(run func(ctx context.Context, id int, fileID models.FileID) error) *MockImageReaderWriter_AddFileID_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) All(ctx context.Context) ([]*models.Image, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.Image, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.Image); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockImageReaderWriter_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImageReaderWriter_Expecter) All(ctx interface{}) *MockImageReaderWriter_All_Call {
	return &MockImageReaderWriter_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockImageReaderWriter_All_Call) Run(run func(ctx context.Context)) *MockImageReaderWriter_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_All_Call) Return(images []*models.Image, err error) *MockImageReaderWriter_All_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageReaderWriter_All_Call) RunAndReturn(run func(ctx context.Context) ([]*models.Image, error)) *MockImageReaderWriter_All_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockImageReaderWriter_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImageReaderWriter_Expecter) Count(ctx interface{}) *MockImageReaderWriter_Count_Call {
	return &MockImageReaderWriter_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockImageReaderWriter_Count_Call) Run(run func(ctx context.Context)) *MockImageReaderWriter_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_Count_Call) Return(n int, err error) *MockImageReaderWriter_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockImageReaderWriter_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByFileID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) CountByFileID(ctx context.Context, fileID models.FileID) (int, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for CountByFileID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) (int, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) int); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_CountByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByFileID'
type MockImageReaderWriter_CountByFileID_Call struct {
	*mock.Call
}

// CountByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
func (_e *MockImageReaderWriter_Expecter) CountByFileID(ctx interface{}, fileID interface{}) *MockImageReaderWriter_CountByFileID_Call {
	return &MockImageReaderWriter_CountByFileID_Call{Call: _e.mock.On("CountByFileID", ctx, fileID)}
}

func (_c *MockImageReaderWriter_CountByFileID_Call) Run(run func(ctx context.Context, fileID models.FileID)) *MockImageReaderWriter_CountByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_CountByFileID_Call) Return(n int, err error) *MockImageReaderWriter_CountByFileID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_CountByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID) (int, error)) *MockImageReaderWriter_CountByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// CountByGalleryID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) CountByGalleryID(ctx context.Context, galleryID int) (int, error) {
	ret := _mock.Called(ctx, galleryID)

	if len(ret) == 0 {
		panic("no return value specified for CountByGalleryID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, galleryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, galleryID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, galleryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_CountByGalleryID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByGalleryID'
type MockImageReaderWriter_CountByGalleryID_Call struct {
	*mock.Call
}

// CountByGalleryID is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
func (_e *MockImageReaderWriter_Expecter) CountByGalleryID(ctx interface{}, galleryID interface{}) *MockImageReaderWriter_CountByGalleryID_Call {
	return &MockImageReaderWriter_CountByGalleryID_Call{Call: _e.mock.On("CountByGalleryID", ctx, galleryID)}
}

func (_c *MockImageReaderWriter_CountByGalleryID_Call) Run(run func(ctx context.Context, galleryID int)) *MockImageReaderWriter_CountByGalleryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_CountByGalleryID_Call) Return(n int, err error) *MockImageReaderWriter_CountByGalleryID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_CountByGalleryID_Call) RunAndReturn(run func(ctx context.Context, galleryID int) (int, error)) *MockImageReaderWriter_CountByGalleryID_Call {
	_c.Call.Return(run)
	return _c
}

// CoverByGalleryID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) CoverByGalleryID(ctx context.Context, galleryId int) (*models.Image, error) {
	ret := _mock.Called(ctx, galleryId)

	if len(ret) == 0 {
		panic("no return value specified for CoverByGalleryID")
	}

	var r0 *models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Image, error)); ok {
		return returnFunc(ctx, galleryId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Image); ok {
		r0 = returnFunc(ctx, galleryId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, galleryId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_CoverByGalleryID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoverByGalleryID'
type MockImageReaderWriter_CoverByGalleryID_Call struct {
	*mock.Call
}

// CoverByGalleryID is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryId int
func (_e *MockImageReaderWriter_Expecter) CoverByGalleryID(ctx interface{}, galleryId interface{}) *MockImageReaderWriter_CoverByGalleryID_Call {
	return &MockImageReaderWriter_CoverByGalleryID_Call{Call: _e.mock.On("CoverByGalleryID", ctx, galleryId)}
}

func (_c *MockImageReaderWriter_CoverByGalleryID_Call) Run(run func(ctx context.Context, galleryId int)) *MockImageReaderWriter_CoverByGalleryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_CoverByGalleryID_Call) Return(image *models.Image, err error) *MockImageReaderWriter_CoverByGalleryID_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageReaderWriter_CoverByGalleryID_Call) RunAndReturn(run func(ctx context.Context, galleryId int) (*models.Image, error)) *MockImageReaderWriter_CoverByGalleryID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) Create(ctx context.Context, newImage *models.Image, fileIDs []models.FileID) error {
	ret := _mock.Called(ctx, newImage, fileIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Image, []models.FileID) error); ok {
		r0 = returnFunc(ctx, newImage, fileIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageReaderWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockImageReaderWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newImage *models.Image
//   - fileIDs []models.FileID
func (_e *MockImageReaderWriter_Expecter) Create(ctx interface{}, newImage interface{}, fileIDs interface{}) *MockImageReaderWriter_Create_Call {
	return &MockImageReaderWriter_Create_Call{Call: _e.mock.On("Create", ctx, newImage, fileIDs)}
}

func (_c *MockImageReaderWriter_Create_Call) Run(run func(ctx context.Context, newImage *models.Image, fileIDs []models.FileID)) *MockImageReaderWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Image
		if args[1] != nil {
			arg1 = args[1].(*models.Image)
		}
		var arg2 []models.FileID
		if args[2] != nil {
			arg2 = args[2].([]models.FileID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_Create_Call) Return(err error) *MockImageReaderWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageReaderWriter_Create_Call) RunAndReturn(run func(ctx context.Context, newImage *models.Image, fileIDs []models.FileID) error) *MockImageReaderWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementOCounter provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) DecrementOCounter(ctx context.Context, id int) (int, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DecrementOCounter")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_DecrementOCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementOCounter'
type MockImageReaderWriter_DecrementOCounter_Call struct {
	*mock.Call
}

// DecrementOCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockImageReaderWriter_Expecter) DecrementOCounter(ctx interface{}, id interface{}) *MockImageReaderWriter_DecrementOCounter_Call {
	return &MockImageReaderWriter_DecrementOCounter_Call{Call: _e.mock.On("DecrementOCounter", ctx, id)}
}

func (_c *MockImageReaderWriter_DecrementOCounter_Call) Run(run func(ctx context.Context, id int)) *MockImageReaderWriter_DecrementOCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_DecrementOCounter_Call) Return(n int, err error) *MockImageReaderWriter_DecrementOCounter_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_DecrementOCounter_Call) RunAndReturn(run func(ctx context.Context, id int) (int, error)) *MockImageReaderWriter_DecrementOCounter_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageReaderWriter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockImageReaderWriter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockImageReaderWriter_Expecter) Destroy(ctx interface{}, id interface{}) *MockImageReaderWriter_Destroy_Call {
	return &MockImageReaderWriter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, id)}
}

func (_c *MockImageReaderWriter_Destroy_Call) Run(run func(ctx context.Context, id int)) *MockImageReaderWriter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_Destroy_Call) Return(err error) *MockImageReaderWriter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageReaderWriter_Destroy_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockImageReaderWriter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) Find(ctx context.Context, id int) (*models.Image, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Image, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Image); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockImageReaderWriter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockImageReaderWriter_Expecter) Find(ctx interface{}, id interface{}) *MockImageReaderWriter_Find_Call {
	return &MockImageReaderWriter_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockImageReaderWriter_Find_Call) Run(run func(ctx context.Context, id int)) *MockImageReaderWriter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_Find_Call) Return(image *models.Image, err error) *MockImageReaderWriter_Find_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageReaderWriter_Find_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Image, error)) *MockImageReaderWriter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByChecksum provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) FindByChecksum(ctx context.Context, checksum string) ([]*models.Image, error) {
	ret := _mock.Called(ctx, checksum)

	if len(ret) == 0 {
		panic("no return value specified for FindByChecksum")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*models.Image, error)); ok {
		return returnFunc(ctx, checksum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*models.Image); ok {
		r0 = returnFunc(ctx, checksum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, checksum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_FindByChecksum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByChecksum'
type MockImageReaderWriter_FindByChecksum_Call struct {
	*mock.Call
}

// FindByChecksum is a helper method to define mock.On call
//   - ctx context.Context
//   - checksum string
func (_e *MockImageReaderWriter_Expecter) FindByChecksum(ctx interface{}, checksum interface{}) *MockImageReaderWriter_FindByChecksum_Call {
	return &MockImageReaderWriter_FindByChecksum_Call{Call: _e.mock.On("FindByChecksum", ctx, checksum)}
}

func (_c *MockImageReaderWriter_FindByChecksum_Call) Run(run func(ctx context.Context, checksum string)) *MockImageReaderWriter_FindByChecksum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_FindByChecksum_Call) Return(images []*models.Image, err error) *MockImageReaderWriter_FindByChecksum_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageReaderWriter_FindByChecksum_Call) RunAndReturn(run func(ctx context.Context, checksum string) ([]*models.Image, error)) *MockImageReaderWriter_FindByChecksum_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFileID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) FindByFileID(ctx context.Context, fileID models.FileID) ([]*models.Image, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for FindByFileID")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) ([]*models.Image, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) []*models.Image); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_FindByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFileID'
type MockImageReaderWriter_FindByFileID_Call struct {
	*mock.Call
}

// FindByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FileID
func (_e *MockImageReaderWriter_Expecter) FindByFileID(ctx interface{}, fileID interface{}) *MockImageReaderWriter_FindByFileID_Call {
	return &MockImageReaderWriter_FindByFileID_Call{Call: _e.mock.On("FindByFileID", ctx, fileID)}
}

func (_c *MockImageReaderWriter_FindByFileID_Call) Run(run func(ctx context.Context, fileID models.FileID)) *MockImageReaderWriter_FindByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_FindByFileID_Call) Return(images []*models.Image, err error) *MockImageReaderWriter_FindByFileID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageReaderWriter_FindByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID models.FileID) ([]*models.Image, error)) *MockImageReaderWriter_FindByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFingerprints provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) FindByFingerprints(ctx context.Context, fp []models.Fingerprint) ([]*models.Image, error) {
	ret := _mock.Called(ctx, fp)

	if len(ret) == 0 {
		panic("no return value specified for FindByFingerprints")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Fingerprint) ([]*models.Image, error)); ok {
		return returnFunc(ctx, fp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Fingerprint) []*models.Image); ok {
		r0 = returnFunc(ctx, fp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []models.Fingerprint) error); ok {
		r1 = returnFunc(ctx, fp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_FindByFingerprints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFingerprints'
type MockImageReaderWriter_FindByFingerprints_Call struct {
	*mock.Call
}

// FindByFingerprints is a helper method to define mock.On call
//   - ctx context.Context
//   - fp []models.Fingerprint
func (_e *MockImageReaderWriter_Expecter) FindByFingerprints(ctx interface{}, fp interface{}) *MockImageReaderWriter_FindByFingerprints_Call {
	return &MockImageReaderWriter_FindByFingerprints_Call{Call: _e.mock.On("FindByFingerprints", ctx, fp)}
}

func (_c *MockImageReaderWriter_FindByFingerprints_Call) Run(run func(ctx context.Context, fp []models.Fingerprint)) *MockImageReaderWriter_FindByFingerprints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Fingerprint
		if args[1] != nil {
			arg1 = args[1].([]models.Fingerprint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_FindByFingerprints_Call) Return(images []*models.Image, err error) *MockImageReaderWriter_FindByFingerprints_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageReaderWriter_FindByFingerprints_Call) RunAndReturn(run func(ctx context.Context, fp []models.Fingerprint) ([]*models.Image, error)) *MockImageReaderWriter_FindByFingerprints_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFolderID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) FindByFolderID(ctx context.Context, fileID models.FolderID) ([]*models.Image, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for FindByFolderID")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FolderID) ([]*models.Image, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FolderID) []*models.Image); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FolderID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_FindByFolderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFolderID'
type MockImageReaderWriter_FindByFolderID_Call struct {
	*mock.Call
}

// FindByFolderID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID models.FolderID
func (_e *MockImageReaderWriter_Expecter) FindByFolderID(ctx interface{}, fileID interface{}) *MockImageReaderWriter_FindByFolderID_Call {
	return &MockImageReaderWriter_FindByFolderID_Call{Call: _e.mock.On("FindByFolderID", ctx, fileID)}
}

func (_c *MockImageReaderWriter_FindByFolderID_Call) Run(run func(ctx context.Context, fileID models.FolderID)) *MockImageReaderWriter_FindByFolderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FolderID
		if args[1] != nil {
			arg1 = args[1].(models.FolderID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_FindByFolderID_Call) Return(images []*models.Image, err error) *MockImageReaderWriter_FindByFolderID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageReaderWriter_FindByFolderID_Call) RunAndReturn(run func(ctx context.Context, fileID models.FolderID) ([]*models.Image, error)) *MockImageReaderWriter_FindByFolderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByGalleryID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) FindByGalleryID(ctx context.Context, galleryID int) ([]*models.Image, error) {
	ret := _mock.Called(ctx, galleryID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGalleryID")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Image, error)); ok {
		return returnFunc(ctx, galleryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Image); ok {
		r0 = returnFunc(ctx, galleryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, galleryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_FindByGalleryID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGalleryID'
type MockImageReaderWriter_FindByGalleryID_Call struct {
	*mock.Call
}

// FindByGalleryID is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
func (_e *MockImageReaderWriter_Expecter) FindByGalleryID(ctx interface{}, galleryID interface{}) *MockImageReaderWriter_FindByGalleryID_Call {
	return &MockImageReaderWriter_FindByGalleryID_Call{Call: _e.mock.On("FindByGalleryID", ctx, galleryID)}
}

func (_c *MockImageReaderWriter_FindByGalleryID_Call) Run(run func(ctx context.Context, galleryID int)) *MockImageReaderWriter_FindByGalleryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_FindByGalleryID_Call) Return(images []*models.Image, err error) *MockImageReaderWriter_FindByGalleryID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageReaderWriter_FindByGalleryID_Call) RunAndReturn(run func(ctx context.Context, galleryID int) ([]*models.Image, error)) *MockImageReaderWriter_FindByGalleryID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByGalleryIDIndex provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) FindByGalleryIDIndex(ctx context.Context, galleryID int, index uint) (*models.Image, error) {
	ret := _mock.Called(ctx, galleryID, index)

	if len(ret) == 0 {
		panic("no return value specified for FindByGalleryIDIndex")
	}

	var r0 *models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, uint) (*models.Image, error)); ok {
		return returnFunc(ctx, galleryID, index)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, uint) *models.Image); ok {
		r0 = returnFunc(ctx, galleryID, index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, uint) error); ok {
		r1 = returnFunc(ctx, galleryID, index)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_FindByGalleryIDIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGalleryIDIndex'
type MockImageReaderWriter_FindByGalleryIDIndex_Call struct {
	*mock.Call
}

// FindByGalleryIDIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
//   - index uint
func (_e *MockImageReaderWriter_Expecter) FindByGalleryIDIndex(ctx interface{}, galleryID interface{}, index interface{}) *MockImageReaderWriter_FindByGalleryIDIndex_Call {
	return &MockImageReaderWriter_FindByGalleryIDIndex_Call{Call: _e.mock.On("FindByGalleryIDIndex", ctx, galleryID, index)}
}

func (_c *MockImageReaderWriter_FindByGalleryIDIndex_Call) Run(run func(ctx context.Context, galleryID int, index uint)) *MockImageReaderWriter_FindByGalleryIDIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_FindByGalleryIDIndex_Call) Return(image *models.Image, err error) *MockImageReaderWriter_FindByGalleryIDIndex_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageReaderWriter_FindByGalleryIDIndex_Call) RunAndReturn(run func(ctx context.Context, galleryID int, index uint) (*models.Image, error)) *MockImageReaderWriter_FindByGalleryIDIndex_Call {
	_c.Call.Return(run)
	return _c
}

// FindByZipFileID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) FindByZipFileID(ctx context.Context, zipFileID models.FileID) ([]*models.Image, error) {
	ret := _mock.Called(ctx, zipFileID)

	if len(ret) == 0 {
		panic("no return value specified for FindByZipFileID")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) ([]*models.Image, error)); ok {
		return returnFunc(ctx, zipFileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FileID) []*models.Image); ok {
		r0 = returnFunc(ctx, zipFileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FileID) error); ok {
		r1 = returnFunc(ctx, zipFileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_FindByZipFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByZipFileID'
type MockImageReaderWriter_FindByZipFileID_Call struct {
	*mock.Call
}

// FindByZipFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - zipFileID models.FileID
func (_e *MockImageReaderWriter_Expecter) FindByZipFileID(ctx interface{}, zipFileID interface{}) *MockImageReaderWriter_FindByZipFileID_Call {
	return &MockImageReaderWriter_FindByZipFileID_Call{Call: _e.mock.On("FindByZipFileID", ctx, zipFileID)}
}

func (_c *MockImageReaderWriter_FindByZipFileID_Call) Run(run func(ctx context.Context, zipFileID models.FileID)) *MockImageReaderWriter_FindByZipFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FileID
		if args[1] != nil {
			arg1 = args[1].(models.FileID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_FindByZipFileID_Call) Return(images []*models.Image, err error) *MockImageReaderWriter_FindByZipFileID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageReaderWriter_FindByZipFileID_Call) RunAndReturn(run func(ctx context.Context, zipFileID models.FileID) ([]*models.Image, error)) *MockImageReaderWriter_FindByZipFileID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMany provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Image, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindMany")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]*models.Image, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []*models.Image); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_FindMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMany'
type MockImageReaderWriter_FindMany_Call struct {
	*mock.Call
}

// FindMany is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockImageReaderWriter_Expecter) FindMany(ctx interface{}, ids interface{}) *MockImageReaderWriter_FindMany_Call {
	return &MockImageReaderWriter_FindMany_Call{Call: _e.mock.On("FindMany", ctx, ids)}
}

func (_c *MockImageReaderWriter_FindMany_Call) Run(run func(ctx context.Context, ids []int)) *MockImageReaderWriter_FindMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_FindMany_Call) Return(images []*models.Image, err error) *MockImageReaderWriter_FindMany_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageReaderWriter_FindMany_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]*models.Image, error)) *MockImageReaderWriter_FindMany_Call {
	_c.Call.Return(run)
	return _c
}

// GetFiles provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) GetFiles(ctx context.Context, relatedID int) ([]models.File, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetFiles")
	}

	var r0 []models.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.File, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.File); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_GetFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFiles'
type MockImageReaderWriter_GetFiles_Call struct {
	*mock.Call
}

// GetFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockImageReaderWriter_Expecter) GetFiles(ctx interface{}, relatedID interface{}) *MockImageReaderWriter_GetFiles_Call {
	return &MockImageReaderWriter_GetFiles_Call{Call: _e.mock.On("GetFiles", ctx, relatedID)}
}

func (_c *MockImageReaderWriter_GetFiles_Call) Run(run func(ctx context.Context, relatedID int)) *MockImageReaderWriter_GetFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_GetFiles_Call) Return(files []models.File, err error) *MockImageReaderWriter_GetFiles_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockImageReaderWriter_GetFiles_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]models.File, error)) *MockImageReaderWriter_GetFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetGalleryIDs provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) GetGalleryIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetGalleryIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_GetGalleryIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGalleryIDs'
type MockImageReaderWriter_GetGalleryIDs_Call struct {
	*mock.Call
}

// GetGalleryIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockImageReaderWriter_Expecter) GetGalleryIDs(ctx interface{}, relatedID interface{}) *MockImageReaderWriter_GetGalleryIDs_Call {
	return &MockImageReaderWriter_GetGalleryIDs_Call{Call: _e.mock.On("GetGalleryIDs", ctx, relatedID)}
}

func (_c *MockImageReaderWriter_GetGalleryIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockImageReaderWriter_GetGalleryIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_GetGalleryIDs_Call) Return(ints []int, err error) *MockImageReaderWriter_GetGalleryIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockImageReaderWriter_GetGalleryIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockImageReaderWriter_GetGalleryIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetManyFileIDs provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) GetManyFileIDs(ctx context.Context, ids []int) ([][]models.FileID, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetManyFileIDs")
	}

	var r0 [][]models.FileID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([][]models.FileID, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) [][]models.FileID); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]models.FileID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_GetManyFileIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManyFileIDs'
type MockImageReaderWriter_GetManyFileIDs_Call struct {
	*mock.Call
}

// GetManyFileIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockImageReaderWriter_Expecter) GetManyFileIDs(ctx interface{}, ids interface{}) *MockImageReaderWriter_GetManyFileIDs_Call {
	return &MockImageReaderWriter_GetManyFileIDs_Call{Call: _e.mock.On("GetManyFileIDs", ctx, ids)}
}

func (_c *MockImageReaderWriter_GetManyFileIDs_Call) Run(run func(ctx context.Context, ids []int)) *MockImageReaderWriter_GetManyFileIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_GetManyFileIDs_Call) Return(fileIDss [][]models.FileID, err error) *MockImageReaderWriter_GetManyFileIDs_Call {
	_c.Call.Return(fileIDss, err)
	return _c
}

func (_c *MockImageReaderWriter_GetManyFileIDs_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([][]models.FileID, error)) *MockImageReaderWriter_GetManyFileIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetPerformerIDs provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) GetPerformerIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetPerformerIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_GetPerformerIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPerformerIDs'
type MockImageReaderWriter_GetPerformerIDs_Call struct {
	*mock.Call
}

// GetPerformerIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockImageReaderWriter_Expecter) GetPerformerIDs(ctx interface{}, relatedID interface{}) *MockImageReaderWriter_GetPerformerIDs_Call {
	return &MockImageReaderWriter_GetPerformerIDs_Call{Call: _e.mock.On("GetPerformerIDs", ctx, relatedID)}
}

func (_c *MockImageReaderWriter_GetPerformerIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockImageReaderWriter_GetPerformerIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_GetPerformerIDs_Call) Return(ints []int, err error) *MockImageReaderWriter_GetPerformerIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockImageReaderWriter_GetPerformerIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockImageReaderWriter_GetPerformerIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagIDs provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) GetTagIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_GetTagIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagIDs'
type MockImageReaderWriter_GetTagIDs_Call struct {
	*mock.Call
}

// GetTagIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockImageReaderWriter_Expecter) GetTagIDs(ctx interface{}, relatedID interface{}) *MockImageReaderWriter_GetTagIDs_Call {
	return &MockImageReaderWriter_GetTagIDs_Call{Call: _e.mock.On("GetTagIDs", ctx, relatedID)}
}

func (_c *MockImageReaderWriter_GetTagIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockImageReaderWriter_GetTagIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_GetTagIDs_Call) Return(ints []int, err error) *MockImageReaderWriter_GetTagIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockImageReaderWriter_GetTagIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockImageReaderWriter_GetTagIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLs provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) GetURLs(ctx context.Context, relatedID int) ([]string, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetURLs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_GetURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLs'
type MockImageReaderWriter_GetURLs_Call struct {
	*mock.Call
}

// GetURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockImageReaderWriter_Expecter) GetURLs(ctx interface{}, relatedID interface{}) *MockImageReaderWriter_GetURLs_Call {
	return &MockImageReaderWriter_GetURLs_Call{Call: _e.mock.On("GetURLs", ctx, relatedID)}
}

func (_c *MockImageReaderWriter_GetURLs_Call) Run(run func(ctx context.Context, relatedID int)) *MockImageReaderWriter_GetURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_GetURLs_Call) Return(strings []string, err error) *MockImageReaderWriter_GetURLs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockImageReaderWriter_GetURLs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]string, error)) *MockImageReaderWriter_GetURLs_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementOCounter provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) IncrementOCounter(ctx context.Context, id int) (int, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementOCounter")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_IncrementOCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementOCounter'
type MockImageReaderWriter_IncrementOCounter_Call struct {
	*mock.Call
}

// IncrementOCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockImageReaderWriter_Expecter) IncrementOCounter(ctx interface{}, id interface{}) *MockImageReaderWriter_IncrementOCounter_Call {
	return &MockImageReaderWriter_IncrementOCounter_Call{Call: _e.mock.On("IncrementOCounter", ctx, id)}
}

func (_c *MockImageReaderWriter_IncrementOCounter_Call) Run(run func(ctx context.Context, id int)) *MockImageReaderWriter_IncrementOCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_IncrementOCounter_Call) Return(n int, err error) *MockImageReaderWriter_IncrementOCounter_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_IncrementOCounter_Call) RunAndReturn(run func(ctx context.Context, id int) (int, error)) *MockImageReaderWriter_IncrementOCounter_Call {
	_c.Call.Return(run)
	return _c
}

// OCount provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) OCount(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for OCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_OCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OCount'
type MockImageReaderWriter_OCount_Call struct {
	*mock.Call
}

// OCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImageReaderWriter_Expecter) OCount(ctx interface{}) *MockImageReaderWriter_OCount_Call {
	return &MockImageReaderWriter_OCount_Call{Call: _e.mock.On("OCount", ctx)}
}

func (_c *MockImageReaderWriter_OCount_Call) Run(run func(ctx context.Context)) *MockImageReaderWriter_OCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_OCount_Call) Return(n int, err error) *MockImageReaderWriter_OCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_OCount_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockImageReaderWriter_OCount_Call {
	_c.Call.Return(run)
	return _c
}

// OCountByPerformerID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) OCountByPerformerID(ctx context.Context, performerID int) (int, error) {
	ret := _mock.Called(ctx, performerID)

	if len(ret) == 0 {
		panic("no return value specified for OCountByPerformerID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, performerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, performerID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, performerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_OCountByPerformerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OCountByPerformerID'
type MockImageReaderWriter_OCountByPerformerID_Call struct {
	*mock.Call
}

// OCountByPerformerID is a helper method to define mock.On call
//   - ctx context.Context
//   - performerID int
func (_e *MockImageReaderWriter_Expecter) OCountByPerformerID(ctx interface{}, performerID interface{}) *MockImageReaderWriter_OCountByPerformerID_Call {
	return &MockImageReaderWriter_OCountByPerformerID_Call{Call: _e.mock.On("OCountByPerformerID", ctx, performerID)}
}

func (_c *MockImageReaderWriter_OCountByPerformerID_Call) Run(run func(ctx context.Context, performerID int)) *MockImageReaderWriter_OCountByPerformerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_OCountByPerformerID_Call) Return(n int, err error) *MockImageReaderWriter_OCountByPerformerID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_OCountByPerformerID_Call) RunAndReturn(run func(ctx context.Context, performerID int) (int, error)) *MockImageReaderWriter_OCountByPerformerID_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) Query(ctx context.Context, options models.ImageQueryOptions) (*models.ImageQueryResult, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *models.ImageQueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ImageQueryOptions) (*models.ImageQueryResult, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ImageQueryOptions) *models.ImageQueryResult); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ImageQueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ImageQueryOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockImageReaderWriter_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - options models.ImageQueryOptions
func (_e *MockImageReaderWriter_Expecter) Query(ctx interface{}, options interface{}) *MockImageReaderWriter_Query_Call {
	return &MockImageReaderWriter_Query_Call{Call: _e.mock.On("Query", ctx, options)}
}

func (_c *MockImageReaderWriter_Query_Call) Run(run func(ctx context.Context, options models.ImageQueryOptions)) *MockImageReaderWriter_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ImageQueryOptions
		if args[1] != nil {
			arg1 = args[1].(models.ImageQueryOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_Query_Call) Return(imageQueryResult *models.ImageQueryResult, err error) *MockImageReaderWriter_Query_Call {
	_c.Call.Return(imageQueryResult, err)
	return _c
}

func (_c *MockImageReaderWriter_Query_Call) RunAndReturn(run func(ctx context.Context, options models.ImageQueryOptions) (*models.ImageQueryResult, error)) *MockImageReaderWriter_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryCount provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) QueryCount(ctx context.Context, imageFilter *models.ImageFilterType, findFilter *models.FindFilterType) (int, error) {
	ret := _mock.Called(ctx, imageFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for QueryCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ImageFilterType, *models.FindFilterType) (int, error)); ok {
		return returnFunc(ctx, imageFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ImageFilterType, *models.FindFilterType) int); ok {
		r0 = returnFunc(ctx, imageFilter, findFilter)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.ImageFilterType, *models.FindFilterType) error); ok {
		r1 = returnFunc(ctx, imageFilter, findFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_QueryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryCount'
type MockImageReaderWriter_QueryCount_Call struct {
	*mock.Call
}

// QueryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - imageFilter *models.ImageFilterType
//   - findFilter *models.FindFilterType
func (_e *MockImageReaderWriter_Expecter) QueryCount(ctx interface{}, imageFilter interface{}, findFilter interface{}) *MockImageReaderWriter_QueryCount_Call {
	return &MockImageReaderWriter_QueryCount_Call{Call: _e.mock.On("QueryCount", ctx, imageFilter, findFilter)}
}

func (_c *MockImageReaderWriter_QueryCount_Call) Run(run func(ctx context.Context, imageFilter *models.ImageFilterType, findFilter *models.FindFilterType)) *MockImageReaderWriter_QueryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.ImageFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.ImageFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_QueryCount_Call) Return(n int, err error) *MockImageReaderWriter_QueryCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_QueryCount_Call) RunAndReturn(run func(ctx context.Context, imageFilter *models.ImageFilterType, findFilter *models.FindFilterType) (int, error)) *MockImageReaderWriter_QueryCount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFileID provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) RemoveFileID(ctx context.Context, id int, fileID models.FileID) error {
	ret := _mock.Called(ctx, id, fileID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFileID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.FileID) error); ok {
		r0 = returnFunc(ctx, id, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageReaderWriter_RemoveFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFileID'
type MockImageReaderWriter_RemoveFileID_Call struct {
	*mock.Call
}

// RemoveFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - fileID models.FileID
func (_e *MockImageReaderWriter_Expecter) RemoveFileID(ctx interface{}, id interface{}, fileID interface{}) *MockImageReaderWriter_RemoveFileID_Call {
	return &MockImageReaderWriter_RemoveFileID_Call{Call: _e.mock.On("RemoveFileID", ctx, id, fileID)}
}

func (_c *MockImageReaderWriter_RemoveFileID_Call) Run(run func(ctx context.Context, id int, fileID models.FileID)) *MockImageReaderWriter_RemoveFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.FileID
		if args[2] != nil {
			arg2 = args[2].(models.FileID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_RemoveFileID_Call) Return(err error) *MockImageReaderWriter_RemoveFileID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageReaderWriter_RemoveFileID_Call) RunAndReturn(run func(ctx context.Context, id int, fileID models.FileID) error) *MockImageReaderWriter_RemoveFileID_Call {
	_c.Call.Return(run)
	return _c
}

// ResetOCounter provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) ResetOCounter(ctx context.Context, id int) (int, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ResetOCounter")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_ResetOCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetOCounter'
type MockImageReaderWriter_ResetOCounter_Call struct {
	*mock.Call
}

// ResetOCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockImageReaderWriter_Expecter) ResetOCounter(ctx interface{}, id interface{}) *MockImageReaderWriter_ResetOCounter_Call {
	return &MockImageReaderWriter_ResetOCounter_Call{Call: _e.mock.On("ResetOCounter", ctx, id)}
}

func (_c *MockImageReaderWriter_ResetOCounter_Call) Run(run func(ctx context.Context, id int)) *MockImageReaderWriter_ResetOCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_ResetOCounter_Call) Return(n int, err error) *MockImageReaderWriter_ResetOCounter_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageReaderWriter_ResetOCounter_Call) RunAndReturn(run func(ctx context.Context, id int) (int, error)) *MockImageReaderWriter_ResetOCounter_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) Size(ctx context.Context) (float64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (float64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockImageReaderWriter_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImageReaderWriter_Expecter) Size(ctx interface{}) *MockImageReaderWriter_Size_Call {
	return &MockImageReaderWriter_Size_Call{Call: _e.mock.On("Size", ctx)}
}

func (_c *MockImageReaderWriter_Size_Call) Run(run func(ctx context.Context)) *MockImageReaderWriter_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_Size_Call) Return(f float64, err error) *MockImageReaderWriter_Size_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockImageReaderWriter_Size_Call) RunAndReturn(run func(ctx context.Context) (float64, error)) *MockImageReaderWriter_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) Update(ctx context.Context, updatedImage *models.Image) error {
	ret := _mock.Called(ctx, updatedImage)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Image) error); ok {
		r0 = returnFunc(ctx, updatedImage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageReaderWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockImageReaderWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - updatedImage *models.Image
func (_e *MockImageReaderWriter_Expecter) Update(ctx interface{}, updatedImage interface{}) *MockImageReaderWriter_Update_Call {
	return &MockImageReaderWriter_Update_Call{Call: _e.mock.On("Update", ctx, updatedImage)}
}

func (_c *MockImageReaderWriter_Update_Call) Run(run func(ctx context.Context, updatedImage *models.Image)) *MockImageReaderWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Image
		if args[1] != nil {
			arg1 = args[1].(*models.Image)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_Update_Call) Return(err error) *MockImageReaderWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageReaderWriter_Update_Call) RunAndReturn(run func(ctx context.Context, updatedImage *models.Image) error) *MockImageReaderWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePartial provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) UpdatePartial(ctx context.Context, id int, partial models.ImagePartial) (*models.Image, error) {
	ret := _mock.Called(ctx, id, partial)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePartial")
	}

	var r0 *models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.ImagePartial) (*models.Image, error)); ok {
		return returnFunc(ctx, id, partial)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.ImagePartial) *models.Image); ok {
		r0 = returnFunc(ctx, id, partial)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.ImagePartial) error); ok {
		r1 = returnFunc(ctx, id, partial)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageReaderWriter_UpdatePartial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePartial'
type MockImageReaderWriter_UpdatePartial_Call struct {
	*mock.Call
}

// UpdatePartial is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - partial models.ImagePartial
func (_e *MockImageReaderWriter_Expecter) UpdatePartial(ctx interface{}, id interface{}, partial interface{}) *MockImageReaderWriter_UpdatePartial_Call {
	return &MockImageReaderWriter_UpdatePartial_Call{Call: _e.mock.On("UpdatePartial", ctx, id, partial)}
}

func (_c *MockImageReaderWriter_UpdatePartial_Call) Run(run func(ctx context.Context, id int, partial models.ImagePartial)) *MockImageReaderWriter_UpdatePartial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.ImagePartial
		if args[2] != nil {
			arg2 = args[2].(models.ImagePartial)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_UpdatePartial_Call) Return(image *models.Image, err error) *MockImageReaderWriter_UpdatePartial_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageReaderWriter_UpdatePartial_Call) RunAndReturn(run func(ctx context.Context, id int, partial models.ImagePartial) (*models.Image, error)) *MockImageReaderWriter_UpdatePartial_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePerformers provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) UpdatePerformers(ctx context.Context, imageID int, performerIDs []int) error {
	ret := _mock.Called(ctx, imageID, performerIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePerformers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = returnFunc(ctx, imageID, performerIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageReaderWriter_UpdatePerformers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePerformers'
type MockImageReaderWriter_UpdatePerformers_Call struct {
	*mock.Call
}

// UpdatePerformers is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID int
//   - performerIDs []int
func (_e *MockImageReaderWriter_Expecter) UpdatePerformers(ctx interface{}, imageID interface{}, performerIDs interface{}) *MockImageReaderWriter_UpdatePerformers_Call {
	return &MockImageReaderWriter_UpdatePerformers_Call{Call: _e.mock.On("UpdatePerformers", ctx, imageID, performerIDs)}
}

func (_c *MockImageReaderWriter_UpdatePerformers_Call) Run(run func(ctx context.Context, imageID int, performerIDs []int)) *MockImageReaderWriter_UpdatePerformers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_UpdatePerformers_Call) Return(err error) *MockImageReaderWriter_UpdatePerformers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageReaderWriter_UpdatePerformers_Call) RunAndReturn(run func(ctx context.Context, imageID int, performerIDs []int) error) *MockImageReaderWriter_UpdatePerformers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTags provides a mock function for the type MockImageReaderWriter
func (_mock *MockImageReaderWriter) UpdateTags(ctx context.Context, imageID int, tagIDs []int) error {
	ret := _mock.Called(ctx, imageID, tagIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = returnFunc(ctx, imageID, tagIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageReaderWriter_UpdateTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTags'
type MockImageReaderWriter_UpdateTags_Call struct {
	*mock.Call
}

// UpdateTags is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID int
//   - tagIDs []int
func (_e *MockImageReaderWriter_Expecter) UpdateTags(ctx interface{}, imageID interface{}, tagIDs interface{}) *MockImageReaderWriter_UpdateTags_Call {
	return &MockImageReaderWriter_UpdateTags_Call{Call: _e.mock.On("UpdateTags", ctx, imageID, tagIDs)}
}

func (_c *MockImageReaderWriter_UpdateTags_Call) Run(run func(ctx context.Context, imageID int, tagIDs []int)) *MockImageReaderWriter_UpdateTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageReaderWriter_UpdateTags_Call) Return(err error) *MockImageReaderWriter_UpdateTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageReaderWriter_UpdateTags_Call) RunAndReturn(run func(ctx context.Context, imageID int, tagIDs []int) error) *MockImageReaderWriter_UpdateTags_Call {
	_c.Call.Return(run)
	return _c
}
