// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSavedFilterReaderWriter creates a new instance of MockSavedFilterReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSavedFilterReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSavedFilterReaderWriter {
	mock := &MockSavedFilterReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSavedFilterReaderWriter is an autogenerated mock type for the SavedFilterReaderWriter type
type MockSavedFilterReaderWriter struct {
	mock.Mock
}

type MockSavedFilterReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSavedFilterReaderWriter) EXPECT() *MockSavedFilterReaderWriter_Expecter {
	return &MockSavedFilterReaderWriter_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockSavedFilterReaderWriter
func (_mock *MockSavedFilterReaderWriter) All(ctx context.Context) ([]*models.SavedFilter, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*models.SavedFilter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.SavedFilter, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.SavedFilter); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SavedFilter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavedFilterReaderWriter_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockSavedFilterReaderWriter_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSavedFilterReaderWriter_Expecter) All(ctx interface{}) *MockSavedFilterReaderWriter_All_Call {
	return &MockSavedFilterReaderWriter_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockSavedFilterReaderWriter_All_Call) Run(run func(ctx context.Context)) *MockSavedFilterReaderWriter_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSavedFilterReaderWriter_All_Call) Return(savedFilters []*models.SavedFilter, err error) *MockSavedFilterReaderWriter_All_Call {
	_c.Call.Return(savedFilters, err)
	return _c
}

func (_c *MockSavedFilterReaderWriter_All_Call) RunAndReturn(run func(ctx context.Context) ([]*models.SavedFilter, error)) *MockSavedFilterReaderWriter_All_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockSavedFilterReaderWriter
func (_mock *MockSavedFilterReaderWriter) Create(ctx context.Context, obj *models.SavedFilter) error {
	ret := _mock.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SavedFilter) error); ok {
		r0 = returnFunc(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSavedFilterReaderWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSavedFilterReaderWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *models.SavedFilter
func (_e *MockSavedFilterReaderWriter_Expecter) Create(ctx interface{}, obj interface{}) *MockSavedFilterReaderWriter_Create_Call {
	return &MockSavedFilterReaderWriter_Create_Call{Call: _e.mock.On("Create", ctx, obj)}
}

func (_c *MockSavedFilterReaderWriter_Create_Call) Run(run func(ctx context.Context, obj *models.SavedFilter)) *MockSavedFilterReaderWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.SavedFilter
		if args[1] != nil {
			arg1 = args[1].(*models.SavedFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavedFilterReaderWriter_Create_Call) Return(err error) *MockSavedFilterReaderWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSavedFilterReaderWriter_Create_Call) RunAndReturn(run func(ctx context.Context, obj *models.SavedFilter) error) *MockSavedFilterReaderWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockSavedFilterReaderWriter
func (_mock *MockSavedFilterReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSavedFilterReaderWriter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockSavedFilterReaderWriter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockSavedFilterReaderWriter_Expecter) Destroy(ctx interface{}, id interface{}) *MockSavedFilterReaderWriter_Destroy_Call {
	return &MockSavedFilterReaderWriter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, id)}
}

func (_c *MockSavedFilterReaderWriter_Destroy_Call) Run(run func(ctx context.Context, id int)) *MockSavedFilterReaderWriter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavedFilterReaderWriter_Destroy_Call) Return(err error) *MockSavedFilterReaderWriter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSavedFilterReaderWriter_Destroy_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockSavedFilterReaderWriter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockSavedFilterReaderWriter
func (_mock *MockSavedFilterReaderWriter) Find(ctx context.Context, id int) (*models.SavedFilter, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.SavedFilter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.SavedFilter, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.SavedFilter); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SavedFilter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavedFilterReaderWriter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockSavedFilterReaderWriter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockSavedFilterReaderWriter_Expecter) Find(ctx interface{}, id interface{}) *MockSavedFilterReaderWriter_Find_Call {
	return &MockSavedFilterReaderWriter_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockSavedFilterReaderWriter_Find_Call) Run(run func(ctx context.Context, id int)) *MockSavedFilterReaderWriter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavedFilterReaderWriter_Find_Call) Return(savedFilter *models.SavedFilter, err error) *MockSavedFilterReaderWriter_Find_Call {
	_c.Call.Return(savedFilter, err)
	return _c
}

func (_c *MockSavedFilterReaderWriter_Find_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.SavedFilter, error)) *MockSavedFilterReaderWriter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMode provides a mock function for the type MockSavedFilterReaderWriter
func (_mock *MockSavedFilterReaderWriter) FindByMode(ctx context.Context, mode models.FilterMode) ([]*models.SavedFilter, error) {
	ret := _mock.Called(ctx, mode)

	if len(ret) == 0 {
		panic("no return value specified for FindByMode")
	}

	var r0 []*models.SavedFilter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FilterMode) ([]*models.SavedFilter, error)); ok {
		return returnFunc(ctx, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FilterMode) []*models.SavedFilter); ok {
		r0 = returnFunc(ctx, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SavedFilter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.FilterMode) error); ok {
		r1 = returnFunc(ctx, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavedFilterReaderWriter_FindByMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMode'
type MockSavedFilterReaderWriter_FindByMode_Call struct {
	*mock.Call
}

// FindByMode is a helper method to define mock.On call
//   - ctx context.Context
//   - mode models.FilterMode
func (_e *MockSavedFilterReaderWriter_Expecter) FindByMode(ctx interface{}, mode interface{}) *MockSavedFilterReaderWriter_FindByMode_Call {
	return &MockSavedFilterReaderWriter_FindByMode_Call{Call: _e.mock.On("FindByMode", ctx, mode)}
}

func (_c *MockSavedFilterReaderWriter_FindByMode_Call) Run(run func(ctx context.Context, mode models.FilterMode)) *MockSavedFilterReaderWriter_FindByMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FilterMode
		if args[1] != nil {
			arg1 = args[1].(models.FilterMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavedFilterReaderWriter_FindByMode_Call) Return(savedFilters []*models.SavedFilter, err error) *MockSavedFilterReaderWriter_FindByMode_Call {
	_c.Call.Return(savedFilters, err)
	return _c
}

func (_c *MockSavedFilterReaderWriter_FindByMode_Call) RunAndReturn(run func(ctx context.Context, mode models.FilterMode) ([]*models.SavedFilter, error)) *MockSavedFilterReaderWriter_FindByMode_Call {
	_c.Call.Return(run)
	return _c
}

// FindMany provides a mock function for the type MockSavedFilterReaderWriter
func (_mock *MockSavedFilterReaderWriter) FindMany(ctx context.Context, ids []int, ignoreNotFound bool) ([]*models.SavedFilter, error) {
	ret := _mock.Called(ctx, ids, ignoreNotFound)

	if len(ret) == 0 {
		panic("no return value specified for FindMany")
	}

	var r0 []*models.SavedFilter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int, bool) ([]*models.SavedFilter, error)); ok {
		return returnFunc(ctx, ids, ignoreNotFound)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int, bool) []*models.SavedFilter); ok {
		r0 = returnFunc(ctx, ids, ignoreNotFound)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SavedFilter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int, bool) error); ok {
		r1 = returnFunc(ctx, ids, ignoreNotFound)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavedFilterReaderWriter_FindMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMany'
type MockSavedFilterReaderWriter_FindMany_Call struct {
	*mock.Call
}

// FindMany is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
//   - ignoreNotFound bool
func (_e *MockSavedFilterReaderWriter_Expecter) FindMany(ctx interface{}, ids interface{}, ignoreNotFound interface{}) *MockSavedFilterReaderWriter_FindMany_Call {
	return &MockSavedFilterReaderWriter_FindMany_Call{Call: _e.mock.On("FindMany", ctx, ids, ignoreNotFound)}
}

func (_c *MockSavedFilterReaderWriter_FindMany_Call) Run(run func(ctx context.Context, ids []int, ignoreNotFound bool)) *MockSavedFilterReaderWriter_FindMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSavedFilterReaderWriter_FindMany_Call) Return(savedFilters []*models.SavedFilter, err error) *MockSavedFilterReaderWriter_FindMany_Call {
	_c.Call.Return(savedFilters, err)
	return _c
}

func (_c *MockSavedFilterReaderWriter_FindMany_Call) RunAndReturn(run func(ctx context.Context, ids []int, ignoreNotFound bool) ([]*models.SavedFilter, error)) *MockSavedFilterReaderWriter_FindMany_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSavedFilterReaderWriter
func (_mock *MockSavedFilterReaderWriter) Update(ctx context.Context, obj *models.SavedFilter) error {
	ret := _mock.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SavedFilter) error); ok {
		r0 = returnFunc(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSavedFilterReaderWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSavedFilterReaderWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *models.SavedFilter
func (_e *MockSavedFilterReaderWriter_Expecter) Update(ctx interface{}, obj interface{}) *MockSavedFilterReaderWriter_Update_Call {
	return &MockSavedFilterReaderWriter_Update_Call{Call: _e.mock.On("Update", ctx, obj)}
}

func (_c *MockSavedFilterReaderWriter_Update_Call) Run(run func(ctx context.Context, obj *models.SavedFilter)) *MockSavedFilterReaderWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.SavedFilter
		if args[1] != nil {
			arg1 = args[1].(*models.SavedFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavedFilterReaderWriter_Update_Call) Return(err error) *MockSavedFilterReaderWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSavedFilterReaderWriter_Update_Call) RunAndReturn(run func(ctx context.Context, obj *models.SavedFilter) error) *MockSavedFilterReaderWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}
