// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSceneMarkerReaderWriter creates a new instance of MockSceneMarkerReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSceneMarkerReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSceneMarkerReaderWriter {
	mock := &MockSceneMarkerReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSceneMarkerReaderWriter is an autogenerated mock type for the SceneMarkerReaderWriter type
type MockSceneMarkerReaderWriter struct {
	mock.Mock
}

type MockSceneMarkerReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSceneMarkerReaderWriter) EXPECT() *MockSceneMarkerReaderWriter_Expecter {
	return &MockSceneMarkerReaderWriter_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) All(ctx context.Context) ([]*models.SceneMarker, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*models.SceneMarker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.SceneMarker, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.SceneMarker); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SceneMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockSceneMarkerReaderWriter_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSceneMarkerReaderWriter_Expecter) All(ctx interface{}) *MockSceneMarkerReaderWriter_All_Call {
	return &MockSceneMarkerReaderWriter_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockSceneMarkerReaderWriter_All_Call) Run(run func(ctx context.Context)) *MockSceneMarkerReaderWriter_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_All_Call) Return(sceneMarkers []*models.SceneMarker, err error) *MockSceneMarkerReaderWriter_All_Call {
	_c.Call.Return(sceneMarkers, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_All_Call) RunAndReturn(run func(ctx context.Context) ([]*models.SceneMarker, error)) *MockSceneMarkerReaderWriter_All_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockSceneMarkerReaderWriter_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSceneMarkerReaderWriter_Expecter) Count(ctx interface{}) *MockSceneMarkerReaderWriter_Count_Call {
	return &MockSceneMarkerReaderWriter_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockSceneMarkerReaderWriter_Count_Call) Run(run func(ctx context.Context)) *MockSceneMarkerReaderWriter_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Count_Call) Return(n int, err error) *MockSceneMarkerReaderWriter_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockSceneMarkerReaderWriter_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByTagID provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) CountByTagID(ctx context.Context, tagID int) (int, error) {
	ret := _mock.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTagID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, tagID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, tagID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, tagID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_CountByTagID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTagID'
type MockSceneMarkerReaderWriter_CountByTagID_Call struct {
	*mock.Call
}

// CountByTagID is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
func (_e *MockSceneMarkerReaderWriter_Expecter) CountByTagID(ctx interface{}, tagID interface{}) *MockSceneMarkerReaderWriter_CountByTagID_Call {
	return &MockSceneMarkerReaderWriter_CountByTagID_Call{Call: _e.mock.On("CountByTagID", ctx, tagID)}
}

func (_c *MockSceneMarkerReaderWriter_CountByTagID_Call) Run(run func(ctx context.Context, tagID int)) *MockSceneMarkerReaderWriter_CountByTagID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_CountByTagID_Call) Return(n int, err error) *MockSceneMarkerReaderWriter_CountByTagID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_CountByTagID_Call) RunAndReturn(run func(ctx context.Context, tagID int) (int, error)) *MockSceneMarkerReaderWriter_CountByTagID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) Create(ctx context.Context, newSceneMarker *models.SceneMarker) error {
	ret := _mock.Called(ctx, newSceneMarker)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SceneMarker) error); ok {
		r0 = returnFunc(ctx, newSceneMarker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSceneMarkerReaderWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSceneMarkerReaderWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newSceneMarker *models.SceneMarker
func (_e *MockSceneMarkerReaderWriter_Expecter) Create(ctx interface{}, newSceneMarker interface{}) *MockSceneMarkerReaderWriter_Create_Call {
	return &MockSceneMarkerReaderWriter_Create_Call{Call: _e.mock.On("Create", ctx, newSceneMarker)}
}

func (_c *MockSceneMarkerReaderWriter_Create_Call) Run(run func(ctx context.Context, newSceneMarker *models.SceneMarker)) *MockSceneMarkerReaderWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.SceneMarker
		if args[1] != nil {
			arg1 = args[1].(*models.SceneMarker)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Create_Call) Return(err error) *MockSceneMarkerReaderWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Create_Call) RunAndReturn(run func(ctx context.Context, newSceneMarker *models.SceneMarker) error) *MockSceneMarkerReaderWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSceneMarkerReaderWriter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockSceneMarkerReaderWriter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockSceneMarkerReaderWriter_Expecter) Destroy(ctx interface{}, id interface{}) *MockSceneMarkerReaderWriter_Destroy_Call {
	return &MockSceneMarkerReaderWriter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, id)}
}

func (_c *MockSceneMarkerReaderWriter_Destroy_Call) Run(run func(ctx context.Context, id int)) *MockSceneMarkerReaderWriter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Destroy_Call) Return(err error) *MockSceneMarkerReaderWriter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Destroy_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockSceneMarkerReaderWriter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) Find(ctx context.Context, id int) (*models.SceneMarker, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.SceneMarker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.SceneMarker, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.SceneMarker); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SceneMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockSceneMarkerReaderWriter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockSceneMarkerReaderWriter_Expecter) Find(ctx interface{}, id interface{}) *MockSceneMarkerReaderWriter_Find_Call {
	return &MockSceneMarkerReaderWriter_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockSceneMarkerReaderWriter_Find_Call) Run(run func(ctx context.Context, id int)) *MockSceneMarkerReaderWriter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Find_Call) Return(sceneMarker *models.SceneMarker, err error) *MockSceneMarkerReaderWriter_Find_Call {
	_c.Call.Return(sceneMarker, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Find_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.SceneMarker, error)) *MockSceneMarkerReaderWriter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySceneID provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) FindBySceneID(ctx context.Context, sceneID int) ([]*models.SceneMarker, error) {
	ret := _mock.Called(ctx, sceneID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySceneID")
	}

	var r0 []*models.SceneMarker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.SceneMarker, error)); ok {
		return returnFunc(ctx, sceneID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.SceneMarker); ok {
		r0 = returnFunc(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SceneMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_FindBySceneID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySceneID'
type MockSceneMarkerReaderWriter_FindBySceneID_Call struct {
	*mock.Call
}

// FindBySceneID is a helper method to define mock.On call
//   - ctx context.Context
//   - sceneID int
func (_e *MockSceneMarkerReaderWriter_Expecter) FindBySceneID(ctx interface{}, sceneID interface{}) *MockSceneMarkerReaderWriter_FindBySceneID_Call {
	return &MockSceneMarkerReaderWriter_FindBySceneID_Call{Call: _e.mock.On("FindBySceneID", ctx, sceneID)}
}

func (_c *MockSceneMarkerReaderWriter_FindBySceneID_Call) Run(run func(ctx context.Context, sceneID int)) *MockSceneMarkerReaderWriter_FindBySceneID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_FindBySceneID_Call) Return(sceneMarkers []*models.SceneMarker, err error) *MockSceneMarkerReaderWriter_FindBySceneID_Call {
	_c.Call.Return(sceneMarkers, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_FindBySceneID_Call) RunAndReturn(run func(ctx context.Context, sceneID int) ([]*models.SceneMarker, error)) *MockSceneMarkerReaderWriter_FindBySceneID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMany provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.SceneMarker, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindMany")
	}

	var r0 []*models.SceneMarker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]*models.SceneMarker, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []*models.SceneMarker); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SceneMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_FindMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMany'
type MockSceneMarkerReaderWriter_FindMany_Call struct {
	*mock.Call
}

// FindMany is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockSceneMarkerReaderWriter_Expecter) FindMany(ctx interface{}, ids interface{}) *MockSceneMarkerReaderWriter_FindMany_Call {
	return &MockSceneMarkerReaderWriter_FindMany_Call{Call: _e.mock.On("FindMany", ctx, ids)}
}

func (_c *MockSceneMarkerReaderWriter_FindMany_Call) Run(run func(ctx context.Context, ids []int)) *MockSceneMarkerReaderWriter_FindMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_FindMany_Call) Return(sceneMarkers []*models.SceneMarker, err error) *MockSceneMarkerReaderWriter_FindMany_Call {
	_c.Call.Return(sceneMarkers, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_FindMany_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]*models.SceneMarker, error)) *MockSceneMarkerReaderWriter_FindMany_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarkerStrings provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) GetMarkerStrings(ctx context.Context, q *string, sort *string) ([]*models.MarkerStringsResultType, error) {
	ret := _mock.Called(ctx, q, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkerStrings")
	}

	var r0 []*models.MarkerStringsResultType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *string) ([]*models.MarkerStringsResultType, error)); ok {
		return returnFunc(ctx, q, sort)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *string) []*models.MarkerStringsResultType); ok {
		r0 = returnFunc(ctx, q, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MarkerStringsResultType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, *string) error); ok {
		r1 = returnFunc(ctx, q, sort)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_GetMarkerStrings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarkerStrings'
type MockSceneMarkerReaderWriter_GetMarkerStrings_Call struct {
	*mock.Call
}

// GetMarkerStrings is a helper method to define mock.On call
//   - ctx context.Context
//   - q *string
//   - sort *string
func (_e *MockSceneMarkerReaderWriter_Expecter) GetMarkerStrings(ctx interface{}, q interface{}, sort interface{}) *MockSceneMarkerReaderWriter_GetMarkerStrings_Call {
	return &MockSceneMarkerReaderWriter_GetMarkerStrings_Call{Call: _e.mock.On("GetMarkerStrings", ctx, q, sort)}
}

func (_c *MockSceneMarkerReaderWriter_GetMarkerStrings_Call) Run(run func(ctx context.Context, q *string, sort *string)) *MockSceneMarkerReaderWriter_GetMarkerStrings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_GetMarkerStrings_Call) Return(markerStringsResultTypes []*models.MarkerStringsResultType, err error) *MockSceneMarkerReaderWriter_GetMarkerStrings_Call {
	_c.Call.Return(markerStringsResultTypes, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_GetMarkerStrings_Call) RunAndReturn(run func(ctx context.Context, q *string, sort *string) ([]*models.MarkerStringsResultType, error)) *MockSceneMarkerReaderWriter_GetMarkerStrings_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagIDs provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) GetTagIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_GetTagIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagIDs'
type MockSceneMarkerReaderWriter_GetTagIDs_Call struct {
	*mock.Call
}

// GetTagIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockSceneMarkerReaderWriter_Expecter) GetTagIDs(ctx interface{}, relatedID interface{}) *MockSceneMarkerReaderWriter_GetTagIDs_Call {
	return &MockSceneMarkerReaderWriter_GetTagIDs_Call{Call: _e.mock.On("GetTagIDs", ctx, relatedID)}
}

func (_c *MockSceneMarkerReaderWriter_GetTagIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockSceneMarkerReaderWriter_GetTagIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_GetTagIDs_Call) Return(ints []int, err error) *MockSceneMarkerReaderWriter_GetTagIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_GetTagIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockSceneMarkerReaderWriter_GetTagIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) Query(ctx context.Context, sceneMarkerFilter *models.SceneMarkerFilterType, findFilter *models.FindFilterType) ([]*models.SceneMarker, int, error) {
	ret := _mock.Called(ctx, sceneMarkerFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []*models.SceneMarker
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SceneMarkerFilterType, *models.FindFilterType) ([]*models.SceneMarker, int, error)); ok {
		return returnFunc(ctx, sceneMarkerFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SceneMarkerFilterType, *models.FindFilterType) []*models.SceneMarker); ok {
		r0 = returnFunc(ctx, sceneMarkerFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SceneMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.SceneMarkerFilterType, *models.FindFilterType) int); ok {
		r1 = returnFunc(ctx, sceneMarkerFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *models.SceneMarkerFilterType, *models.FindFilterType) error); ok {
		r2 = returnFunc(ctx, sceneMarkerFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSceneMarkerReaderWriter_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockSceneMarkerReaderWriter_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sceneMarkerFilter *models.SceneMarkerFilterType
//   - findFilter *models.FindFilterType
func (_e *MockSceneMarkerReaderWriter_Expecter) Query(ctx interface{}, sceneMarkerFilter interface{}, findFilter interface{}) *MockSceneMarkerReaderWriter_Query_Call {
	return &MockSceneMarkerReaderWriter_Query_Call{Call: _e.mock.On("Query", ctx, sceneMarkerFilter, findFilter)}
}

func (_c *MockSceneMarkerReaderWriter_Query_Call) Run(run func(ctx context.Context, sceneMarkerFilter *models.SceneMarkerFilterType, findFilter *models.FindFilterType)) *MockSceneMarkerReaderWriter_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.SceneMarkerFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.SceneMarkerFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Query_Call) Return(sceneMarkers []*models.SceneMarker, n int, err error) *MockSceneMarkerReaderWriter_Query_Call {
	_c.Call.Return(sceneMarkers, n, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Query_Call) RunAndReturn(run func(ctx context.Context, sceneMarkerFilter *models.SceneMarkerFilterType, findFilter *models.FindFilterType) ([]*models.SceneMarker, int, error)) *MockSceneMarkerReaderWriter_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryCount provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) QueryCount(ctx context.Context, sceneMarkerFilter *models.SceneMarkerFilterType, findFilter *models.FindFilterType) (int, error) {
	ret := _mock.Called(ctx, sceneMarkerFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for QueryCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SceneMarkerFilterType, *models.FindFilterType) (int, error)); ok {
		return returnFunc(ctx, sceneMarkerFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SceneMarkerFilterType, *models.FindFilterType) int); ok {
		r0 = returnFunc(ctx, sceneMarkerFilter, findFilter)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.SceneMarkerFilterType, *models.FindFilterType) error); ok {
		r1 = returnFunc(ctx, sceneMarkerFilter, findFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_QueryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryCount'
type MockSceneMarkerReaderWriter_QueryCount_Call struct {
	*mock.Call
}

// QueryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - sceneMarkerFilter *models.SceneMarkerFilterType
//   - findFilter *models.FindFilterType
func (_e *MockSceneMarkerReaderWriter_Expecter) QueryCount(ctx interface{}, sceneMarkerFilter interface{}, findFilter interface{}) *MockSceneMarkerReaderWriter_QueryCount_Call {
	return &MockSceneMarkerReaderWriter_QueryCount_Call{Call: _e.mock.On("QueryCount", ctx, sceneMarkerFilter, findFilter)}
}

func (_c *MockSceneMarkerReaderWriter_QueryCount_Call) Run(run func(ctx context.Context, sceneMarkerFilter *models.SceneMarkerFilterType, findFilter *models.FindFilterType)) *MockSceneMarkerReaderWriter_QueryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.SceneMarkerFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.SceneMarkerFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_QueryCount_Call) Return(n int, err error) *MockSceneMarkerReaderWriter_QueryCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_QueryCount_Call) RunAndReturn(run func(ctx context.Context, sceneMarkerFilter *models.SceneMarkerFilterType, findFilter *models.FindFilterType) (int, error)) *MockSceneMarkerReaderWriter_QueryCount_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) Update(ctx context.Context, updatedSceneMarker *models.SceneMarker) error {
	ret := _mock.Called(ctx, updatedSceneMarker)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.SceneMarker) error); ok {
		r0 = returnFunc(ctx, updatedSceneMarker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSceneMarkerReaderWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSceneMarkerReaderWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - updatedSceneMarker *models.SceneMarker
func (_e *MockSceneMarkerReaderWriter_Expecter) Update(ctx interface{}, updatedSceneMarker interface{}) *MockSceneMarkerReaderWriter_Update_Call {
	return &MockSceneMarkerReaderWriter_Update_Call{Call: _e.mock.On("Update", ctx, updatedSceneMarker)}
}

func (_c *MockSceneMarkerReaderWriter_Update_Call) Run(run func(ctx context.Context, updatedSceneMarker *models.SceneMarker)) *MockSceneMarkerReaderWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.SceneMarker
		if args[1] != nil {
			arg1 = args[1].(*models.SceneMarker)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Update_Call) Return(err error) *MockSceneMarkerReaderWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Update_Call) RunAndReturn(run func(ctx context.Context, updatedSceneMarker *models.SceneMarker) error) *MockSceneMarkerReaderWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePartial provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) UpdatePartial(ctx context.Context, id int, updatedSceneMarker models.SceneMarkerPartial) (*models.SceneMarker, error) {
	ret := _mock.Called(ctx, id, updatedSceneMarker)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePartial")
	}

	var r0 *models.SceneMarker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.SceneMarkerPartial) (*models.SceneMarker, error)); ok {
		return returnFunc(ctx, id, updatedSceneMarker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.SceneMarkerPartial) *models.SceneMarker); ok {
		r0 = returnFunc(ctx, id, updatedSceneMarker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SceneMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.SceneMarkerPartial) error); ok {
		r1 = returnFunc(ctx, id, updatedSceneMarker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_UpdatePartial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePartial'
type MockSceneMarkerReaderWriter_UpdatePartial_Call struct {
	*mock.Call
}

// UpdatePartial is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - updatedSceneMarker models.SceneMarkerPartial
func (_e *MockSceneMarkerReaderWriter_Expecter) UpdatePartial(ctx interface{}, id interface{}, updatedSceneMarker interface{}) *MockSceneMarkerReaderWriter_UpdatePartial_Call {
	return &MockSceneMarkerReaderWriter_UpdatePartial_Call{Call: _e.mock.On("UpdatePartial", ctx, id, updatedSceneMarker)}
}

func (_c *MockSceneMarkerReaderWriter_UpdatePartial_Call) Run(run func(ctx context.Context, id int, updatedSceneMarker models.SceneMarkerPartial)) *MockSceneMarkerReaderWriter_UpdatePartial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.SceneMarkerPartial
		if args[2] != nil {
			arg2 = args[2].(models.SceneMarkerPartial)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_UpdatePartial_Call) Return(sceneMarker *models.SceneMarker, err error) *MockSceneMarkerReaderWriter_UpdatePartial_Call {
	_c.Call.Return(sceneMarker, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_UpdatePartial_Call) RunAndReturn(run func(ctx context.Context, id int, updatedSceneMarker models.SceneMarkerPartial) (*models.SceneMarker, error)) *MockSceneMarkerReaderWriter_UpdatePartial_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTags provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) UpdateTags(ctx context.Context, markerID int, tagIDs []int) error {
	ret := _mock.Called(ctx, markerID, tagIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = returnFunc(ctx, markerID, tagIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSceneMarkerReaderWriter_UpdateTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTags'
type MockSceneMarkerReaderWriter_UpdateTags_Call struct {
	*mock.Call
}

// UpdateTags is a helper method to define mock.On call
//   - ctx context.Context
//   - markerID int
//   - tagIDs []int
func (_e *MockSceneMarkerReaderWriter_Expecter) UpdateTags(ctx interface{}, markerID interface{}, tagIDs interface{}) *MockSceneMarkerReaderWriter_UpdateTags_Call {
	return &MockSceneMarkerReaderWriter_UpdateTags_Call{Call: _e.mock.On("UpdateTags", ctx, markerID, tagIDs)}
}

func (_c *MockSceneMarkerReaderWriter_UpdateTags_Call) Run(run func(ctx context.Context, markerID int, tagIDs []int)) *MockSceneMarkerReaderWriter_UpdateTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_UpdateTags_Call) Return(err error) *MockSceneMarkerReaderWriter_UpdateTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_UpdateTags_Call) RunAndReturn(run func(ctx context.Context, markerID int, tagIDs []int) error) *MockSceneMarkerReaderWriter_UpdateTags_Call {
	_c.Call.Return(run)
	return _c
}

// Wall provides a mock function for the type MockSceneMarkerReaderWriter
func (_mock *MockSceneMarkerReaderWriter) Wall(ctx context.Context, q *string) ([]*models.SceneMarker, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Wall")
	}

	var r0 []*models.SceneMarker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) ([]*models.SceneMarker, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) []*models.SceneMarker); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SceneMarker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSceneMarkerReaderWriter_Wall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wall'
type MockSceneMarkerReaderWriter_Wall_Call struct {
	*mock.Call
}

// Wall is a helper method to define mock.On call
//   - ctx context.Context
//   - q *string
func (_e *MockSceneMarkerReaderWriter_Expecter) Wall(ctx interface{}, q interface{}) *MockSceneMarkerReaderWriter_Wall_Call {
	return &MockSceneMarkerReaderWriter_Wall_Call{Call: _e.mock.On("Wall", ctx, q)}
}

func (_c *MockSceneMarkerReaderWriter_Wall_Call) Run(run func(ctx context.Context, q *string)) *MockSceneMarkerReaderWriter_Wall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Wall_Call) Return(sceneMarkers []*models.SceneMarker, err error) *MockSceneMarkerReaderWriter_Wall_Call {
	_c.Call.Return(sceneMarkers, err)
	return _c
}

func (_c *MockSceneMarkerReaderWriter_Wall_Call) RunAndReturn(run func(ctx context.Context, q *string) ([]*models.SceneMarker, error)) *MockSceneMarkerReaderWriter_Wall_Call {
	_c.Call.Return(run)
	return _c
}
