// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStudioReaderWriter creates a new instance of MockStudioReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudioReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudioReaderWriter {
	mock := &MockStudioReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStudioReaderWriter is an autogenerated mock type for the StudioReaderWriter type
type MockStudioReaderWriter struct {
	mock.Mock
}

type MockStudioReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudioReaderWriter) EXPECT() *MockStudioReaderWriter_Expecter {
	return &MockStudioReaderWriter_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) All(ctx context.Context) ([]*models.Studio, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.Studio, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.Studio); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockStudioReaderWriter_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStudioReaderWriter_Expecter) All(ctx interface{}) *MockStudioReaderWriter_All_Call {
	return &MockStudioReaderWriter_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockStudioReaderWriter_All_Call) Run(run func(ctx context.Context)) *MockStudioReaderWriter_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_All_Call) Return(studios []*models.Studio, err error) *MockStudioReaderWriter_All_Call {
	_c.Call.Return(studios, err)
	return _c
}

func (_c *MockStudioReaderWriter_All_Call) RunAndReturn(run func(ctx context.Context) ([]*models.Studio, error)) *MockStudioReaderWriter_All_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockStudioReaderWriter_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStudioReaderWriter_Expecter) Count(ctx interface{}) *MockStudioReaderWriter_Count_Call {
	return &MockStudioReaderWriter_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockStudioReaderWriter_Count_Call) Run(run func(ctx context.Context)) *MockStudioReaderWriter_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_Count_Call) Return(n int, err error) *MockStudioReaderWriter_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStudioReaderWriter_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockStudioReaderWriter_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByTagID provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) CountByTagID(ctx context.Context, tagID int) (int, error) {
	ret := _mock.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTagID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, tagID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, tagID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, tagID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_CountByTagID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTagID'
type MockStudioReaderWriter_CountByTagID_Call struct {
	*mock.Call
}

// CountByTagID is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
func (_e *MockStudioReaderWriter_Expecter) CountByTagID(ctx interface{}, tagID interface{}) *MockStudioReaderWriter_CountByTagID_Call {
	return &MockStudioReaderWriter_CountByTagID_Call{Call: _e.mock.On("CountByTagID", ctx, tagID)}
}

func (_c *MockStudioReaderWriter_CountByTagID_Call) Run(run func(ctx context.Context, tagID int)) *MockStudioReaderWriter_CountByTagID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_CountByTagID_Call) Return(n int, err error) *MockStudioReaderWriter_CountByTagID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStudioReaderWriter_CountByTagID_Call) RunAndReturn(run func(ctx context.Context, tagID int) (int, error)) *MockStudioReaderWriter_CountByTagID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) Create(ctx context.Context, newStudio *models.Studio) error {
	ret := _mock.Called(ctx, newStudio)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Studio) error); ok {
		r0 = returnFunc(ctx, newStudio)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStudioReaderWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStudioReaderWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newStudio *models.Studio
func (_e *MockStudioReaderWriter_Expecter) Create(ctx interface{}, newStudio interface{}) *MockStudioReaderWriter_Create_Call {
	return &MockStudioReaderWriter_Create_Call{Call: _e.mock.On("Create", ctx, newStudio)}
}

func (_c *MockStudioReaderWriter_Create_Call) Run(run func(ctx context.Context, newStudio *models.Studio)) *MockStudioReaderWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Studio
		if args[1] != nil {
			arg1 = args[1].(*models.Studio)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_Create_Call) Return(err error) *MockStudioReaderWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStudioReaderWriter_Create_Call) RunAndReturn(run func(ctx context.Context, newStudio *models.Studio) error) *MockStudioReaderWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStudioReaderWriter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockStudioReaderWriter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockStudioReaderWriter_Expecter) Destroy(ctx interface{}, id interface{}) *MockStudioReaderWriter_Destroy_Call {
	return &MockStudioReaderWriter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, id)}
}

func (_c *MockStudioReaderWriter_Destroy_Call) Run(run func(ctx context.Context, id int)) *MockStudioReaderWriter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_Destroy_Call) Return(err error) *MockStudioReaderWriter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStudioReaderWriter_Destroy_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockStudioReaderWriter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) Find(ctx context.Context, id int) (*models.Studio, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Studio, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Studio); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockStudioReaderWriter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockStudioReaderWriter_Expecter) Find(ctx interface{}, id interface{}) *MockStudioReaderWriter_Find_Call {
	return &MockStudioReaderWriter_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockStudioReaderWriter_Find_Call) Run(run func(ctx context.Context, id int)) *MockStudioReaderWriter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_Find_Call) Return(studio *models.Studio, err error) *MockStudioReaderWriter_Find_Call {
	_c.Call.Return(studio, err)
	return _c
}

func (_c *MockStudioReaderWriter_Find_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Studio, error)) *MockStudioReaderWriter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) FindByName(ctx context.Context, name string, nocase bool) (*models.Studio, error) {
	ret := _mock.Called(ctx, name, nocase)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*models.Studio, error)); ok {
		return returnFunc(ctx, name, nocase)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *models.Studio); ok {
		r0 = returnFunc(ctx, name, nocase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, name, nocase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockStudioReaderWriter_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - nocase bool
func (_e *MockStudioReaderWriter_Expecter) FindByName(ctx interface{}, name interface{}, nocase interface{}) *MockStudioReaderWriter_FindByName_Call {
	return &MockStudioReaderWriter_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name, nocase)}
}

func (_c *MockStudioReaderWriter_FindByName_Call) Run(run func(ctx context.Context, name string, nocase bool)) *MockStudioReaderWriter_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_FindByName_Call) Return(studio *models.Studio, err error) *MockStudioReaderWriter_FindByName_Call {
	_c.Call.Return(studio, err)
	return _c
}

func (_c *MockStudioReaderWriter_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string, nocase bool) (*models.Studio, error)) *MockStudioReaderWriter_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySceneID provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) FindBySceneID(ctx context.Context, sceneID int) (*models.Studio, error) {
	ret := _mock.Called(ctx, sceneID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySceneID")
	}

	var r0 *models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Studio, error)); ok {
		return returnFunc(ctx, sceneID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Studio); ok {
		r0 = returnFunc(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_FindBySceneID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySceneID'
type MockStudioReaderWriter_FindBySceneID_Call struct {
	*mock.Call
}

// FindBySceneID is a helper method to define mock.On call
//   - ctx context.Context
//   - sceneID int
func (_e *MockStudioReaderWriter_Expecter) FindBySceneID(ctx interface{}, sceneID interface{}) *MockStudioReaderWriter_FindBySceneID_Call {
	return &MockStudioReaderWriter_FindBySceneID_Call{Call: _e.mock.On("FindBySceneID", ctx, sceneID)}
}

func (_c *MockStudioReaderWriter_FindBySceneID_Call) Run(run func(ctx context.Context, sceneID int)) *MockStudioReaderWriter_FindBySceneID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_FindBySceneID_Call) Return(studio *models.Studio, err error) *MockStudioReaderWriter_FindBySceneID_Call {
	_c.Call.Return(studio, err)
	return _c
}

func (_c *MockStudioReaderWriter_FindBySceneID_Call) RunAndReturn(run func(ctx context.Context, sceneID int) (*models.Studio, error)) *MockStudioReaderWriter_FindBySceneID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStashID provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) FindByStashID(ctx context.Context, stashID models.StashID) ([]*models.Studio, error) {
	ret := _mock.Called(ctx, stashID)

	if len(ret) == 0 {
		panic("no return value specified for FindByStashID")
	}

	var r0 []*models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StashID) ([]*models.Studio, error)); ok {
		return returnFunc(ctx, stashID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StashID) []*models.Studio); ok {
		r0 = returnFunc(ctx, stashID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.StashID) error); ok {
		r1 = returnFunc(ctx, stashID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_FindByStashID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStashID'
type MockStudioReaderWriter_FindByStashID_Call struct {
	*mock.Call
}

// FindByStashID is a helper method to define mock.On call
//   - ctx context.Context
//   - stashID models.StashID
func (_e *MockStudioReaderWriter_Expecter) FindByStashID(ctx interface{}, stashID interface{}) *MockStudioReaderWriter_FindByStashID_Call {
	return &MockStudioReaderWriter_FindByStashID_Call{Call: _e.mock.On("FindByStashID", ctx, stashID)}
}

func (_c *MockStudioReaderWriter_FindByStashID_Call) Run(run func(ctx context.Context, stashID models.StashID)) *MockStudioReaderWriter_FindByStashID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StashID
		if args[1] != nil {
			arg1 = args[1].(models.StashID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_FindByStashID_Call) Return(studios []*models.Studio, err error) *MockStudioReaderWriter_FindByStashID_Call {
	_c.Call.Return(studios, err)
	return _c
}

func (_c *MockStudioReaderWriter_FindByStashID_Call) RunAndReturn(run func(ctx context.Context, stashID models.StashID) ([]*models.Studio, error)) *MockStudioReaderWriter_FindByStashID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStashIDStatus provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) FindByStashIDStatus(ctx context.Context, hasStashID bool, stashboxEndpoint string) ([]*models.Studio, error) {
	ret := _mock.Called(ctx, hasStashID, stashboxEndpoint)

	if len(ret) == 0 {
		panic("no return value specified for FindByStashIDStatus")
	}

	var r0 []*models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, string) ([]*models.Studio, error)); ok {
		return returnFunc(ctx, hasStashID, stashboxEndpoint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, string) []*models.Studio); ok {
		r0 = returnFunc(ctx, hasStashID, stashboxEndpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, string) error); ok {
		r1 = returnFunc(ctx, hasStashID, stashboxEndpoint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_FindByStashIDStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStashIDStatus'
type MockStudioReaderWriter_FindByStashIDStatus_Call struct {
	*mock.Call
}

// FindByStashIDStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - hasStashID bool
//   - stashboxEndpoint string
func (_e *MockStudioReaderWriter_Expecter) FindByStashIDStatus(ctx interface{}, hasStashID interface{}, stashboxEndpoint interface{}) *MockStudioReaderWriter_FindByStashIDStatus_Call {
	return &MockStudioReaderWriter_FindByStashIDStatus_Call{Call: _e.mock.On("FindByStashIDStatus", ctx, hasStashID, stashboxEndpoint)}
}

func (_c *MockStudioReaderWriter_FindByStashIDStatus_Call) Run(run func(ctx context.Context, hasStashID bool, stashboxEndpoint string)) *MockStudioReaderWriter_FindByStashIDStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_FindByStashIDStatus_Call) Return(studios []*models.Studio, err error) *MockStudioReaderWriter_FindByStashIDStatus_Call {
	_c.Call.Return(studios, err)
	return _c
}

func (_c *MockStudioReaderWriter_FindByStashIDStatus_Call) RunAndReturn(run func(ctx context.Context, hasStashID bool, stashboxEndpoint string) ([]*models.Studio, error)) *MockStudioReaderWriter_FindByStashIDStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindChildren provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) FindChildren(ctx context.Context, id int) ([]*models.Studio, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindChildren")
	}

	var r0 []*models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Studio, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Studio); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_FindChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindChildren'
type MockStudioReaderWriter_FindChildren_Call struct {
	*mock.Call
}

// FindChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockStudioReaderWriter_Expecter) FindChildren(ctx interface{}, id interface{}) *MockStudioReaderWriter_FindChildren_Call {
	return &MockStudioReaderWriter_FindChildren_Call{Call: _e.mock.On("FindChildren", ctx, id)}
}

func (_c *MockStudioReaderWriter_FindChildren_Call) Run(run func(ctx context.Context, id int)) *MockStudioReaderWriter_FindChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_FindChildren_Call) Return(studios []*models.Studio, err error) *MockStudioReaderWriter_FindChildren_Call {
	_c.Call.Return(studios, err)
	return _c
}

func (_c *MockStudioReaderWriter_FindChildren_Call) RunAndReturn(run func(ctx context.Context, id int) ([]*models.Studio, error)) *MockStudioReaderWriter_FindChildren_Call {
	_c.Call.Return(run)
	return _c
}

// FindMany provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Studio, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindMany")
	}

	var r0 []*models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]*models.Studio, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []*models.Studio); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_FindMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMany'
type MockStudioReaderWriter_FindMany_Call struct {
	*mock.Call
}

// FindMany is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockStudioReaderWriter_Expecter) FindMany(ctx interface{}, ids interface{}) *MockStudioReaderWriter_FindMany_Call {
	return &MockStudioReaderWriter_FindMany_Call{Call: _e.mock.On("FindMany", ctx, ids)}
}

func (_c *MockStudioReaderWriter_FindMany_Call) Run(run func(ctx context.Context, ids []int)) *MockStudioReaderWriter_FindMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_FindMany_Call) Return(studios []*models.Studio, err error) *MockStudioReaderWriter_FindMany_Call {
	_c.Call.Return(studios, err)
	return _c
}

func (_c *MockStudioReaderWriter_FindMany_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]*models.Studio, error)) *MockStudioReaderWriter_FindMany_Call {
	_c.Call.Return(run)
	return _c
}

// GetAliases provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) GetAliases(ctx context.Context, relatedID int) ([]string, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetAliases")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_GetAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAliases'
type MockStudioReaderWriter_GetAliases_Call struct {
	*mock.Call
}

// GetAliases is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockStudioReaderWriter_Expecter) GetAliases(ctx interface{}, relatedID interface{}) *MockStudioReaderWriter_GetAliases_Call {
	return &MockStudioReaderWriter_GetAliases_Call{Call: _e.mock.On("GetAliases", ctx, relatedID)}
}

func (_c *MockStudioReaderWriter_GetAliases_Call) Run(run func(ctx context.Context, relatedID int)) *MockStudioReaderWriter_GetAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_GetAliases_Call) Return(strings []string, err error) *MockStudioReaderWriter_GetAliases_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockStudioReaderWriter_GetAliases_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]string, error)) *MockStudioReaderWriter_GetAliases_Call {
	_c.Call.Return(run)
	return _c
}

// GetImage provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) GetImage(ctx context.Context, studioID int) ([]byte, error) {
	ret := _mock.Called(ctx, studioID)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]byte, error)); ok {
		return returnFunc(ctx, studioID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []byte); ok {
		r0 = returnFunc(ctx, studioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, studioID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type MockStudioReaderWriter_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - ctx context.Context
//   - studioID int
func (_e *MockStudioReaderWriter_Expecter) GetImage(ctx interface{}, studioID interface{}) *MockStudioReaderWriter_GetImage_Call {
	return &MockStudioReaderWriter_GetImage_Call{Call: _e.mock.On("GetImage", ctx, studioID)}
}

func (_c *MockStudioReaderWriter_GetImage_Call) Run(run func(ctx context.Context, studioID int)) *MockStudioReaderWriter_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_GetImage_Call) Return(bytes []byte, err error) *MockStudioReaderWriter_GetImage_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockStudioReaderWriter_GetImage_Call) RunAndReturn(run func(ctx context.Context, studioID int) ([]byte, error)) *MockStudioReaderWriter_GetImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetStashIDs provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) GetStashIDs(ctx context.Context, relatedID int) ([]models.StashID, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetStashIDs")
	}

	var r0 []models.StashID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.StashID, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.StashID); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.StashID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_GetStashIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStashIDs'
type MockStudioReaderWriter_GetStashIDs_Call struct {
	*mock.Call
}

// GetStashIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockStudioReaderWriter_Expecter) GetStashIDs(ctx interface{}, relatedID interface{}) *MockStudioReaderWriter_GetStashIDs_Call {
	return &MockStudioReaderWriter_GetStashIDs_Call{Call: _e.mock.On("GetStashIDs", ctx, relatedID)}
}

func (_c *MockStudioReaderWriter_GetStashIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockStudioReaderWriter_GetStashIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_GetStashIDs_Call) Return(stashIDs []models.StashID, err error) *MockStudioReaderWriter_GetStashIDs_Call {
	_c.Call.Return(stashIDs, err)
	return _c
}

func (_c *MockStudioReaderWriter_GetStashIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]models.StashID, error)) *MockStudioReaderWriter_GetStashIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagIDs provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) GetTagIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_GetTagIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagIDs'
type MockStudioReaderWriter_GetTagIDs_Call struct {
	*mock.Call
}

// GetTagIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockStudioReaderWriter_Expecter) GetTagIDs(ctx interface{}, relatedID interface{}) *MockStudioReaderWriter_GetTagIDs_Call {
	return &MockStudioReaderWriter_GetTagIDs_Call{Call: _e.mock.On("GetTagIDs", ctx, relatedID)}
}

func (_c *MockStudioReaderWriter_GetTagIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockStudioReaderWriter_GetTagIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_GetTagIDs_Call) Return(ints []int, err error) *MockStudioReaderWriter_GetTagIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockStudioReaderWriter_GetTagIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockStudioReaderWriter_GetTagIDs_Call {
	_c.Call.Return(run)
	return _c
}

// HasImage provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) HasImage(ctx context.Context, studioID int) (bool, error) {
	ret := _mock.Called(ctx, studioID)

	if len(ret) == 0 {
		panic("no return value specified for HasImage")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, studioID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, studioID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, studioID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_HasImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasImage'
type MockStudioReaderWriter_HasImage_Call struct {
	*mock.Call
}

// HasImage is a helper method to define mock.On call
//   - ctx context.Context
//   - studioID int
func (_e *MockStudioReaderWriter_Expecter) HasImage(ctx interface{}, studioID interface{}) *MockStudioReaderWriter_HasImage_Call {
	return &MockStudioReaderWriter_HasImage_Call{Call: _e.mock.On("HasImage", ctx, studioID)}
}

func (_c *MockStudioReaderWriter_HasImage_Call) Run(run func(ctx context.Context, studioID int)) *MockStudioReaderWriter_HasImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_HasImage_Call) Return(b bool, err error) *MockStudioReaderWriter_HasImage_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStudioReaderWriter_HasImage_Call) RunAndReturn(run func(ctx context.Context, studioID int) (bool, error)) *MockStudioReaderWriter_HasImage_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) Query(ctx context.Context, studioFilter *models.StudioFilterType, findFilter *models.FindFilterType) ([]*models.Studio, int, error) {
	ret := _mock.Called(ctx, studioFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []*models.Studio
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.StudioFilterType, *models.FindFilterType) ([]*models.Studio, int, error)); ok {
		return returnFunc(ctx, studioFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.StudioFilterType, *models.FindFilterType) []*models.Studio); ok {
		r0 = returnFunc(ctx, studioFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.StudioFilterType, *models.FindFilterType) int); ok {
		r1 = returnFunc(ctx, studioFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *models.StudioFilterType, *models.FindFilterType) error); ok {
		r2 = returnFunc(ctx, studioFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStudioReaderWriter_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStudioReaderWriter_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - studioFilter *models.StudioFilterType
//   - findFilter *models.FindFilterType
func (_e *MockStudioReaderWriter_Expecter) Query(ctx interface{}, studioFilter interface{}, findFilter interface{}) *MockStudioReaderWriter_Query_Call {
	return &MockStudioReaderWriter_Query_Call{Call: _e.mock.On("Query", ctx, studioFilter, findFilter)}
}

func (_c *MockStudioReaderWriter_Query_Call) Run(run func(ctx context.Context, studioFilter *models.StudioFilterType, findFilter *models.FindFilterType)) *MockStudioReaderWriter_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.StudioFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.StudioFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_Query_Call) Return(studios []*models.Studio, n int, err error) *MockStudioReaderWriter_Query_Call {
	_c.Call.Return(studios, n, err)
	return _c
}

func (_c *MockStudioReaderWriter_Query_Call) RunAndReturn(run func(ctx context.Context, studioFilter *models.StudioFilterType, findFilter *models.FindFilterType) ([]*models.Studio, int, error)) *MockStudioReaderWriter_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryCount provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) QueryCount(ctx context.Context, studioFilter *models.StudioFilterType, findFilter *models.FindFilterType) (int, error) {
	ret := _mock.Called(ctx, studioFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for QueryCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.StudioFilterType, *models.FindFilterType) (int, error)); ok {
		return returnFunc(ctx, studioFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.StudioFilterType, *models.FindFilterType) int); ok {
		r0 = returnFunc(ctx, studioFilter, findFilter)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.StudioFilterType, *models.FindFilterType) error); ok {
		r1 = returnFunc(ctx, studioFilter, findFilter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_QueryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryCount'
type MockStudioReaderWriter_QueryCount_Call struct {
	*mock.Call
}

// QueryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - studioFilter *models.StudioFilterType
//   - findFilter *models.FindFilterType
func (_e *MockStudioReaderWriter_Expecter) QueryCount(ctx interface{}, studioFilter interface{}, findFilter interface{}) *MockStudioReaderWriter_QueryCount_Call {
	return &MockStudioReaderWriter_QueryCount_Call{Call: _e.mock.On("QueryCount", ctx, studioFilter, findFilter)}
}

func (_c *MockStudioReaderWriter_QueryCount_Call) Run(run func(ctx context.Context, studioFilter *models.StudioFilterType, findFilter *models.FindFilterType)) *MockStudioReaderWriter_QueryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.StudioFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.StudioFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_QueryCount_Call) Return(n int, err error) *MockStudioReaderWriter_QueryCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStudioReaderWriter_QueryCount_Call) RunAndReturn(run func(ctx context.Context, studioFilter *models.StudioFilterType, findFilter *models.FindFilterType) (int, error)) *MockStudioReaderWriter_QueryCount_Call {
	_c.Call.Return(run)
	return _c
}

// QueryForAutoTag provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) QueryForAutoTag(ctx context.Context, words []string) ([]*models.Studio, error) {
	ret := _mock.Called(ctx, words)

	if len(ret) == 0 {
		panic("no return value specified for QueryForAutoTag")
	}

	var r0 []*models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*models.Studio, error)); ok {
		return returnFunc(ctx, words)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*models.Studio); ok {
		r0 = returnFunc(ctx, words)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, words)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_QueryForAutoTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryForAutoTag'
type MockStudioReaderWriter_QueryForAutoTag_Call struct {
	*mock.Call
}

// QueryForAutoTag is a helper method to define mock.On call
//   - ctx context.Context
//   - words []string
func (_e *MockStudioReaderWriter_Expecter) QueryForAutoTag(ctx interface{}, words interface{}) *MockStudioReaderWriter_QueryForAutoTag_Call {
	return &MockStudioReaderWriter_QueryForAutoTag_Call{Call: _e.mock.On("QueryForAutoTag", ctx, words)}
}

func (_c *MockStudioReaderWriter_QueryForAutoTag_Call) Run(run func(ctx context.Context, words []string)) *MockStudioReaderWriter_QueryForAutoTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_QueryForAutoTag_Call) Return(studios []*models.Studio, err error) *MockStudioReaderWriter_QueryForAutoTag_Call {
	_c.Call.Return(studios, err)
	return _c
}

func (_c *MockStudioReaderWriter_QueryForAutoTag_Call) RunAndReturn(run func(ctx context.Context, words []string) ([]*models.Studio, error)) *MockStudioReaderWriter_QueryForAutoTag_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) Update(ctx context.Context, updatedStudio *models.Studio) error {
	ret := _mock.Called(ctx, updatedStudio)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Studio) error); ok {
		r0 = returnFunc(ctx, updatedStudio)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStudioReaderWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStudioReaderWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - updatedStudio *models.Studio
func (_e *MockStudioReaderWriter_Expecter) Update(ctx interface{}, updatedStudio interface{}) *MockStudioReaderWriter_Update_Call {
	return &MockStudioReaderWriter_Update_Call{Call: _e.mock.On("Update", ctx, updatedStudio)}
}

func (_c *MockStudioReaderWriter_Update_Call) Run(run func(ctx context.Context, updatedStudio *models.Studio)) *MockStudioReaderWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Studio
		if args[1] != nil {
			arg1 = args[1].(*models.Studio)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_Update_Call) Return(err error) *MockStudioReaderWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStudioReaderWriter_Update_Call) RunAndReturn(run func(ctx context.Context, updatedStudio *models.Studio) error) *MockStudioReaderWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImage provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) UpdateImage(ctx context.Context, studioID int, image []byte) error {
	ret := _mock.Called(ctx, studioID, image)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []byte) error); ok {
		r0 = returnFunc(ctx, studioID, image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStudioReaderWriter_UpdateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImage'
type MockStudioReaderWriter_UpdateImage_Call struct {
	*mock.Call
}

// UpdateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - studioID int
//   - image []byte
func (_e *MockStudioReaderWriter_Expecter) UpdateImage(ctx interface{}, studioID interface{}, image interface{}) *MockStudioReaderWriter_UpdateImage_Call {
	return &MockStudioReaderWriter_UpdateImage_Call{Call: _e.mock.On("UpdateImage", ctx, studioID, image)}
}

func (_c *MockStudioReaderWriter_UpdateImage_Call) Run(run func(ctx context.Context, studioID int, image []byte)) *MockStudioReaderWriter_UpdateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_UpdateImage_Call) Return(err error) *MockStudioReaderWriter_UpdateImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStudioReaderWriter_UpdateImage_Call) RunAndReturn(run func(ctx context.Context, studioID int, image []byte) error) *MockStudioReaderWriter_UpdateImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePartial provides a mock function for the type MockStudioReaderWriter
func (_mock *MockStudioReaderWriter) UpdatePartial(ctx context.Context, updatedStudio models.StudioPartial) (*models.Studio, error) {
	ret := _mock.Called(ctx, updatedStudio)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePartial")
	}

	var r0 *models.Studio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StudioPartial) (*models.Studio, error)); ok {
		return returnFunc(ctx, updatedStudio)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.StudioPartial) *models.Studio); ok {
		r0 = returnFunc(ctx, updatedStudio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Studio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.StudioPartial) error); ok {
		r1 = returnFunc(ctx, updatedStudio)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudioReaderWriter_UpdatePartial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePartial'
type MockStudioReaderWriter_UpdatePartial_Call struct {
	*mock.Call
}

// UpdatePartial is a helper method to define mock.On call
//   - ctx context.Context
//   - updatedStudio models.StudioPartial
func (_e *MockStudioReaderWriter_Expecter) UpdatePartial(ctx interface{}, updatedStudio interface{}) *MockStudioReaderWriter_UpdatePartial_Call {
	return &MockStudioReaderWriter_UpdatePartial_Call{Call: _e.mock.On("UpdatePartial", ctx, updatedStudio)}
}

func (_c *MockStudioReaderWriter_UpdatePartial_Call) Run(run func(ctx context.Context, updatedStudio models.StudioPartial)) *MockStudioReaderWriter_UpdatePartial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.StudioPartial
		if args[1] != nil {
			arg1 = args[1].(models.StudioPartial)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudioReaderWriter_UpdatePartial_Call) Return(studio *models.Studio, err error) *MockStudioReaderWriter_UpdatePartial_Call {
	_c.Call.Return(studio, err)
	return _c
}

func (_c *MockStudioReaderWriter_UpdatePartial_Call) RunAndReturn(run func(ctx context.Context, updatedStudio models.StudioPartial) (*models.Studio, error)) *MockStudioReaderWriter_UpdatePartial_Call {
	_c.Call.Return(run)
	return _c
}
