// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTagReaderWriter creates a new instance of MockTagReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagReaderWriter {
	mock := &MockTagReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagReaderWriter is an autogenerated mock type for the TagReaderWriter type
type MockTagReaderWriter struct {
	mock.Mock
}

type MockTagReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagReaderWriter) EXPECT() *MockTagReaderWriter_Expecter {
	return &MockTagReaderWriter_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) All(ctx context.Context) ([]*models.Tag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*models.Tag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*models.Tag); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockTagReaderWriter_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTagReaderWriter_Expecter) All(ctx interface{}) *MockTagReaderWriter_All_Call {
	return &MockTagReaderWriter_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockTagReaderWriter_All_Call) Run(run func(ctx context.Context)) *MockTagReaderWriter_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_All_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_All_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_All_Call) RunAndReturn(run func(ctx context.Context) ([]*models.Tag, error)) *MockTagReaderWriter_All_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockTagReaderWriter_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTagReaderWriter_Expecter) Count(ctx interface{}) *MockTagReaderWriter_Count_Call {
	return &MockTagReaderWriter_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockTagReaderWriter_Count_Call) Run(run func(ctx context.Context)) *MockTagReaderWriter_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_Count_Call) Return(n int, err error) *MockTagReaderWriter_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTagReaderWriter_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockTagReaderWriter_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByChildTagID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) CountByChildTagID(ctx context.Context, childID int) (int, error) {
	ret := _mock.Called(ctx, childID)

	if len(ret) == 0 {
		panic("no return value specified for CountByChildTagID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, childID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, childID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, childID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_CountByChildTagID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByChildTagID'
type MockTagReaderWriter_CountByChildTagID_Call struct {
	*mock.Call
}

// CountByChildTagID is a helper method to define mock.On call
//   - ctx context.Context
//   - childID int
func (_e *MockTagReaderWriter_Expecter) CountByChildTagID(ctx interface{}, childID interface{}) *MockTagReaderWriter_CountByChildTagID_Call {
	return &MockTagReaderWriter_CountByChildTagID_Call{Call: _e.mock.On("CountByChildTagID", ctx, childID)}
}

func (_c *MockTagReaderWriter_CountByChildTagID_Call) Run(run func(ctx context.Context, childID int)) *MockTagReaderWriter_CountByChildTagID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_CountByChildTagID_Call) Return(n int, err error) *MockTagReaderWriter_CountByChildTagID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTagReaderWriter_CountByChildTagID_Call) RunAndReturn(run func(ctx context.Context, childID int) (int, error)) *MockTagReaderWriter_CountByChildTagID_Call {
	_c.Call.Return(run)
	return _c
}

// CountByParentTagID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) CountByParentTagID(ctx context.Context, parentID int) (int, error) {
	ret := _mock.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CountByParentTagID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, parentID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_CountByParentTagID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByParentTagID'
type MockTagReaderWriter_CountByParentTagID_Call struct {
	*mock.Call
}

// CountByParentTagID is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int
func (_e *MockTagReaderWriter_Expecter) CountByParentTagID(ctx interface{}, parentID interface{}) *MockTagReaderWriter_CountByParentTagID_Call {
	return &MockTagReaderWriter_CountByParentTagID_Call{Call: _e.mock.On("CountByParentTagID", ctx, parentID)}
}

func (_c *MockTagReaderWriter_CountByParentTagID_Call) Run(run func(ctx context.Context, parentID int)) *MockTagReaderWriter_CountByParentTagID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_CountByParentTagID_Call) Return(n int, err error) *MockTagReaderWriter_CountByParentTagID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTagReaderWriter_CountByParentTagID_Call) RunAndReturn(run func(ctx context.Context, parentID int) (int, error)) *MockTagReaderWriter_CountByParentTagID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) Create(ctx context.Context, newTag *models.Tag) error {
	ret := _mock.Called(ctx, newTag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Tag) error); ok {
		r0 = returnFunc(ctx, newTag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagReaderWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTagReaderWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newTag *models.Tag
func (_e *MockTagReaderWriter_Expecter) Create(ctx interface{}, newTag interface{}) *MockTagReaderWriter_Create_Call {
	return &MockTagReaderWriter_Create_Call{Call: _e.mock.On("Create", ctx, newTag)}
}

func (_c *MockTagReaderWriter_Create_Call) Run(run func(ctx context.Context, newTag *models.Tag)) *MockTagReaderWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Tag
		if args[1] != nil {
			arg1 = args[1].(*models.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_Create_Call) Return(err error) *MockTagReaderWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagReaderWriter_Create_Call) RunAndReturn(run func(ctx context.Context, newTag *models.Tag) error) *MockTagReaderWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagReaderWriter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockTagReaderWriter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTagReaderWriter_Expecter) Destroy(ctx interface{}, id interface{}) *MockTagReaderWriter_Destroy_Call {
	return &MockTagReaderWriter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, id)}
}

func (_c *MockTagReaderWriter_Destroy_Call) Run(run func(ctx context.Context, id int)) *MockTagReaderWriter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_Destroy_Call) Return(err error) *MockTagReaderWriter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagReaderWriter_Destroy_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockTagReaderWriter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) Find(ctx context.Context, id int) (*models.Tag, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Tag, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Tag); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockTagReaderWriter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTagReaderWriter_Expecter) Find(ctx interface{}, id interface{}) *MockTagReaderWriter_Find_Call {
	return &MockTagReaderWriter_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockTagReaderWriter_Find_Call) Run(run func(ctx context.Context, id int)) *MockTagReaderWriter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_Find_Call) Return(tag *models.Tag, err error) *MockTagReaderWriter_Find_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockTagReaderWriter_Find_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.Tag, error)) *MockTagReaderWriter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllAncestors provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindAllAncestors(ctx context.Context, tagID int, excludeIDs []int) ([]*models.TagPath, error) {
	ret := _mock.Called(ctx, tagID, excludeIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindAllAncestors")
	}

	var r0 []*models.TagPath
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) ([]*models.TagPath, error)); ok {
		return returnFunc(ctx, tagID, excludeIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) []*models.TagPath); ok {
		r0 = returnFunc(ctx, tagID, excludeIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TagPath)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []int) error); ok {
		r1 = returnFunc(ctx, tagID, excludeIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindAllAncestors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllAncestors'
type MockTagReaderWriter_FindAllAncestors_Call struct {
	*mock.Call
}

// FindAllAncestors is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
//   - excludeIDs []int
func (_e *MockTagReaderWriter_Expecter) FindAllAncestors(ctx interface{}, tagID interface{}, excludeIDs interface{}) *MockTagReaderWriter_FindAllAncestors_Call {
	return &MockTagReaderWriter_FindAllAncestors_Call{Call: _e.mock.On("FindAllAncestors", ctx, tagID, excludeIDs)}
}

func (_c *MockTagReaderWriter_FindAllAncestors_Call) Run(run func(ctx context.Context, tagID int, excludeIDs []int)) *MockTagReaderWriter_FindAllAncestors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindAllAncestors_Call) Return(tagPaths []*models.TagPath, err error) *MockTagReaderWriter_FindAllAncestors_Call {
	_c.Call.Return(tagPaths, err)
	return _c
}

func (_c *MockTagReaderWriter_FindAllAncestors_Call) RunAndReturn(run func(ctx context.Context, tagID int, excludeIDs []int) ([]*models.TagPath, error)) *MockTagReaderWriter_FindAllAncestors_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllDescendants provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindAllDescendants(ctx context.Context, tagID int, excludeIDs []int) ([]*models.TagPath, error) {
	ret := _mock.Called(ctx, tagID, excludeIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindAllDescendants")
	}

	var r0 []*models.TagPath
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) ([]*models.TagPath, error)); ok {
		return returnFunc(ctx, tagID, excludeIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) []*models.TagPath); ok {
		r0 = returnFunc(ctx, tagID, excludeIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TagPath)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []int) error); ok {
		r1 = returnFunc(ctx, tagID, excludeIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindAllDescendants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllDescendants'
type MockTagReaderWriter_FindAllDescendants_Call struct {
	*mock.Call
}

// FindAllDescendants is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
//   - excludeIDs []int
func (_e *MockTagReaderWriter_Expecter) FindAllDescendants(ctx interface{}, tagID interface{}, excludeIDs interface{}) *MockTagReaderWriter_FindAllDescendants_Call {
	return &MockTagReaderWriter_FindAllDescendants_Call{Call: _e.mock.On("FindAllDescendants", ctx, tagID, excludeIDs)}
}

func (_c *MockTagReaderWriter_FindAllDescendants_Call) Run(run func(ctx context.Context, tagID int, excludeIDs []int)) *MockTagReaderWriter_FindAllDescendants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindAllDescendants_Call) Return(tagPaths []*models.TagPath, err error) *MockTagReaderWriter_FindAllDescendants_Call {
	_c.Call.Return(tagPaths, err)
	return _c
}

func (_c *MockTagReaderWriter_FindAllDescendants_Call) RunAndReturn(run func(ctx context.Context, tagID int, excludeIDs []int) ([]*models.TagPath, error)) *MockTagReaderWriter_FindAllDescendants_Call {
	_c.Call.Return(run)
	return _c
}

// FindByChildTagID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByChildTagID(ctx context.Context, childID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, childID)

	if len(ret) == 0 {
		panic("no return value specified for FindByChildTagID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, childID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, childID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, childID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByChildTagID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByChildTagID'
type MockTagReaderWriter_FindByChildTagID_Call struct {
	*mock.Call
}

// FindByChildTagID is a helper method to define mock.On call
//   - ctx context.Context
//   - childID int
func (_e *MockTagReaderWriter_Expecter) FindByChildTagID(ctx interface{}, childID interface{}) *MockTagReaderWriter_FindByChildTagID_Call {
	return &MockTagReaderWriter_FindByChildTagID_Call{Call: _e.mock.On("FindByChildTagID", ctx, childID)}
}

func (_c *MockTagReaderWriter_FindByChildTagID_Call) Run(run func(ctx context.Context, childID int)) *MockTagReaderWriter_FindByChildTagID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByChildTagID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindByChildTagID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByChildTagID_Call) RunAndReturn(run func(ctx context.Context, childID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindByChildTagID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByGalleryID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByGalleryID(ctx context.Context, galleryID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, galleryID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGalleryID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, galleryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, galleryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, galleryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByGalleryID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGalleryID'
type MockTagReaderWriter_FindByGalleryID_Call struct {
	*mock.Call
}

// FindByGalleryID is a helper method to define mock.On call
//   - ctx context.Context
//   - galleryID int
func (_e *MockTagReaderWriter_Expecter) FindByGalleryID(ctx interface{}, galleryID interface{}) *MockTagReaderWriter_FindByGalleryID_Call {
	return &MockTagReaderWriter_FindByGalleryID_Call{Call: _e.mock.On("FindByGalleryID", ctx, galleryID)}
}

func (_c *MockTagReaderWriter_FindByGalleryID_Call) Run(run func(ctx context.Context, galleryID int)) *MockTagReaderWriter_FindByGalleryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByGalleryID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindByGalleryID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByGalleryID_Call) RunAndReturn(run func(ctx context.Context, galleryID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindByGalleryID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByGroupID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByGroupID(ctx context.Context, groupID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGroupID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGroupID'
type MockTagReaderWriter_FindByGroupID_Call struct {
	*mock.Call
}

// FindByGroupID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int
func (_e *MockTagReaderWriter_Expecter) FindByGroupID(ctx interface{}, groupID interface{}) *MockTagReaderWriter_FindByGroupID_Call {
	return &MockTagReaderWriter_FindByGroupID_Call{Call: _e.mock.On("FindByGroupID", ctx, groupID)}
}

func (_c *MockTagReaderWriter_FindByGroupID_Call) Run(run func(ctx context.Context, groupID int)) *MockTagReaderWriter_FindByGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByGroupID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindByGroupID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByGroupID_Call) RunAndReturn(run func(ctx context.Context, groupID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindByGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByImageID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByImageID(ctx context.Context, imageID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for FindByImageID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByImageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByImageID'
type MockTagReaderWriter_FindByImageID_Call struct {
	*mock.Call
}

// FindByImageID is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID int
func (_e *MockTagReaderWriter_Expecter) FindByImageID(ctx interface{}, imageID interface{}) *MockTagReaderWriter_FindByImageID_Call {
	return &MockTagReaderWriter_FindByImageID_Call{Call: _e.mock.On("FindByImageID", ctx, imageID)}
}

func (_c *MockTagReaderWriter_FindByImageID_Call) Run(run func(ctx context.Context, imageID int)) *MockTagReaderWriter_FindByImageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByImageID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindByImageID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByImageID_Call) RunAndReturn(run func(ctx context.Context, imageID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindByImageID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByName(ctx context.Context, name string, nocase bool) (*models.Tag, error) {
	ret := _mock.Called(ctx, name, nocase)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*models.Tag, error)); ok {
		return returnFunc(ctx, name, nocase)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *models.Tag); ok {
		r0 = returnFunc(ctx, name, nocase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, name, nocase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockTagReaderWriter_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - nocase bool
func (_e *MockTagReaderWriter_Expecter) FindByName(ctx interface{}, name interface{}, nocase interface{}) *MockTagReaderWriter_FindByName_Call {
	return &MockTagReaderWriter_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name, nocase)}
}

func (_c *MockTagReaderWriter_FindByName_Call) Run(run func(ctx context.Context, name string, nocase bool)) *MockTagReaderWriter_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByName_Call) Return(tag *models.Tag, err error) *MockTagReaderWriter_FindByName_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string, nocase bool) (*models.Tag, error)) *MockTagReaderWriter_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNames provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByNames(ctx context.Context, names []string, nocase bool) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, names, nocase)

	if len(ret) == 0 {
		panic("no return value specified for FindByNames")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, names, nocase)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, bool) []*models.Tag); ok {
		r0 = returnFunc(ctx, names, nocase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, bool) error); ok {
		r1 = returnFunc(ctx, names, nocase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNames'
type MockTagReaderWriter_FindByNames_Call struct {
	*mock.Call
}

// FindByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
//   - nocase bool
func (_e *MockTagReaderWriter_Expecter) FindByNames(ctx interface{}, names interface{}, nocase interface{}) *MockTagReaderWriter_FindByNames_Call {
	return &MockTagReaderWriter_FindByNames_Call{Call: _e.mock.On("FindByNames", ctx, names, nocase)}
}

func (_c *MockTagReaderWriter_FindByNames_Call) Run(run func(ctx context.Context, names []string, nocase bool)) *MockTagReaderWriter_FindByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByNames_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindByNames_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByNames_Call) RunAndReturn(run func(ctx context.Context, names []string, nocase bool) ([]*models.Tag, error)) *MockTagReaderWriter_FindByNames_Call {
	_c.Call.Return(run)
	return _c
}

// FindByParentTagID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByParentTagID(ctx context.Context, parentID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByParentTagID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByParentTagID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByParentTagID'
type MockTagReaderWriter_FindByParentTagID_Call struct {
	*mock.Call
}

// FindByParentTagID is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int
func (_e *MockTagReaderWriter_Expecter) FindByParentTagID(ctx interface{}, parentID interface{}) *MockTagReaderWriter_FindByParentTagID_Call {
	return &MockTagReaderWriter_FindByParentTagID_Call{Call: _e.mock.On("FindByParentTagID", ctx, parentID)}
}

func (_c *MockTagReaderWriter_FindByParentTagID_Call) Run(run func(ctx context.Context, parentID int)) *MockTagReaderWriter_FindByParentTagID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByParentTagID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindByParentTagID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByParentTagID_Call) RunAndReturn(run func(ctx context.Context, parentID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindByParentTagID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPerformerID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByPerformerID(ctx context.Context, performerID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, performerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByPerformerID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, performerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, performerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, performerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByPerformerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPerformerID'
type MockTagReaderWriter_FindByPerformerID_Call struct {
	*mock.Call
}

// FindByPerformerID is a helper method to define mock.On call
//   - ctx context.Context
//   - performerID int
func (_e *MockTagReaderWriter_Expecter) FindByPerformerID(ctx interface{}, performerID interface{}) *MockTagReaderWriter_FindByPerformerID_Call {
	return &MockTagReaderWriter_FindByPerformerID_Call{Call: _e.mock.On("FindByPerformerID", ctx, performerID)}
}

func (_c *MockTagReaderWriter_FindByPerformerID_Call) Run(run func(ctx context.Context, performerID int)) *MockTagReaderWriter_FindByPerformerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByPerformerID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindByPerformerID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByPerformerID_Call) RunAndReturn(run func(ctx context.Context, performerID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindByPerformerID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySceneID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindBySceneID(ctx context.Context, sceneID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, sceneID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySceneID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, sceneID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindBySceneID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySceneID'
type MockTagReaderWriter_FindBySceneID_Call struct {
	*mock.Call
}

// FindBySceneID is a helper method to define mock.On call
//   - ctx context.Context
//   - sceneID int
func (_e *MockTagReaderWriter_Expecter) FindBySceneID(ctx interface{}, sceneID interface{}) *MockTagReaderWriter_FindBySceneID_Call {
	return &MockTagReaderWriter_FindBySceneID_Call{Call: _e.mock.On("FindBySceneID", ctx, sceneID)}
}

func (_c *MockTagReaderWriter_FindBySceneID_Call) Run(run func(ctx context.Context, sceneID int)) *MockTagReaderWriter_FindBySceneID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindBySceneID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindBySceneID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindBySceneID_Call) RunAndReturn(run func(ctx context.Context, sceneID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindBySceneID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySceneMarkerID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindBySceneMarkerID(ctx context.Context, sceneMarkerID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, sceneMarkerID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySceneMarkerID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, sceneMarkerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, sceneMarkerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, sceneMarkerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindBySceneMarkerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySceneMarkerID'
type MockTagReaderWriter_FindBySceneMarkerID_Call struct {
	*mock.Call
}

// FindBySceneMarkerID is a helper method to define mock.On call
//   - ctx context.Context
//   - sceneMarkerID int
func (_e *MockTagReaderWriter_Expecter) FindBySceneMarkerID(ctx interface{}, sceneMarkerID interface{}) *MockTagReaderWriter_FindBySceneMarkerID_Call {
	return &MockTagReaderWriter_FindBySceneMarkerID_Call{Call: _e.mock.On("FindBySceneMarkerID", ctx, sceneMarkerID)}
}

func (_c *MockTagReaderWriter_FindBySceneMarkerID_Call) Run(run func(ctx context.Context, sceneMarkerID int)) *MockTagReaderWriter_FindBySceneMarkerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindBySceneMarkerID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindBySceneMarkerID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindBySceneMarkerID_Call) RunAndReturn(run func(ctx context.Context, sceneMarkerID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindBySceneMarkerID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStudioID provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindByStudioID(ctx context.Context, studioID int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, studioID)

	if len(ret) == 0 {
		panic("no return value specified for FindByStudioID")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, studioID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*models.Tag); ok {
		r0 = returnFunc(ctx, studioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, studioID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindByStudioID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStudioID'
type MockTagReaderWriter_FindByStudioID_Call struct {
	*mock.Call
}

// FindByStudioID is a helper method to define mock.On call
//   - ctx context.Context
//   - studioID int
func (_e *MockTagReaderWriter_Expecter) FindByStudioID(ctx interface{}, studioID interface{}) *MockTagReaderWriter_FindByStudioID_Call {
	return &MockTagReaderWriter_FindByStudioID_Call{Call: _e.mock.On("FindByStudioID", ctx, studioID)}
}

func (_c *MockTagReaderWriter_FindByStudioID_Call) Run(run func(ctx context.Context, studioID int)) *MockTagReaderWriter_FindByStudioID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindByStudioID_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindByStudioID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindByStudioID_Call) RunAndReturn(run func(ctx context.Context, studioID int) ([]*models.Tag, error)) *MockTagReaderWriter_FindByStudioID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMany provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindMany")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int) []*models.Tag); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_FindMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMany'
type MockTagReaderWriter_FindMany_Call struct {
	*mock.Call
}

// FindMany is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int
func (_e *MockTagReaderWriter_Expecter) FindMany(ctx interface{}, ids interface{}) *MockTagReaderWriter_FindMany_Call {
	return &MockTagReaderWriter_FindMany_Call{Call: _e.mock.On("FindMany", ctx, ids)}
}

func (_c *MockTagReaderWriter_FindMany_Call) Run(run func(ctx context.Context, ids []int)) *MockTagReaderWriter_FindMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_FindMany_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_FindMany_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_FindMany_Call) RunAndReturn(run func(ctx context.Context, ids []int) ([]*models.Tag, error)) *MockTagReaderWriter_FindMany_Call {
	_c.Call.Return(run)
	return _c
}

// GetAliases provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) GetAliases(ctx context.Context, relatedID int) ([]string, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetAliases")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_GetAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAliases'
type MockTagReaderWriter_GetAliases_Call struct {
	*mock.Call
}

// GetAliases is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockTagReaderWriter_Expecter) GetAliases(ctx interface{}, relatedID interface{}) *MockTagReaderWriter_GetAliases_Call {
	return &MockTagReaderWriter_GetAliases_Call{Call: _e.mock.On("GetAliases", ctx, relatedID)}
}

func (_c *MockTagReaderWriter_GetAliases_Call) Run(run func(ctx context.Context, relatedID int)) *MockTagReaderWriter_GetAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_GetAliases_Call) Return(strings []string, err error) *MockTagReaderWriter_GetAliases_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTagReaderWriter_GetAliases_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]string, error)) *MockTagReaderWriter_GetAliases_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildIDs provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) GetChildIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetChildIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_GetChildIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildIDs'
type MockTagReaderWriter_GetChildIDs_Call struct {
	*mock.Call
}

// GetChildIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockTagReaderWriter_Expecter) GetChildIDs(ctx interface{}, relatedID interface{}) *MockTagReaderWriter_GetChildIDs_Call {
	return &MockTagReaderWriter_GetChildIDs_Call{Call: _e.mock.On("GetChildIDs", ctx, relatedID)}
}

func (_c *MockTagReaderWriter_GetChildIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockTagReaderWriter_GetChildIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_GetChildIDs_Call) Return(ints []int, err error) *MockTagReaderWriter_GetChildIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockTagReaderWriter_GetChildIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockTagReaderWriter_GetChildIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetImage provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) GetImage(ctx context.Context, tagID int) ([]byte, error) {
	ret := _mock.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]byte, error)); ok {
		return returnFunc(ctx, tagID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []byte); ok {
		r0 = returnFunc(ctx, tagID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, tagID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type MockTagReaderWriter_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
func (_e *MockTagReaderWriter_Expecter) GetImage(ctx interface{}, tagID interface{}) *MockTagReaderWriter_GetImage_Call {
	return &MockTagReaderWriter_GetImage_Call{Call: _e.mock.On("GetImage", ctx, tagID)}
}

func (_c *MockTagReaderWriter_GetImage_Call) Run(run func(ctx context.Context, tagID int)) *MockTagReaderWriter_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_GetImage_Call) Return(bytes []byte, err error) *MockTagReaderWriter_GetImage_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTagReaderWriter_GetImage_Call) RunAndReturn(run func(ctx context.Context, tagID int) ([]byte, error)) *MockTagReaderWriter_GetImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetParentIDs provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) GetParentIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _mock.Called(ctx, relatedID)

	if len(ret) == 0 {
		panic("no return value specified for GetParentIDs")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return returnFunc(ctx, relatedID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = returnFunc(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_GetParentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParentIDs'
type MockTagReaderWriter_GetParentIDs_Call struct {
	*mock.Call
}

// GetParentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - relatedID int
func (_e *MockTagReaderWriter_Expecter) GetParentIDs(ctx interface{}, relatedID interface{}) *MockTagReaderWriter_GetParentIDs_Call {
	return &MockTagReaderWriter_GetParentIDs_Call{Call: _e.mock.On("GetParentIDs", ctx, relatedID)}
}

func (_c *MockTagReaderWriter_GetParentIDs_Call) Run(run func(ctx context.Context, relatedID int)) *MockTagReaderWriter_GetParentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_GetParentIDs_Call) Return(ints []int, err error) *MockTagReaderWriter_GetParentIDs_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockTagReaderWriter_GetParentIDs_Call) RunAndReturn(run func(ctx context.Context, relatedID int) ([]int, error)) *MockTagReaderWriter_GetParentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// HasImage provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) HasImage(ctx context.Context, tagID int) (bool, error) {
	ret := _mock.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for HasImage")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, tagID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, tagID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, tagID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_HasImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasImage'
type MockTagReaderWriter_HasImage_Call struct {
	*mock.Call
}

// HasImage is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
func (_e *MockTagReaderWriter_Expecter) HasImage(ctx interface{}, tagID interface{}) *MockTagReaderWriter_HasImage_Call {
	return &MockTagReaderWriter_HasImage_Call{Call: _e.mock.On("HasImage", ctx, tagID)}
}

func (_c *MockTagReaderWriter_HasImage_Call) Run(run func(ctx context.Context, tagID int)) *MockTagReaderWriter_HasImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_HasImage_Call) Return(b bool, err error) *MockTagReaderWriter_HasImage_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTagReaderWriter_HasImage_Call) RunAndReturn(run func(ctx context.Context, tagID int) (bool, error)) *MockTagReaderWriter_HasImage_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) Merge(ctx context.Context, source []int, destination int) error {
	ret := _mock.Called(ctx, source, destination)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int, int) error); ok {
		r0 = returnFunc(ctx, source, destination)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagReaderWriter_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockTagReaderWriter_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
//   - source []int
//   - destination int
func (_e *MockTagReaderWriter_Expecter) Merge(ctx interface{}, source interface{}, destination interface{}) *MockTagReaderWriter_Merge_Call {
	return &MockTagReaderWriter_Merge_Call{Call: _e.mock.On("Merge", ctx, source, destination)}
}

func (_c *MockTagReaderWriter_Merge_Call) Run(run func(ctx context.Context, source []int, destination int)) *MockTagReaderWriter_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_Merge_Call) Return(err error) *MockTagReaderWriter_Merge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagReaderWriter_Merge_Call) RunAndReturn(run func(ctx context.Context, source []int, destination int) error) *MockTagReaderWriter_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) Query(ctx context.Context, tagFilter *models.TagFilterType, findFilter *models.FindFilterType) ([]*models.Tag, int, error) {
	ret := _mock.Called(ctx, tagFilter, findFilter)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []*models.Tag
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.TagFilterType, *models.FindFilterType) ([]*models.Tag, int, error)); ok {
		return returnFunc(ctx, tagFilter, findFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.TagFilterType, *models.FindFilterType) []*models.Tag); ok {
		r0 = returnFunc(ctx, tagFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.TagFilterType, *models.FindFilterType) int); ok {
		r1 = returnFunc(ctx, tagFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *models.TagFilterType, *models.FindFilterType) error); ok {
		r2 = returnFunc(ctx, tagFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTagReaderWriter_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockTagReaderWriter_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - tagFilter *models.TagFilterType
//   - findFilter *models.FindFilterType
func (_e *MockTagReaderWriter_Expecter) Query(ctx interface{}, tagFilter interface{}, findFilter interface{}) *MockTagReaderWriter_Query_Call {
	return &MockTagReaderWriter_Query_Call{Call: _e.mock.On("Query", ctx, tagFilter, findFilter)}
}

func (_c *MockTagReaderWriter_Query_Call) Run(run func(ctx context.Context, tagFilter *models.TagFilterType, findFilter *models.FindFilterType)) *MockTagReaderWriter_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.TagFilterType
		if args[1] != nil {
			arg1 = args[1].(*models.TagFilterType)
		}
		var arg2 *models.FindFilterType
		if args[2] != nil {
			arg2 = args[2].(*models.FindFilterType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_Query_Call) Return(tags []*models.Tag, n int, err error) *MockTagReaderWriter_Query_Call {
	_c.Call.Return(tags, n, err)
	return _c
}

func (_c *MockTagReaderWriter_Query_Call) RunAndReturn(run func(ctx context.Context, tagFilter *models.TagFilterType, findFilter *models.FindFilterType) ([]*models.Tag, int, error)) *MockTagReaderWriter_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryForAutoTag provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) QueryForAutoTag(ctx context.Context, words []string) ([]*models.Tag, error) {
	ret := _mock.Called(ctx, words)

	if len(ret) == 0 {
		panic("no return value specified for QueryForAutoTag")
	}

	var r0 []*models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*models.Tag, error)); ok {
		return returnFunc(ctx, words)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*models.Tag); ok {
		r0 = returnFunc(ctx, words)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, words)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_QueryForAutoTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryForAutoTag'
type MockTagReaderWriter_QueryForAutoTag_Call struct {
	*mock.Call
}

// QueryForAutoTag is a helper method to define mock.On call
//   - ctx context.Context
//   - words []string
func (_e *MockTagReaderWriter_Expecter) QueryForAutoTag(ctx interface{}, words interface{}) *MockTagReaderWriter_QueryForAutoTag_Call {
	return &MockTagReaderWriter_QueryForAutoTag_Call{Call: _e.mock.On("QueryForAutoTag", ctx, words)}
}

func (_c *MockTagReaderWriter_QueryForAutoTag_Call) Run(run func(ctx context.Context, words []string)) *MockTagReaderWriter_QueryForAutoTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_QueryForAutoTag_Call) Return(tags []*models.Tag, err error) *MockTagReaderWriter_QueryForAutoTag_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagReaderWriter_QueryForAutoTag_Call) RunAndReturn(run func(ctx context.Context, words []string) ([]*models.Tag, error)) *MockTagReaderWriter_QueryForAutoTag_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) Update(ctx context.Context, updatedTag *models.Tag) error {
	ret := _mock.Called(ctx, updatedTag)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Tag) error); ok {
		r0 = returnFunc(ctx, updatedTag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagReaderWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTagReaderWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - updatedTag *models.Tag
func (_e *MockTagReaderWriter_Expecter) Update(ctx interface{}, updatedTag interface{}) *MockTagReaderWriter_Update_Call {
	return &MockTagReaderWriter_Update_Call{Call: _e.mock.On("Update", ctx, updatedTag)}
}

func (_c *MockTagReaderWriter_Update_Call) Run(run func(ctx context.Context, updatedTag *models.Tag)) *MockTagReaderWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Tag
		if args[1] != nil {
			arg1 = args[1].(*models.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_Update_Call) Return(err error) *MockTagReaderWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagReaderWriter_Update_Call) RunAndReturn(run func(ctx context.Context, updatedTag *models.Tag) error) *MockTagReaderWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAliases provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) UpdateAliases(ctx context.Context, tagID int, aliases []string) error {
	ret := _mock.Called(ctx, tagID, aliases)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAliases")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []string) error); ok {
		r0 = returnFunc(ctx, tagID, aliases)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagReaderWriter_UpdateAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAliases'
type MockTagReaderWriter_UpdateAliases_Call struct {
	*mock.Call
}

// UpdateAliases is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
//   - aliases []string
func (_e *MockTagReaderWriter_Expecter) UpdateAliases(ctx interface{}, tagID interface{}, aliases interface{}) *MockTagReaderWriter_UpdateAliases_Call {
	return &MockTagReaderWriter_UpdateAliases_Call{Call: _e.mock.On("UpdateAliases", ctx, tagID, aliases)}
}

func (_c *MockTagReaderWriter_UpdateAliases_Call) Run(run func(ctx context.Context, tagID int, aliases []string)) *MockTagReaderWriter_UpdateAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_UpdateAliases_Call) Return(err error) *MockTagReaderWriter_UpdateAliases_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagReaderWriter_UpdateAliases_Call) RunAndReturn(run func(ctx context.Context, tagID int, aliases []string) error) *MockTagReaderWriter_UpdateAliases_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateChildTags provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) UpdateChildTags(ctx context.Context, tagID int, parentIDs []int) error {
	ret := _mock.Called(ctx, tagID, parentIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChildTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = returnFunc(ctx, tagID, parentIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagReaderWriter_UpdateChildTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateChildTags'
type MockTagReaderWriter_UpdateChildTags_Call struct {
	*mock.Call
}

// UpdateChildTags is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
//   - parentIDs []int
func (_e *MockTagReaderWriter_Expecter) UpdateChildTags(ctx interface{}, tagID interface{}, parentIDs interface{}) *MockTagReaderWriter_UpdateChildTags_Call {
	return &MockTagReaderWriter_UpdateChildTags_Call{Call: _e.mock.On("UpdateChildTags", ctx, tagID, parentIDs)}
}

func (_c *MockTagReaderWriter_UpdateChildTags_Call) Run(run func(ctx context.Context, tagID int, parentIDs []int)) *MockTagReaderWriter_UpdateChildTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_UpdateChildTags_Call) Return(err error) *MockTagReaderWriter_UpdateChildTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagReaderWriter_UpdateChildTags_Call) RunAndReturn(run func(ctx context.Context, tagID int, parentIDs []int) error) *MockTagReaderWriter_UpdateChildTags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImage provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) UpdateImage(ctx context.Context, tagID int, image []byte) error {
	ret := _mock.Called(ctx, tagID, image)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []byte) error); ok {
		r0 = returnFunc(ctx, tagID, image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagReaderWriter_UpdateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImage'
type MockTagReaderWriter_UpdateImage_Call struct {
	*mock.Call
}

// UpdateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
//   - image []byte
func (_e *MockTagReaderWriter_Expecter) UpdateImage(ctx interface{}, tagID interface{}, image interface{}) *MockTagReaderWriter_UpdateImage_Call {
	return &MockTagReaderWriter_UpdateImage_Call{Call: _e.mock.On("UpdateImage", ctx, tagID, image)}
}

func (_c *MockTagReaderWriter_UpdateImage_Call) Run(run func(ctx context.Context, tagID int, image []byte)) *MockTagReaderWriter_UpdateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_UpdateImage_Call) Return(err error) *MockTagReaderWriter_UpdateImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagReaderWriter_UpdateImage_Call) RunAndReturn(run func(ctx context.Context, tagID int, image []byte) error) *MockTagReaderWriter_UpdateImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateParentTags provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) UpdateParentTags(ctx context.Context, tagID int, parentIDs []int) error {
	ret := _mock.Called(ctx, tagID, parentIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParentTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = returnFunc(ctx, tagID, parentIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagReaderWriter_UpdateParentTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateParentTags'
type MockTagReaderWriter_UpdateParentTags_Call struct {
	*mock.Call
}

// UpdateParentTags is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int
//   - parentIDs []int
func (_e *MockTagReaderWriter_Expecter) UpdateParentTags(ctx interface{}, tagID interface{}, parentIDs interface{}) *MockTagReaderWriter_UpdateParentTags_Call {
	return &MockTagReaderWriter_UpdateParentTags_Call{Call: _e.mock.On("UpdateParentTags", ctx, tagID, parentIDs)}
}

func (_c *MockTagReaderWriter_UpdateParentTags_Call) Run(run func(ctx context.Context, tagID int, parentIDs []int)) *MockTagReaderWriter_UpdateParentTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_UpdateParentTags_Call) Return(err error) *MockTagReaderWriter_UpdateParentTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagReaderWriter_UpdateParentTags_Call) RunAndReturn(run func(ctx context.Context, tagID int, parentIDs []int) error) *MockTagReaderWriter_UpdateParentTags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePartial provides a mock function for the type MockTagReaderWriter
func (_mock *MockTagReaderWriter) UpdatePartial(ctx context.Context, id int, updateTag models.TagPartial) (*models.Tag, error) {
	ret := _mock.Called(ctx, id, updateTag)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePartial")
	}

	var r0 *models.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.TagPartial) (*models.Tag, error)); ok {
		return returnFunc(ctx, id, updateTag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.TagPartial) *models.Tag); ok {
		r0 = returnFunc(ctx, id, updateTag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.TagPartial) error); ok {
		r1 = returnFunc(ctx, id, updateTag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagReaderWriter_UpdatePartial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePartial'
type MockTagReaderWriter_UpdatePartial_Call struct {
	*mock.Call
}

// UpdatePartial is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - updateTag models.TagPartial
func (_e *MockTagReaderWriter_Expecter) UpdatePartial(ctx interface{}, id interface{}, updateTag interface{}) *MockTagReaderWriter_UpdatePartial_Call {
	return &MockTagReaderWriter_UpdatePartial_Call{Call: _e.mock.On("UpdatePartial", ctx, id, updateTag)}
}

func (_c *MockTagReaderWriter_UpdatePartial_Call) Run(run func(ctx context.Context, id int, updateTag models.TagPartial)) *MockTagReaderWriter_UpdatePartial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.TagPartial
		if args[2] != nil {
			arg2 = args[2].(models.TagPartial)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagReaderWriter_UpdatePartial_Call) Return(tag *models.Tag, err error) *MockTagReaderWriter_UpdatePartial_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockTagReaderWriter_UpdatePartial_Call) RunAndReturn(run func(ctx context.Context, id int, updateTag models.TagPartial) (*models.Tag, error)) *MockTagReaderWriter_UpdatePartial_Call {
	_c.Call.Return(run)
	return _c
}
